import type { Problem } from "./types";

// Pinterest design-round prompts, continued: the catalog update pipeline
// (main prompt 6) and the first two shorter sketches (image upload/serving,
// pins-and-boards data model). See seed-design-a.ts for the series notes.

export const designProblemsC: Problem[] = [
  {
    slug: "design-catalog-update-pipeline",
    title: "Design a Merchant Catalog Update Pipeline",
    category: "system-design",
    difficulty: "medium",
    companies: ["pinterest"],
    summary:
      "Idempotent bulk ingestion with per-item ordering, fairness, and safe deletions.",
    prompt: [
      '"Merchants give Pinterest their product catalogs: scheduled feed files with up to tens of millions of items, plus real-time API updates for price and availability. Design the pipeline that ingests, validates, and publishes products as shoppable pins, keeps price and stock fresh within minutes, and tells merchants what went wrong."',
      "",
      "Feeds come as daily full snapshots and hourly deltas (CSV/TSV/XML) plus an item-level API. Full feeds imply deletion semantics: an item missing from a full feed is gone. Most merchants have thousands of items; a few have 20M+ — a 20M-item feed cannot starve a 200-item feed. Validation rejects at item level with reasons, never the whole feed for one bad row. Per item, last writer wins by source timestamp: an old feed must not overwrite a newer API price.",
      "",
      "Cover: idempotency and per-item ordering across the two write sources, safe full-feed deletion, fairness and backpressure across merchants, and how a price change reaches the pin within minutes.",
      "",
      '*Reported as: "Design Catalog Update Pipeline — scalable, fault-tolerant, with partitioning for horizontal scalability" (PracHub); Prepfully lists a product-catalogue example. Shopping is a strategic Pinterest surface.*',
    ].join("\n"),
    hints: [
      "One topic keyed by (merchant, item) gives per-item ordering for feed rows and API updates alike; version every write with its source timestamp and make the catalog write conditional (only if newer). Replays then become no-ops.",
      "Diff before you fan out: typical daily change rate is 5–10%, so emitting only changes cuts every downstream consumer's load 10–20×, and an append-only change log makes any consumer rebuildable by replay.",
      "Naive full-feed deletion is how a truncated download erases a merchant's catalog. Track last_seen_run per item, hold retirement when the candidate set exceeds a threshold, and retire in two steps: out-of-stock first, hard delete after a grace period.",
    ],
    rubric: [
      "- **Idempotency and ordering** — partition by item key for in-order processing, versioned conditional writes by source timestamp so late feed rows can't regress a fresher API update, and chunk reprocessing that's harmless by construction.",
      "- **Diff-driven fan-out** — validate-and-diff as the single catalog writer emitting a changes topic; downstream consumers (pin writer, images, search, eligibility) subscribe independently so a slow image fetch never delays a price.",
      "- **Safe deletions** — last_seen_run tracking, a guardrail holding retirement when too much of the catalog would vanish, and two-step retirement (out-of-stock → hard delete after grace).",
      "- **Fairness and lanes** — per-merchant concurrency quotas at the parser, separate lanes by feed size, priority partitions for the API fast lane, and lag monitoring with different severities per lane.",
      "- **Merchant feedback** — per-run status with item-level error codes and samples; a schema change shows up as a spike in one rejection code, not a pipeline failure.",
      "- **Store choice** — justifies a transactional store with (merchant, item) keys, conditional updates, per-merchant range scans, and secondary indexes for tooling; plus content-addressed images so re-submits don't re-fetch.",
    ].join("\n"),
    solution: [
      "## Numbers and shape",
      "",
      "Assume 100k merchant catalogs, ~2B items total. A daily full refresh is 2B item rows/day ≈ 23k items/s average and very bursty (feeds cluster at midnight local). Typical daily change rate is 5–10%, so diffing before fan-out cuts downstream load 10–20×. A 20M-row feed in 10k-row chunks is 2,000 parallelizable chunks. New images ~2% of items/day ≈ 40M fetches — a separate async lane that must not gate price updates. Catalog store: 2B × ~2 KB ≈ 4 TB plus change history.",
      "",
      "## Data and flow",
      "",
      "```",
      "POST /v1/catalogs/{id}/feeds        { url, format, schedule, type: full|delta }",
      "POST /v1/catalogs/{id}/items:batch  [{ item_id, price, availability, ..., source_ts }]   -- fast lane",
      "GET  /v1/catalogs/{id}/runs/{run}   → { received, accepted, rejected, errors:[{item_id, code, sample}] }",
      "",
      "catalog_item (TiDB / sharded MySQL)  pk (merchant_id, item_id) → { attrs json, version: source_ts,",
      "                                     run_id, last_seen_run, content_hash }",
      "item_change  (append-only)           (merchant_id, item_id, version) → changed fields   -- audit + replay",
      "Kafka: items-in (key = merchant:item) · item-changes (same key) · images",
      "```",
      "",
      "The scheduler fetches each feed on cadence (retries; a content hash skips unchanged files), lands it on object storage, and a parser streams it into chunks, writing each row to items-in keyed by (merchant, item). API updates hit the same topic, same key, tagged priority. Validation workers normalize, read the item's current version, and — only if the content hash changed and the source timestamp is newer — write the new version and emit a change event. Downstream consumers subscribe to changes independently. A run-status service aggregates counters and rejection samples for the merchant dashboard.",
      "",
      "## Deep dive: idempotency and ordering per item",
      "",
      "Two sources write the same item: the daily feed and the real-time API. Version every write with its source timestamp (feed rows inherit the snapshot time) and make the write conditional: apply only if incoming.version > current.version. Partitioning by item key means one worker processes both writes in order; the version check means a replayed or late feed row can't regress a fresher API price. Reprocessing a chunk re-emits the same conditional writes — no-ops.",
      "",
      "## Deep dive: full-feed deletions without catastrophes",
      "",
      "A full feed asserts \"these are all my items\", but naive deletion means a truncated download erases a catalog. Track last_seen_run per item; at run completion, items last seen before this run are retirement candidates. Guardrails: if candidates exceed ~30% of the catalog, hold retirement, mark the run \"needs review\", and alert the merchant. Retire in two steps — out-of-stock first, hard delete after a grace period — so a merchant who fixes their feed tomorrow recovers without re-creating pins.",
      "",
      "## Deep dive: fairness and backpressure",
      "",
      "Partitioning by item spreads a huge merchant across all partitions — good for throughput, bad for fairness: 2,000 chunks can fill every backlog. Controls: a per-merchant concurrency quota at the parser (N chunks in flight), separate lanes by feed size so small feeds never queue behind large ones, and dedicated priority partitions for the API fast lane drained first. Lag on the fast lane is a page; lag on the bulk lane is a graph.",
      "",
      "## Storage and the change log",
      "",
      "The catalog store wants point lookups, conditional updates, per-merchant range scans (retirement, export), and secondary indexes for tooling — the TiDB profile, or sharded MySQL keyed by (merchant, item). The append-only change log is what makes the system debuggable: rebuild any consumer by replay, and \"what was this price on Tuesday\" is a query, not an investigation. Images are content-addressed by byte hash so re-submitting the same URL doesn't re-fetch.",
      "",
      "## Probes to expect",
      "",
      "- *A feed is 10x larger than yesterday.* The per-merchant quota throttles it; others are unaffected; the run takes longer and the status page says so. If half the items are missing too, the retirement guardrail holds deletions.",
      "- *A worker crashes mid-chunk.* Kafka redelivers from the last committed offset; conditional versioned writes make the replay a no-op for applied rows.",
      "- *How does a price reach the pin in minutes?* The API path skips fetch/parse, lands on priority partitions, and the pin writer subscribes to changes directly — the budget is Kafka hops plus one conditional write.",
    ].join("\n"),
  },
  {
    slug: "design-image-upload-serving",
    title: "Design Image Upload and Serving for Pins",
    category: "system-design",
    difficulty: "medium",
    companies: ["pinterest"],
    summary:
      "Presigned uploads, content-addressed variants, and a CDN that caches forever.",
    prompt: [
      '"Design the architecture for uploading and storing images for pins: hundreds of millions of users saving image-heavy content, processed into the sizes the product needs and served globally with low latency."',
      "",
      "Scope: upload, dedup, processing into variants, global serving, and the pin-creation flow — not the image ML. Assume ~50M new images/day at ~1 MB, while serving is orders of magnitude larger (feeds show dozens of images per page at tens of thousands of QPS → millions of image requests per second), so the design is about the CDN and the variants, not the upload.",
      "",
      "Cover: how bytes get in without transiting your API tier, dedup when the same image is saved by a million users, cache-friendly URLs, and what the pin row shows while processing is still running.",
      "",
      '*Reported as: "Design the architecture for uploading and storing images (pins)" (Design Gurus); "image storage" (Glassdoor forum). Also surfaces as a follow-up inside the feed or pin-save prompt.*',
    ].join("\n"),
    hints: [
      "The API tier should never proxy image bytes: hand the client a presigned URL and let it PUT straight to object storage; an upload-complete event drives everything else asynchronously.",
      "Content-address everything: dedup by byte hash so a million saves store one image, and make URLs immutable (/i/{sig}/{variant}.jpg) so the CDN can cache forever with no stale-cache story.",
      "The pin must exist before processing finishes. Create it in a 'processing' state and flip to 'ready' — and decide which readers filter on that state.",
    ],
    rubric: [
      "- **Upload path** — presigned direct-to-object-storage PUT, API never proxies bytes; completion event on a queue drives async processing.",
      "- **Dedup and addressing** — content-hash signature index storing each image once; immutable content-addressed URLs enabling cache-forever CDN behavior with no invalidation problem.",
      "- **Processing pipeline** — async fan-out: safety classification, fixed variant set (thumbnail/grid/full), embedding computation, metadata write; an origin service that can generate a missing variant on demand.",
      "- **Serving economics** — recognizes serving dwarfs ingest by orders of magnitude and designs for CDN hit rate and variant strategy, not upload throughput.",
      "- **Pin-creation consistency** — pin created in processing state with placeholder, flipped to ready; feed candidate generators filter on state; pin and board mapping colocated on the board's shard with a counter maintained transactionally, not COUNT(*).",
    ].join("\n"),
    solution: [
      "## Numbers",
      "",
      "~50M new images/day at ~1 MB is ~50 TB/day of ingest — real but boring. Serving is the problem: dozens of images per feed page at tens of thousands of feed QPS means millions of image requests per second, so the design lives or dies on the CDN and the variant strategy.",
      "",
      "## Design",
      "",
      "The client asks the API for a presigned upload URL and PUTs directly to object storage — the API tier never touches bytes. The upload-complete event on Kafka drives an async pipeline:",
      "",
      "1. **Dedup** — content-hash against a signature index; the same image saved by a million users is stored once.",
      "2. **Safety classification** before anything becomes visible.",
      "3. **Variants** — resize into a fixed set (thumbnail, grid, full).",
      "4. **Embedding** computation for retrieval and related-pins.",
      "5. **Metadata write** completing the flow.",
      "",
      "The pin row in sharded MySQL references the image by content signature. URLs are immutable and content-addressed — `/i/{sig}/{variant}.jpg` — so the CDN caches forever and a stale-cache problem cannot exist. Origin is object storage behind a small origin service that can generate a missing variant on demand (so adding a new variant size doesn't require reprocessing the archive).",
      "",
      "## Deep dive: pin-creation consistency",
      "",
      "The pin must exist before the image finishes processing. Create it in a `processing` state with a placeholder, flip to `ready` when the pipeline completes, and have the feed's candidate generators filter on state so half-processed pins never surface. Placement matters: the pin row and its board→pin mapping land on the same shard (Pinterest places pins on their board's shard) so the save is one local transaction — and the board's pin count is a counter updated in that transaction, never a COUNT(*).",
      "",
      "## Probes to expect",
      "",
      "- *Same image uploaded twice concurrently?* Both uploads land; the signature index write is idempotent (set-if-absent by hash); the loser's blob is garbage-collected.",
      "- *A new product surface needs a new size?* On-demand variant generation at the origin, cached by the CDN thereafter — no archive reprocess.",
      "- *Takedown with cache-forever URLs?* Content-addressed URLs are immutable, so takedown is enforced at the origin and edge by signature blocklist, and the pin row flips state — the URL disappearing from products, not the cache expiring.",
    ].join("\n"),
  },
  {
    slug: "design-pins-boards-data-model",
    title: "Design the Pins and Boards Data Model",
    category: "system-design",
    difficulty: "medium",
    companies: ["pinterest"],
    summary:
      "Sharding a relational model: object tables, mapping tables, no cross-shard joins.",
    prompt: [
      '"Design the storage for pins, boards, and saves: users save pins to boards, follow boards and users, and browse a board\'s pins in order. Billions of pins, hundreds of millions of users, high availability."',
      "",
      "This is really \"do you know how to shard a relational model\" — Pinterest's signature public engineering story. Cover: the id scheme, where objects and relationships live, how \"pins on board B\" and \"boards of user U\" stay single-shard queries, what happens transactionally on a save versus asynchronously, and the hot cases (moving pins between shards, boards with millions of pins).",
      "",
      '*Reported as: "Design a pin save and board management service — metadata storage, graph relationships, high availability" (System Design Handbook).*',
    ].join("\n"),
    hints: [
      "Pinterest's actual scheme: a 64-bit id packing 16 bits of shard, 10 bits of type, and 36 bits of local id — the id itself tells you where the row lives, so routing needs no lookup service.",
      "Mapping tables (from_id, to_id, sequence) live on the shard of the 'from' object, making one-to-many reads single-shard range scans ordered by sequence. No cross-shard joins, no foreign keys; the app fetches ids then batch-fetches objects through a cache.",
      "Decide what's transactional: the pin insert and board→pin mapping share the board's shard and commit together; user→pins, follower fan-out, and search indexing ride a job queue afterwards.",
    ],
    rubric: [
      "- **Id and placement scheme** — a shard-encoding id (shard/type/local) so routing is arithmetic; pins placed on their board's shard so the save path is single-shard.",
      "- **Object vs mapping tables** — JSON-blob object tables keyed by local id; (from_id, to_id, sequence) mapping tables on the from-side shard turning one-to-many reads into ordered single-shard range scans.",
      "- **Write choreography** — synchronous: pin row + board mapping in one local transaction (plus the board's pin counter); asynchronous via job queue: user mapping, follower fan-out, search index.",
      "- **No cross-shard joins** — application-level joins: fetch ids, batch-fetch objects, cache in front; explains why this beats distributed joins operationally.",
      "- **Hot and awkward cases** — pin move across shards as insert + tombstone with background reconcile (brief double-appearance tolerated); huge boards paginated by sequence range, their fan-out on the pull path.",
      "- **Store justification** — why MySQL in 2011 (maturity, row transactions, ordered scans) and what points at TiDB today (same properties with automatic sharding).",
    ].join("\n"),
    solution: [
      "## The scheme",
      "",
      "Pinterest's actual design. A 64-bit id packs 16 bits of shard id, 10 bits of type id, and 36 bits of local id — the id alone routes the query, no lookup service. Object tables (pins, boards, users) store a JSON blob keyed by local id. Relationships are mapping tables `(from_id, to_id, sequence)` living on the shard of the **from** object:",
      "",
      "- \"pins on board B\" → single-shard range scan on B's shard, ordered by sequence.",
      "- \"boards of user U\" → likewise on U's shard.",
      "",
      "No cross-shard joins, no foreign keys. The application fetches ids from a mapping table, then batch-fetches objects, with memcached in front. Pins are preferentially placed on the same shard as their board, which makes the save path local.",
      "",
      "## Saving a pin",
      "",
      "Synchronous, on the board's shard, in one transaction: insert the pin row and the board→pin mapping — and bump the board's pin-count column (a counter in the same transaction, never a COUNT(*)). Everything else is asynchronous through a job queue with retries: the user→pins mapping, follower fan-out into feeds and notifications, the search index. The queue's contract — tolerates delay and failure — is exactly what those consumers need: 30 seconds late is invisible, lost is not.",
      "",
      "## Deep dive: moves and hot boards",
      "",
      "Moving a pin between boards can cross shards. Do it as an insert of the new mapping on the destination shard plus a tombstone on the source, reconciled by a background job; readers tolerate a brief double-appearance. Boards with millions of pins are never loaded whole — scan by sequence range with pagination — and their follower fan-out goes through the pull path (the feed reads them at request time) rather than write fan-out.",
      "",
      "## Why this store",
      "",
      "In 2011 the answer was MySQL over the NoSQL of the day for maturity, row-level transactions, and ordered range scans — with sharding done in the application because automatic sharding didn't exist at the quality needed. The same reasoning today points at TiDB when you want those properties with automatic sharding and secondary indexes, or keeps sharded MySQL where operational familiarity wins. The access patterns — point lookup by id, ordered range scan per mapping, small local transactions — are the justification; name them before naming the store.",
      "",
      "## Probes to expect",
      "",
      "- *Why not a graph database?* The queries are one-hop range scans and point lookups; mapping tables answer both with an index. Graph DBs earn complexity on multi-hop traversals this product doesn't run.",
      "- *A shard is hot?* Placement by board spreads users' content; a single viral board's reads are cache-absorbed (immutable-ish rows cache well), and its fan-out is already on the pull path.",
      "- *Resharding?* The id encodes a logical shard, and many logical shards map to few physical hosts — growth is moving logical shards between hosts, not rewriting ids.",
    ].join("\n"),
  },
];
