import type { Problem } from "./types";

// Apple system-design prompts reported for Software Engineer loops (PracHub's
// Apple list, 2025–2026), part C: the election voting API discussion, an
// accuracy-first click aggregator, and a file sync service. Prompts are
// restated in our own words.

export const appleDesignProblemsC: Problem[] = [
  {
    slug: "design-election-voting-apis",
    title: "Design the APIs for an Election Voting System",
    category: "system-design",
    difficulty: "medium",
    companies: ["apple"],
    summary:
      "One final ballot per voter, results sealed until close — contracts, the one-transaction rule, and a recount path.",
    prompt: [
      "Design the APIs and the core data model for a voting system. Start by saying which kind of vote you are designing for — identified or anonymous, single or multiple choice, final or changeable, results visible during voting or only afterwards — then commit to a baseline.",
      "",
      "Baseline: voters are authenticated; each voter may cast **one final, single-choice ballot** per election; an election has a configured opening and closing time; results become public only after it closes. Be ready to say how the contracts change when each assumption changes.",
      "",
      "Work through three parts. **Elections:** the resources and endpoints to create an election, add options, configure eligibility and timing, publish it and read its state — including its lifecycle and who may do what. **Casting a ballot:** the endpoint, its request and response, its error model, and what happens with a retry after a timeout, two simultaneous requests from one voter, and a request that races the closing time. **Results and audit:** when results are visible, how counts are produced, and what operators can inspect without exposing how individuals voted.",
      "",
      "The coding version of this question — a service class with idempotent votes and an audit log — is [Voting System API](/problems/voting-service-api).",
      "",
      "*Reported as: design the APIs and core data model for a voting system (PracHub, Apple Software Engineer technical screen, May 2026; also the second half of a reported Apple Senior SWE phone screen).*",
    ].join("\n"),
    hints: [
      "Freeze the rules when the election is published. A ballot has to be judged against the option set and eligibility policy the voter actually saw, so either make those immutable once open or record the rules version on every ballot.",
      "Acceptance is one transaction: the is-it-open check, the eligibility decision and the one-ballot uniqueness constraint must commit or fail together, using the database's clock rather than each app server's.",
      "Fast counters are for reads. Keep immutable ballots as the authoritative record so a count can always be recomputed and a mismatch detected and repaired.",
    ],
    rubric: [
      "- **Clarifies the vote type, then commits** — names the axes (identified or anonymous, single or multi choice, final or changeable, live or sealed results), states a baseline, and later explains how contracts change when an assumption flips.",
      "- **Election lifecycle and authorisation** — stable identifiers, draft → open → closed (and cancelled) transitions, administrator versus voter permissions, and rules that are immutable once open or explicitly versioned.",
      "- **Ballot contract** — voter identity derived from authentication rather than the request body; validation of state, eligibility and option; concrete, meaningful status codes for each failure.",
      "- **One accepted ballot under retries and concurrency** — a uniqueness constraint or transactional rule, stable idempotency for an ambiguous timeout that cannot be used to change the choice, and a deterministic outcome at the closing boundary.",
      "- **Results and recountability** — visibility tied to election state, counters or derived tallies backed by immutable ballots, and a reconciliation path when they disagree.",
      "- **Audit and privacy boundaries** — audit events for election changes and acceptance decisions, separation of public results, administrative audit data and protected voter information, plus rate limits, pagination and monitoring.",
    ].join("\n"),
    solution: [
      "## Clarify, then commit",
      "",
      "The four axes change the design more than any scale number: identified versus anonymous decides whether a ballot may reference a voter; final versus changeable decides between insert-once and replace; sealed versus live results decides whether a read model may exist before close. Baseline as given: authenticated voters, one final single-choice ballot, open and close times, results sealed until close.",
      "",
      "## Part 1 — elections, options, eligibility",
      "",
      "```",
      "POST /elections                       -> 201 { election_id, state: draft }            admin",
      "POST /elections/{id}/options          -> 201 { option_id }                            admin, draft only",
      "PUT  /elections/{id}/eligibility      { rule | voter list reference }                 admin, draft only",
      "PUT  /elections/{id}/schedule         { opens_at, closes_at }                         admin, draft only",
      "POST /elections/{id}:publish          -> 200 { state: scheduled|open, rules_version } admin",
      "POST /elections/{id}:cancel           -> 200 { state: cancelled }                     admin",
      "GET  /elections/{id}                  -> state, options, schedule (no tallies)        voter or admin",
      "```",
      "",
      "States: `draft → open → closed`, with `cancelled` reachable from draft or open. Publishing validates the election (at least two options, a closing time after the opening time, an eligibility policy) and **freezes** options, eligibility and schedule under a `rules_version`. If the business insists on mid-election changes, they create a new rules version, every ballot records the version it was cast under, and the change is an audit event — but the default answer is: cancel and re-run. Identifiers are opaque and stable; administrators and voters are distinct roles checked on every call.",
      "",
      "## Part 2 — casting one ballot safely",
      "",
      "```",
      "PUT /elections/{id}/ballot        Authorization: <voter token>   Idempotency-Key: <uuid>",
      "    { option_id }",
      "201 { receipt_id, accepted_at }              first acceptance",
      "200 { receipt_id, accepted_at }              replay of the same request",
      "403 not eligible      404 unknown election      409 already voted | not open | closed",
      "422 unknown option    429 rate limited",
      "```",
      "",
      "The voter comes from the token, never from the body — a body field would let anyone vote as anyone. The resource is singular (`/ballot`) because a voter has at most one.",
      "",
      "Acceptance is one database transaction: read the election row with a shared lock and check `state = open` and `now() < closes_at` using the **database clock**; evaluate eligibility against the frozen rules; insert into `ballots` with a unique key on `(election_id, voter_id)`. Two simultaneous requests from one voter race on that unique key — one commits with 201, the other gets 409. Closing takes an exclusive lock on the same election row and flips the state, so a ballot racing the deadline is accepted exactly when its transaction commits before the close transaction does. No app-server clock is involved, which is what makes the boundary deterministic.",
      "",
      "The ambiguous timeout: the client retries with the same `Idempotency-Key`; the server finds the stored outcome and returns the original receipt with 200. Because the ballot is final, a retry carrying the same option can return the receipt even without the key, while a different option is a 409 — idempotency must never be a way to change a vote.",
      "",
      "## Part 3 — results and auditability",
      "",
      "```",
      "GET /elections/{id}/results     409 until closed;  200 { totals[], turnout, tabulated_at, digest } afterwards",
      "GET /elections/{id}/audit       admin only, paginated: lifecycle changes and acceptance decisions",
      "```",
      "",
      "Immutable ballots are the authoritative record. Counters per option may be incremented in the acceptance transaction for cheap operator dashboards, but the published result comes from a **recount** over ballots at close; a mismatch between counter and recount raises an alert and the recount wins. Publishing stores a snapshot with a digest so the result cannot drift afterwards.",
      "",
      "Audit events are append-only: who created, published or cancelled, what changed, and every acceptance or rejection with its reason — but not the chosen option. Three access tiers follow: public results; administrative audit without individual choices; and the voter-to-option link, which is protected data with the narrowest access and its own read audit. Add rate limits on the ballot endpoint, pagination on listings, and monitoring of acceptance latency near the deadline, 409 rates, and counter-versus-ballot drift.",
      "",
      "## When the assumptions change",
      "",
      "- **Anonymous ballots:** split the write in two — an eligibility ledger records *that* a voter voted; the ballot box stores the choice with no voter reference, linked only by a blind or one-time token. Uniqueness moves to the ledger; audit can prove one-person-one-ballot but not who chose what, and a ballot can no longer be looked up or replaced by its voter.",
      "- **Changeable until close:** `PUT` replaces; keep prior versions for audit, adjust counters by delta, and count only the latest version at close.",
      "- **Ranked choice:** the ballot is an ordered list; validation rejects duplicates and unknown options; per-option counters stop being meaningful and tabulation becomes rounds computed from ballots at close.",
      "- **Live results:** a read model updated per acceptance is now a product feature; say what staleness is acceptable and how it influences voters.",
      "",
      "## Probes to expect",
      "",
      "- *Why PUT rather than POST?* The resource is the voter's single ballot; PUT is idempotent by definition and matches the uniqueness rule.",
      "- *Scale?* An election is a hot row. Shard ballots by election and voter, keep the state check cheap, and batch counter updates — correctness rests on the unique key, not the counter.",
    ].join("\n"),
  },
  {
    slug: "design-ad-click-aggregator",
    title: "Design an Accurate Ad Click Aggregator",
    category: "system-design",
    difficulty: "medium",
    companies: ["apple"],
    summary:
      "Dedup by impression, event-time windows with watermarks, idempotent sinks — and a batch recount that owns the truth.",
    prompt: [
      "Design the system that counts ad clicks. Advertisers want per-ad click counts by minute on a dashboard within about a minute, and the same counts drive billing, so **accuracy** is the primary requirement: a click must be counted once — not zero times, not twice.",
      "",
      "Assume 10k clicks per second on average with 10× peaks, tens of millions of ads, and clients that retry, double-click, go offline and send events late or out of order. Queries are: clicks for ad X between two times at minute granularity, and the top ads in a window.",
      "",
      "Cover: how a click is captured so it can be verified and deduplicated; ingestion; the aggregation model (event time, windows, lateness); how you get effectively-exactly-once counts through retries and restarts; hot ads; the store that serves queries; how streaming numbers are reconciled with a batch recount; and what you monitor to prove the numbers are right.",
      "",
      "*Reported as: an accurate click aggregator with deduplication and correctness at scale (PracHub, Apple Software Engineer technical screen, Dec 2025), and as half of a two-system onsite prompt (Jan 2026).*",
    ].join("\n"),
    hints: [
      "Give every click an identity you can trust: serve the ad with a signed impression token and route the click through your redirect endpoint, so a click is verifiable and a duplicate is recognisable by its impression id.",
      "Exactly-once is a property of the whole pipeline: idempotent producers, event-time windows with a watermark, checkpointed state, and a sink that upserts by (ad, minute) instead of incrementing.",
      "Keep the raw events. A batch job that recomputes from immutable raw data and overwrites the streaming aggregates is what makes billing defensible — and what lets you fix a bug after the fact.",
    ],
    rubric: [
      "- **Capture and identity** — clicks pass through a redirect endpoint carrying a signed impression token; the event id derives from it, making clicks verifiable and duplicates detectable; the redirect stays fast and never loses the click.",
      "- **Ingestion** — a durable, partitioned log with idempotent producers; partitioning by ad id with a plan for hot ads (salting and two-stage aggregation).",
      "- **Event-time aggregation** — tumbling windows on event time, watermarks and allowed lateness, a defined policy for events later than the watermark, and dedup state with a bounded time-to-live.",
      "- **Effectively exactly-once** — explains where duplicates arise (client retries, producer retries, consumer restarts) and closes each: dedup keys, checkpointing, and an idempotent or transactional sink keyed by (ad, window).",
      "- **Reconciliation** — immutable raw events archived; a batch recount with full dedup and fraud rules overwrites streaming results; billing reads reconciled data; discrepancy is measured and alerted on.",
      "- **Serving and observability** — a time-partitioned analytical store with rollups, query patterns that match it, and metrics such as end-to-end lag, dedup rate, late-event rate and stream-versus-batch delta.",
    ].join("\n"),
    solution: [
      "## Requirements and numbers",
      "",
      "10k clicks/s average, 100k/s at peak; an event is ~200 bytes, so ingestion bandwidth is trivial — the difficulty is correctness, not volume. Dashboards may be a minute behind and slightly provisional; billing must be exact and can wait hours. Those two contracts lead directly to a streaming path for freshness and a batch path for truth.",
      "",
      "## Capturing a click you can trust",
      "",
      "When an ad is served, the ad server embeds a signed impression token: `{impression_id, ad_id, placement, served_at}` plus an HMAC. The click goes to `GET /click?t=<token>`, which verifies the signature, appends a click event to a durable log, and answers with a 302 to the advertiser. The signature means the event cannot be forged or replayed for a different ad; the `impression_id` is the dedup key — one billable click per impression. The redirect handler acknowledges only after a durable append; if the log is unreachable it spools to local disk rather than dropping the click or delaying the user.",
      "",
      "## Ingestion",
      "",
      "Events land in a partitioned log (Kafka), keyed by `ad_id` so an ad's events stay ordered within a partition. Producers are idempotent, so a producer retry does not write twice. Raw events are also written, unmodified, to object storage in hourly partitions — the immutable archive everything else can be rebuilt from.",
      "",
      "## Streaming aggregation",
      "",
      "A stream processor (Flink or similar) assigns each event to a one-minute tumbling window by **event time**. A watermark trails the newest event time by a few minutes; windows emit a provisional count as they fill, and a final count when the watermark passes them. Events later than the allowed lateness are not dropped silently: they are routed to a late-events topic and picked up by the batch recount, and the dashboard marks very recent minutes as provisional.",
      "",
      "Dedup: keyed state holds recently seen `impression_id`s with a time-to-live a little longer than the lateness bound; a repeat within that period is discarded. A bloom filter in front of the exact store keeps the common case — not a duplicate — cheap.",
      "",
      "## Effectively exactly-once",
      "",
      "Duplicates come from three places. Client retries and double clicks are removed by the impression-id dedup. Producer retries are removed by idempotent producers. Consumer restarts replay input from the last checkpoint, so the sink must tolerate replays: state and offsets are checkpointed together, and the sink **upserts** `(ad_id, minute) → count` with the count computed from checkpointed state rather than issuing increments. Replaying a window rewrites the same value. Where the sink supports it, a two-phase commit tied to the checkpoint gives the same result.",
      "",
      "## Hot ads",
      "",
      "A viral ad can be several percent of traffic on one key. Aggregate in two stages: partition by `(ad_id, salt)` and produce partial counts per second, then merge partials keyed by `ad_id`. The hot key now costs a handful of messages per second in the second stage.",
      "",
      "## Serving",
      "",
      "Aggregates live in a time-partitioned analytical store (ClickHouse, Druid or Pinot): primary key `(ad_id, minute)`, with rollups to hour and day so long ranges stay cheap. Top-N in a window is a partition scan with a heap, or a pre-aggregated per-window ranking for the dashboard's defaults.",
      "",
      "## Reconciliation — the part that makes it accurate",
      "",
      "Every hour, and again daily, a batch job recomputes counts from the raw archive with global dedup, the late events, and the current fraud rules, and **overwrites** the streaming aggregates for that period — replace, never add. Billing reads only reconciled periods. The job also reports the difference between streaming and batch per ad; a delta above a small threshold pages someone, because it means a bug in one of the two paths. Because raw events are kept, a wrong rule can be fixed and the period recomputed.",
      "",
      "## What to monitor",
      "",
      "End-to-end lag from click to queryable, dedup rate, late-event rate and lateness distribution, checkpoint duration, partition skew, spool depth at the redirect tier, and the stream-versus-batch delta — the last one is the accuracy metric.",
      "",
      "## Probes to expect",
      "",
      "- *Why event time?* Processing-time windows move clicks between minutes whenever the pipeline lags, so the same data gives different answers on replay.",
      "- *Click fraud?* Filtering is another consumer of the raw log that emits verdicts; the batch recount applies them. Keep it out of the redirect path.",
      "- *Can the dashboard and the invoice disagree?* Briefly, and visibly: provisional minutes are labelled, and reconciled values replace them.",
    ].join("\n"),
  },
  {
    slug: "design-file-sync-service",
    title: "Design a File Sync Service",
    category: "system-design",
    difficulty: "medium",
    companies: ["apple"],
    summary:
      "Content-addressed blocks, a per-namespace journal, and conflicted copies instead of silent loss.",
    prompt: [
      "Design a Dropbox-style service: a folder that stays in sync across a user's devices, with version history and the ability to share folders and links with other people.",
      "",
      "Assume hundreds of millions of users, files from a few bytes to tens of gigabytes, devices that edit offline, and networks where re-uploading a whole large file for a one-line change is unacceptable.",
      "",
      "Cover: how files are broken up, stored and deduplicated; the metadata model and how devices learn what changed; the upload and download flows and the moment a new version exists; conflicts between devices; version history and garbage collection; sharing and permissions; security; and how it scales.",
      "",
      "*Reported as: a cloud file storage and synchronization service with versioning and secure sharing, as half of a two-system onsite prompt (PracHub, Apple Software Engineer onsite, Jan 2026).*",
    ].join("\n"),
    hints: [
      "Split every file into blocks of a few megabytes and address each block by its hash. A file version is just an ordered list of block hashes, so an edit uploads only the blocks that changed.",
      "Metadata is a journal per namespace: every commit gets the next sequence number, devices keep a cursor, and a long-poll or push tells them to fetch. A shared folder is its own namespace mounted into each member's tree.",
      "A commit names the revision it was based on. If that is no longer the latest, do not overwrite — keep both as a conflicted copy.",
    ],
    rubric: [
      "- **Block model and dedup** — files chunked into content-addressed blocks, a manifest per version, upload of missing blocks only, and an explicit stance on cross-user dedup and what it leaks.",
      "- **Metadata journal and change notification** — per-namespace ordered journal, device cursors, long-poll or push as a wake-up, paginated delta fetch; metadata sharded so one namespace has a single ordered writer.",
      "- **Commit protocol** — blocks first, then an atomic metadata commit that validates the blocks exist; the commit carries the parent revision; crashes leave only orphaned blocks.",
      "- **Conflict handling** — optimistic concurrency on parent revision with conflicted copies rather than silent overwrite; handles delete-versus-edit and offline edits.",
      "- **History, sharing and security** — retained versions and restore, block garbage collection by reference, shared-folder namespaces with roles, capability links with expiry, authorised block fetches, encryption in transit and at rest.",
      "- **Efficiency and scale** — delta sync within changed blocks, compression, batching of small files, notification fan-out for large shared folders, and metrics such as sync latency and dedup ratio.",
    ].join("\n"),
    solution: [
      "## Two planes",
      "",
      "A **block store** holds immutable, content-addressed blocks on object storage. A **metadata service** holds the file tree, versions, sharing and the change journal in a sharded, strongly consistent database. Clients talk to both; bytes never pass through the metadata tier.",
      "",
      "## Blocks",
      "",
      "The client splits a file into blocks of about 4 MB and hashes each with SHA-256. A file version is a manifest — an ordered list of block hashes plus size and modification time. Before uploading, the client asks which hashes the server is missing and sends only those, so a small edit to a large file uploads one or two blocks and an unchanged re-upload sends nothing. Fixed-size blocks handle in-place edits; content-defined chunking with a rolling hash also survives insertions that shift every later byte, at the cost of client CPU. Inside a changed block, an rsync-style delta trims further.",
      "",
      "Dedup across versions and within an account is free. Dedup **across users** saves more storage but lets someone probe whether a file already exists on the service; if you allow it, never skip the upload on the strength of a client-supplied hash alone.",
      "",
      "## Metadata and the journal",
      "",
      "```",
      "namespace   ns_id -> owner | shared-folder, members, roles",
      "journal     (ns_id, seq) -> { file_id, path, rev, manifest, size, mtime, deleted }     append-only",
      "file_head   (ns_id, file_id) -> latest rev                                             for conflict checks",
      "block       hash -> location, size, ref_count",
      "cursor      (device_id, ns_id) -> last applied seq",
      "```",
      "",
      "Every change to a namespace is a journal entry with the namespace's next sequence number. Shard by `ns_id` so each namespace has one ordered writer and a commit is a single-shard transaction. A user's root is one namespace; every **shared folder is its own namespace** mounted into each member's tree — so a change in a shared folder is one journal append, not one per member.",
      "",
      "## Upload and commit",
      "",
      "1. Chunk and hash; `POST /blocks:missing` with the hash list.",
      "2. Upload missing blocks straight to the block store (idempotent by hash, resumable).",
      "3. `POST /files:commit { ns_id, file_id, parent_rev, manifest }`.",
      "4. The server verifies every block exists, checks `parent_rev`, appends to the journal and updates `file_head` in one transaction. **That commit is the moment the version exists.**",
      "",
      "A crash before step 4 leaves orphaned blocks for garbage collection and nothing visible; a retry of step 4 with the same manifest and parent is idempotent.",
      "",
      "## Learning about changes",
      "",
      "Devices hold a long-poll (or receive a push) per account; the signal only says a namespace advanced. The device then fetches journal entries after its cursor, downloads blocks it lacks, assembles the file in a temporary location, verifies it, and renames it into place atomically so applications never see a half-written file. The cursor advances only after the change is applied.",
      "",
      "## Conflicts",
      "",
      "A commit whose `parent_rev` is not the current head means another device got there first. The service never overwrites: it accepts the new content as a **conflicted copy** alongside the winner and both devices see both files. Offline edits follow the same rule when they eventually commit. Delete versus edit resolves to keeping the edited file. Losing a user's bytes silently is the one unacceptable outcome.",
      "",
      "## History and garbage collection",
      "",
      "Old revisions remain in the journal for the retention period; restoring is a new commit that points at an old manifest, which costs no block uploads. Blocks are reference-counted by manifests; a mark-and-sweep pass deletes blocks unreferenced beyond retention, with a grace period to avoid racing in-flight commits.",
      "",
      "## Sharing and security",
      "",
      "Members have roles on the shared namespace (owner, editor, viewer), checked by the metadata service on every commit and listing. Links are capability tokens with optional expiry and password, revocable. Block downloads go through short-lived signed URLs issued only for manifests the caller may read — knowing a hash is not authorisation. Transport is TLS; blocks are encrypted at rest with envelope keys; device unlink revokes tokens and can request a remote wipe; sharing and access are audit-logged.",
      "",
      "## Scale and measurement",
      "",
      "Metadata shards by namespace; very large shared folders are the hot spot, handled by batching notifications and rate-limiting fan-out. Many small files are batched into one commit request. Track sync latency from commit to remote apply, conflicted-copy rate, dedup ratio, bytes uploaded versus bytes changed, notification lag, and orphaned block volume.",
      "",
      "## Probes to expect",
      "",
      "- *Why not last-writer-wins?* It silently destroys work; a conflicted copy is ugly but safe.",
      "- *Renames and moves?* Stable `file_id`s make a move a metadata-only journal entry; no blocks move.",
      "- *A 50 GB file over a flaky link?* Blocks are independent and idempotent, so the upload resumes block by block and commits once at the end.",
    ].join("\n"),
  },
];
