import type { Problem } from "./types";

// Apple front-end system-design prompts (the JavaScript interview guide,
// 2026): the three front-end system design questions GreatFrontEnd lists
// under Apple, with no date or role: autocomplete, music streaming and photo
// sharing. The guide names them without detail, so the prompts are framed
// here as client-architecture questions, in our own words.

const REPORTED = "*Listed under Apple by GreatFrontEnd as a front-end system design question, with no date or role.*";

export const appleDesignProblemsG: Problem[] = [
  {
    slug: "design-autocomplete-frontend",
    title: "Design an Autocomplete Component (Front End)",
    category: "system-design",
    difficulty: "medium",
    companies: ["apple"],
    summary:
      "A reusable typeahead: the component API, a data layer that debounces, cancels and caches, and the combobox pattern done properly.",
    prompt: [
      "Design a reusable autocomplete component: the search box that suggests results as you type, as on a large site's global search. Several product teams will use it, with different result types (plain text, rich rows with images, grouped sections), so it must be configurable. Focus on the client: its architecture, its API, how it talks to the server, and how it behaves on slow networks, on phones and with assistive technology.",
      "",
      "Cover the requirements and scope, the component's architecture, its props and the server API, the data layer (debouncing, cancellation, caching, race conditions), rendering performance, and accessibility and internationalization.",
      "",
      REPORTED,
      "",
      "To build the component itself, see [Typeahead with Keyboard Navigation](/problems/typeahead-keyboard-nav).",
    ].join("\n"),
    hints: [
      "Split the component into an input, a results list, and a controller that owns debouncing, request cancellation and the cache. The UI pieces stay dumb, and the controller is what teams configure.",
      "A cache keyed by query, with a size cap and a time-to-live, makes backspacing instant. Decide whether a prefix's results can answer a longer query locally.",
      "The accessible pattern is a combobox: an input with `role=\"combobox\"`, `aria-expanded` and `aria-activedescendant`, pointing at a `listbox` of `option`s. Focus never leaves the input.",
    ],
    rubric: [
      "- **Requirements and scope**: functional (suggestions as you type, keyboard and pointer selection, custom rendering, initial results on focus) and non-functional (perceived latency, mobile, accessibility, reuse across teams) are stated before designing.",
      "- **Architecture**: a clear split between the input, the results view and a controller or data layer, with data flow in both directions and the extension points teams need.",
      "- **Component and server API**: props such as `fetchSuggestions`, `minQueryLength`, `debounceMs`, `renderItem`, `onSelect` and `initialResults`, and a server endpoint with query, limit and a response shape that carries result types.",
      "- **Network and state**: debouncing, cancelling stale requests (`AbortController` or sequence numbers) so an old response never overwrites a new one, a bounded per-query cache with expiry, and error, empty and loading states.",
      "- **Performance and UX**: highlighted matches, no layout shift as results arrive, virtualization or a hard limit for long lists, and fast paths such as serving a cached prefix.",
      "- **Accessibility and i18n**: the combobox pattern with a listbox and options, `aria-activedescendant`, announced result counts, full keyboard support, IME composition handled (no query mid-composition), and right-to-left layouts.",
    ].join("\n"),
    solution: [
      "## Requirements",
      "",
      "Suggestions appear as the user types, from a minimum length, and show something useful on focus (recent searches). Arrow keys, Enter, Escape and the pointer all work. Teams supply how to fetch and how to render a result. Non-functional: suggestions should feel instant (show cached results immediately, and fresh ones within a few hundred milliseconds), the component must work on phones and with screen readers, and it must be safe to drop into any page.",
      "",
      "## Architecture",
      "",
      "```",
      "Autocomplete (public component)",
      " ├─ Input           controlled text field, the combobox",
      " ├─ ResultsList     listbox of options, renders renderItem(result)",
      " └─ Controller      debounce -> cache lookup -> fetch (abortable) -> state",
      "        └─ Cache     Map<query, { results, expiresAt }>, LRU-capped",
      "```",
      "",
      "The controller is a small state machine: idle, loading, showing results, empty, or error. The input and list only render what it says. Teams configure the controller through props, never by reaching into it.",
      "",
      "## Component API and server API",
      "",
      "```",
      "<Autocomplete",
      "  fetchSuggestions={(query, { signal }) => Promise<Result[]>}",
      "  minQueryLength={2}  debounceMs={150}  maxResults={8}",
      "  initialResults={recentSearches}",
      "  renderItem={(result, { highlighted }) => ReactNode}",
      "  onSelect={(result) => ...}",
      "/>",
      "",
      "GET /suggest?q=ipho&limit=8&locale=en-US",
      "-> { query: \"ipho\", results: [{ id, type: \"product\" | \"article\" | \"query\", title, subtitle?, imageUrl?, url }] }",
      "```",
      "",
      "Echoing the query in the response lets the client drop answers for a query it no longer shows.",
      "",
      "## Data layer",
      "",
      "- **Debounce** keystrokes (about 150 ms) rather than throttle: the user wants results for what they stopped typing.",
      "- **Cancel** the in-flight request when the query changes, with an `AbortController`. Also guard with the echoed query or a sequence number, because a response can still arrive after the abort.",
      "- **Cache** results by normalized query (trimmed, lowercased) with a time-to-live and an LRU cap of around 100 entries. Backspacing then costs nothing. For small, stable datasets, filter a cached prefix's results locally instead of calling the server.",
      "- **Errors** keep the last good results visible with a quiet retry. The input never blocks.",
      "",
      "## Rendering and UX",
      "",
      "Highlight the matched part of each title. Reserve the list's height, or render it as an overlay, so the page doesn't shift. Cap the results (8 to 10) rather than virtualizing; if a team needs long lists, virtualize. Show loading only after a short delay, so fast responses don't flicker.",
      "",
      "## Accessibility and internationalization",
      "",
      "The input is a `combobox` with `aria-expanded`, `aria-controls` pointing at a `listbox`, and `aria-activedescendant` naming the highlighted `option`. Focus stays in the input the whole time. A polite live region announces \"5 results\". Escape closes the list, and Enter selects. For CJK input, ignore `input` events between `compositionstart` and `compositionend`. Mirror the layout for right-to-left languages.",
      "",
      "## Worth saying out loud",
      "",
      "- The race condition is the classic bug: a slow response for \"ip\" arriving after the one for \"iphone\". Cancellation plus a query check fixes it.",
      "- Measure time to first suggestion, cache hit rate and abandonment, not only request latency.",
    ].join("\n"),
  },
  {
    slug: "design-music-streaming-frontend",
    title: "Design a Music Streaming Web App (Front End)",
    category: "system-design",
    difficulty: "hard",
    companies: ["apple"],
    summary:
      "A player that keeps playing across navigation, a queue model, streaming and preloading audio, and state shared across tabs and devices.",
    prompt: [
      "Design the web client of a music streaming service. Users browse and search a large catalog, build playlists, and play music. **Playback must continue while they navigate** the app, and the same account may be open in several tabs or on other devices. Focus on the client.",
      "",
      "Cover the core flows and non-functional requirements, the application architecture (how the player survives navigation), playback (streaming, buffering, preloading the next track, gapless playback, protected content, lock-screen and media-key controls), the client data model (catalog entities, the queue, playlists), syncing state across tabs and devices, performance, and accessibility.",
      "",
      REPORTED,
    ].join("\n"),
    hints: [
      "Mount the player in the app shell, outside the routed pages, so a route change never unmounts it. Pages talk to it through a small store or service, never by owning the audio element.",
      "Model the queue explicitly: an ordered list of track ids, a current index, shuffle as a separate permutation, and a history for Back. Most player bugs are queue bugs.",
      "The Media Session API gives lock-screen and media-key controls. Media Source Extensions give adaptive streaming, and Encrypted Media Extensions give protected content.",
    ],
    rubric: [
      "- **Requirements and scope**: browse, search, library and playlists, playback with a queue, and cross-device continuity, plus non-functional targets such as time to first sound, uninterrupted playback during navigation, and poor-network behavior.",
      "- **Architecture**: a single-page app with a persistent player mounted outside the routes, client routing, and a data layer that separates catalog data from player state.",
      "- **Playback**: streaming via `<audio>` or Media Source Extensions with adaptive bitrate, buffering and preloading the next track, gapless or crossfade playback via Web Audio when needed, protected content through Encrypted Media Extensions, and Media Session controls.",
      "- **State and data**: normalized catalog entities, an explicit queue model with shuffle and repeat, optimistic updates for likes and playlist edits with rollback, and playback position saved for resuming.",
      "- **Sync and resilience**: one active player across tabs (BroadcastChannel or a Web Lock), device handoff through the server, retry and quality fallback on bad networks, and clear error states.",
      "- **Performance and accessibility**: code-splitting by route, sized artwork, virtualized long lists, prefetching likely next pages, full keyboard control with shortcuts, focus management on navigation, and screen-reader labels on player controls.",
    ].join("\n"),
    solution: [
      "## Requirements",
      "",
      "Core flows: browse and search the catalog, open albums, artists and playlists, add to the library, edit playlists, and play with a queue (next, previous, shuffle, repeat, seek). Non-functional: first sound within about a second of pressing play, **no interruption when navigating**, graceful degradation on slow networks, and one active player per account unless the user moves playback.",
      "",
      "## Architecture",
      "",
      "```",
      "AppShell",
      " ├─ Router outlet     Home | Search | Album | Artist | Playlist | Library   (code-split)",
      " ├─ PlayerBar         persistent: never unmounted by navigation",
      " └─ Stores",
      "      ├─ catalog     normalized entities: tracks, albums, artists, playlists",
      "      ├─ library     the user's saved items and playlists (optimistic)",
      "      └─ player      queue, current index, position, state, volume",
      "PlayerService        owns the audio element(s), MediaSession, preloading",
      "```",
      "",
      "Pages dispatch intents (\"play this album from track 3\") to the player store. Only the PlayerService touches the audio element, so a route change can never stop the music.",
      "",
      "## Playback",
      "",
      "- **Streaming**: for a single bitrate, `<audio src>` with HTTP range requests is enough. For adaptive quality, use Media Source Extensions: fetch segments, append them to a `SourceBuffer`, and step the bitrate down when the buffer drains. Protected content goes through Encrypted Media Extensions with the licence server.",
      "- **Preloading**: when the current track is nearly done, start fetching the next one in the queue. For gapless albums, schedule the next buffer on a Web Audio timeline, or use two alternating audio elements, instead of waiting for `ended`.",
      "- **Controls everywhere**: the Media Session API supplies metadata, artwork and action handlers (play, pause, next, previous, seek), so lock screens, media keys and headphones work.",
      "- **Resume**: save the position every few seconds and on `pagehide`, locally and to the server, so a reload continues where it stopped.",
      "",
      "## The queue",
      "",
      "```",
      "queue      trackIds[]          the order the user built or the context gave",
      "order      number[]            a permutation of queue indices; identity unless shuffled",
      "cursor     index into order",
      "history    for Back when shuffled",
      "context    { type: \"album\" | \"playlist\" | ..., id }   for \"playing from\" and refills",
      "```",
      "",
      "Keeping shuffle as a separate permutation means turning shuffle off restores the original order, and \"play next\" inserts right after the cursor.",
      "",
      "## Sync across tabs and devices",
      "",
      "Across tabs, a `BroadcastChannel` (or a Web Lock) elects one tab as the active player; the others show the state and send commands to it. Across devices, the server holds the playback session. A client announces \"I'm playing\" over a push channel, and the others pause and offer to take over. Library edits apply optimistically and reconcile when the server confirms.",
      "",
      "## Performance and accessibility",
      "",
      "Split code by route and load the player core early. Request artwork at the displayed size with `srcset`. Virtualize long playlists and libraries. Prefetch an album's data on hover or focus. Every control is a real button with a label, the seek bar is a slider with `aria-valuetext` such as \"1:32 of 3:45\", keyboard shortcuts cover the essentials, and focus moves to the main heading on navigation.",
      "",
      "## Worth saying out loud",
      "",
      "- Autoplay policies block sound until the user interacts. The first play must come from a click.",
      "- Measure time to first sound, rebuffering ratio and skip latency.",
    ].join("\n"),
  },
  {
    slug: "design-photo-sharing-frontend",
    title: "Design a Photo Sharing App (Front End)",
    category: "system-design",
    difficulty: "medium",
    companies: ["apple"],
    summary:
      "An infinite feed of images without layout shift, optimistic likes, and an upload flow that resizes, strips location and survives a bad connection.",
    prompt: [
      "Design the web client of a photo sharing app: an infinite feed of posts (photo, caption, likes, comments), a post detail view, a profile grid, and uploading a new photo with a caption. Focus on the client.",
      "",
      "Cover the requirements, the component architecture, the data model and API for a paginated feed, feed rendering (infinite scroll, image loading, no layout shift, memory on long sessions), interactions (likes and comments), the upload flow, and performance, accessibility and privacy.",
      "",
      REPORTED,
    ].join("\n"),
    hints: [
      "Page the feed with a cursor, not offsets: new posts arriving at the top shouldn't make the next page repeat or skip items.",
      "Know every image's aspect ratio before it loads, from the API. Reserving the box is what prevents layout shift; `srcset` and lazy loading handle the bytes.",
      "Treat upload as a pipeline: pick, preview, resize and strip metadata on the client, upload with progress and retry, then create the post.",
    ],
    rubric: [
      "- **Requirements and scope**: feed, post detail, profile grid and upload, plus non-functional goals (fast first paint, smooth scrolling on long sessions, mobile networks, accessibility, privacy).",
      "- **Architecture and data model**: feed, post and upload components over a normalized store of posts and users, so a like updates everywhere a post appears.",
      "- **Feed API and rendering**: cursor pagination, prefetching the next page before the end, `IntersectionObserver` rather than scroll listeners, and virtualization or recycling for memory on long sessions.",
      "- **Images**: aspect ratios from the API to prevent layout shift, `srcset` and `sizes`, lazy loading below the fold, placeholders, and modern formats.",
      "- **Interactions and upload**: optimistic likes with rollback, paginated comments, and an upload pipeline with client-side resize, EXIF orientation and location stripping, progress, and chunked or resumable uploads direct to storage with retry.",
      "- **Performance, accessibility and privacy**: server rendering of the first page, alt text prompted at upload, keyboard navigation through the feed, focus management in the post dialog, and location data removed unless the user adds it.",
    ].join("\n"),
    solution: [
      "## Requirements",
      "",
      "Scroll a personalized feed indefinitely, like and comment, open a post in a dialog with its own URL, view a profile's grid, and upload a photo with a caption and alt text. Non-functional: the first posts render fast on a phone, scrolling stays smooth after hundreds of posts, and uploads survive a flaky connection.",
      "",
      "## Architecture and data model",
      "",
      "```",
      "FeedPage ── PostCard (image, caption, LikeButton, CommentPreview)",
      "PostDialog (route /p/:id, opens over the feed)",
      "ProfileGrid ── GridTile",
      "Composer (pick -> edit -> caption and alt text -> upload)",
      "",
      "store: posts by id, users by id, feed pages [{ postIds, nextCursor }]",
      "```",
      "",
      "A normalized store means a like in the dialog updates the card in the feed behind it, because both read the same post record.",
      "",
      "## Feed API and rendering",
      "",
      "```",
      "GET /feed?cursor=abc&limit=12",
      "-> { posts: [{ id, author: { id, name, avatarUrl }, image: { url, width, height, blurhash, alt },",
      "                caption, likeCount, likedByMe, commentCount, createdAt }],",
      "     nextCursor: \"def\" }",
      "```",
      "",
      "Cursor pagination stays correct while new posts arrive. An `IntersectionObserver` on a sentinel a screen or two above the end fetches the next page early. For long sessions, virtualize the list, or replace far-off cards with fixed-height placeholders, so memory stays bounded.",
      "",
      "## Images",
      "",
      "Width and height come with every post, so each card reserves its box (`aspect-ratio`) before the image arrives: no layout shift. Serve several sizes and let `srcset` and `sizes` pick one. Load the first screen eagerly and the rest with `loading=\"lazy\"`, show a blurred placeholder while each image decodes, and prefer AVIF or WebP.",
      "",
      "## Interactions",
      "",
      "A like updates the store at once and sends the request. On failure it rolls back and shows a quiet error. Comments load in pages inside the dialog, and a new comment appears optimistically with a pending state.",
      "",
      "## Upload",
      "",
      "1. Pick a file, or capture one on mobile, and preview it with an object URL.",
      "2. On the client, apply EXIF orientation, **strip location metadata** unless the user chooses to add a place, and resize to the largest size the service stores.",
      "3. Ask the server for a presigned upload URL, and upload directly to storage in chunks, with progress, retry and resume.",
      "4. Create the post with the stored object's key, caption and alt text. Show it at the top of the user's feed immediately, marked as pending until the server confirms.",
      "",
      "## Performance and accessibility",
      "",
      "Render the first page on the server, and hydrate. Prefetch the next page and the likely next dialog. Prompt for alt text at upload, with a generated suggestion the user can edit. Cards are reachable by keyboard, the dialog traps focus and returns it to the card on close, and the like button reports its state with `aria-pressed`.",
      "",
      "## Worth saying out loud",
      "",
      "- Layout shift from images is the most visible front-end failure in a feed, and the fix starts in the API: return the dimensions.",
      "- Location in photo metadata is a privacy leak. Strip it by default.",
    ].join("\n"),
  },
];
