import type { Problem } from "./types";

// Snowflake system-design prompts, part C: an RPC layer, a client logging
// library, a client for an unreliable token service, a global quota system,
// a metrics system, a web crawler, and counting the nodes of a server tree.

export const snowflakeDesignProblemsC: Problem[] = [
  {
    slug: "design-rpc-layer-over-rest",
    title: "Design an RPC Layer Over Hand-Written REST Calls",
    category: "system-design",
    difficulty: "medium",
    companies: ["snowflake"],
    summary:
      "An interface definition that generates stubs and skeletons, with marshalling, discovery, deadlines, idempotent retries and versioning handled once.",
    prompt: [
      "A codebase calls its internal services through hand-written REST calls: URLs built by string concatenation, JSON assembled by hand, retries copied and pasted. Design an RPC abstraction layer to replace them.",
      "",
      "Cover the interface definition and what is generated from it, marshalling, service discovery, deadlines, retries and their relationship with idempotency, and how interfaces evolve without breaking callers.",
    ].join("\n"),
    hints: [
      "An interface definition generates client stubs and server skeletons, so the wire format, discovery and retry logic live in one place and callers write a method call.",
      "Retry only idempotent calls, and give every request an id so a server can filter duplicates of the non-idempotent ones.",
      "Versioning: additive changes to messages with defaults for new fields; a new method or a new version for anything else.",
    ],
    rubric: [
      "- **Interface definition** — a schema that generates typed client stubs and server skeletons; the generated code owns marshalling.",
      "- **Service discovery and balancing** — client-side resolution from a registry versus a proxy, with the argument for either.",
      "- **Deadlines** — propagated end to end, so a slow dependency cannot hold a caller forever.",
      "- **Retries and idempotency** — retries only for idempotent calls or with a request id for duplicate filtering; backoff and jitter.",
      "- **Versioning** — additive message evolution with defaults, explicit new versions for breaking changes.",
    ].join("\n"),
    solution: [
      "## Core",
      "",
      "Start from an interface definition: services, methods, request and response messages. From it, generate a client stub (a method per RPC that marshals, resolves a target, sends, and unmarshals) and a server skeleton (decodes, dispatches, encodes). Developers implement the skeleton and call the stub; URLs, JSON and retry loops disappear from application code.",
      "",
      "## Discovery and balancing",
      "",
      "Generated code versus runtime reflection is the first fork: generated code is faster and type-checked, reflection is more flexible for dynamic languages. Client-side load balancing resolves instances from a registry and picks one per call; a proxy centralises that logic and adds a hop. Client-side when latency matters and clients are few languages; a proxy when there are many client platforms to keep consistent.",
      "",
      "## Deadlines, retries, idempotency",
      "",
      "Every call carries a deadline that is propagated to downstream calls, so a slow leaf cannot hold the whole chain. Retries are allowed only for calls marked idempotent in the definition; everything else carries a request id, and servers keep a short-lived table of recently seen ids to drop duplicates. Backoff with jitter prevents a retry storm from a brief outage.",
      "",
      "## The trade-off to argue",
      "",
      "Generated code versus runtime reflection, and client-side versus proxy load balancing. Name both, pick for the stated environment, and say what you give up.",
      "",
      "## Versioning",
      "",
      "Messages evolve additively: new optional fields with defaults, never a removed or retyped field. Breaking changes get a new method or a new service version, and the registry serves both until callers migrate. The migration from REST happens behind the stubs, one service at a time.",
    ].join("\n"),
  },
  {
    slug: "design-client-logging-library",
    title: "Design a Logging Library for Web and Mobile Clients",
    category: "system-design",
    difficulty: "medium",
    companies: ["snowflake"],
    summary: "A non-blocking log() into a bounded buffer, flushed by size or time, persisted offline, with a stated policy for what to drop under pressure.",
    prompt: [
      "Design a logging library that runs inside web and mobile applications and ships logs to a backend. The application must never be slowed or blocked by logging, devices go offline, and call volume rises with the user base.",
      "",
      "Cover the API, buffering and flushing, behaviour when the device is offline, how the library behaves under pressure when logs arrive faster than they can be sent, and what the backend receives.",
    ].join("\n"),
    hints: [
      "log() appends to a bounded in-memory buffer and returns immediately; a background flush sends batches when the buffer reaches a size or an interval elapses.",
      "Persist the buffer to local storage when offline and retry with backoff; cap the on-disk size too.",
      "Under pressure, choose explicitly: drop oldest, drop newest, or sample by level. Blocking the app is never acceptable.",
    ],
    rubric: [
      "- **Non-blocking API** — log() does no I/O, no network and no synchronous disk write; a bounded buffer absorbs bursts.",
      "- **Batching** — flush by size or by time, compressed, with a payload the backend can ingest in bulk.",
      "- **Offline** — buffer persisted locally with a cap, retried with backoff and jitter when connectivity returns.",
      "- **Backpressure policy** — an explicit drop or sampling rule, with error-level logs protected.",
      "- **Backend contract** — idempotent ingestion keyed by (device, sequence) so retries do not duplicate.",
    ].join("\n"),
    solution: [
      "## API and buffering",
      "",
      "`log(level, message, fields)` appends a record to a ring buffer and returns. A background task flushes when the buffer holds N records or T seconds have passed, whichever first, sending one compressed batch. Each record carries a device id and a per-device sequence number, which is what makes the backend's ingestion idempotent across retries.",
      "",
      "## Offline",
      "",
      "If a flush fails, the batch is written to local storage and retried with exponential backoff and jitter when the network is back. The on-disk store has a cap too; past it, the same drop policy applies as in memory.",
      "",
      "## The trade-off to argue",
      "",
      "Batching versus backpressure as volume grows. Batching helps until the device produces logs faster than it can ever send them; then something has to give. Drop oldest keeps the most recent context; drop newest keeps the cause of a problem; sampling by level keeps every error and a fraction of the debug noise. Pick sampling by level for a product that must debug incidents, and say that blocking the application is the one option that is never on the table.",
      "",
      "## Backend",
      "",
      "A bulk ingestion endpoint that acknowledges a batch only after it is durably written, deduplicates by (device, sequence), and applies server-side sampling or quotas per application version so a buggy release cannot flood the pipeline.",
      "",
      "## Probes",
      "",
      "- *Battery and bandwidth on mobile?* Flush on Wi-Fi or when the app backgrounds; larger intervals on cellular.",
      "- *Sensitive data?* Redaction in the library before buffering, because once it is on disk it is already a leak.",
    ].join("\n"),
  },
  {
    slug: "design-token-service-client",
    title: "Design a Client for an Unreliable Token Service",
    category: "system-design",
    difficulty: "medium",
    companies: ["snowflake"],
    summary:
      "Cache tokens with expiry, refresh ahead of time with jitter, single-flight the refresh, and decide between a slightly stale token and a failed request.",
    prompt: [
      "Your service needs a short-lived token from a third-party token service on every outbound call. That service is slow at times and down at others. Design the client so your own availability does not track theirs.",
      "",
      "Cover caching, when and how a token is refreshed, what happens when many requests need a token at the same moment, how you behave while the token service is down, and the trade-off between serving a slightly stale token and failing the request.",
    ].join("\n"),
    hints: [
      "Cache the token with its expiry and refresh it ahead of expiry, with jitter so a fleet does not refresh in lockstep.",
      "Single-flight the refresh: one in-flight request serves every waiter; the rest reuse the current token meanwhile.",
      "Circuit breaker and backoff around the token service, and a policy for the window after expiry when no refresh has succeeded.",
    ],
    rubric: [
      "- **Cache with expiry** — tokens cached per credential with the issuer's expiry, refreshed proactively.",
      "- **Refresh-ahead with jitter** — refresh at a fraction of the lifetime, randomised, so a fleet spreads its load on the issuer.",
      "- **Single-flight** — concurrent requests share one refresh; no thundering herd.",
      "- **Resilience** — backoff and a circuit breaker around the issuer; the service keeps running on the cached token while the issuer is down.",
      "- **Stale-versus-fail policy** — an explicit grace window and the reasoning for it.",
    ].join("\n"),
    solution: [
      "## Core",
      "",
      "A token cache keyed by credential, storing the token and its expiry. A request takes the cached token if it is valid. A background refresh starts at a randomised point in the token's lifetime — say between 60% and 80% — so instances refresh at different moments. The refresh is single-flight: a mutex or a shared promise ensures one call to the issuer no matter how many requests arrive, and callers keep using the current token until the new one lands.",
      "",
      "## When the issuer is down",
      "",
      "Refresh attempts back off exponentially with jitter, behind a circuit breaker that stops hammering a failing dependency. Meanwhile the cached token continues to serve requests until it expires. The service's availability therefore depends on the issuer only when the outage outlasts a token lifetime, which is the whole point of the design.",
      "",
      "## The trade-off to argue",
      "",
      "After expiry with no fresh token: serve a slightly stale token or fail the request? Serving a stale token keeps the product up and may be rejected downstream, turning a clean failure into a confusing one; failing fast is honest and takes the product down with the issuer. A short grace window — minutes, configurable, with alerts firing the moment it is used — is the usual compromise, and the right answer depends on whether the downstream even accepts stale tokens.",
      "",
      "## Probes",
      "",
      "- *Many credentials?* One cache entry and one single-flight per credential; a bounded pool of refreshers.",
      "- *Clock skew?* Treat the issuer's expiry as authoritative and refresh early enough to absorb a minute of skew.",
    ].join("\n"),
  },
  {
    slug: "design-global-quota-system",
    title: "Design a Global Multi-Tenant Quota System",
    category: "system-design",
    difficulty: "medium",
    companies: ["snowflake"],
    summary:
      "One usage record per tenant across every service, reserve-then-commit, idempotent usage events, and a chosen point between strict consistency and latency.",
    prompt: [
      "Design a quota system that enforces one limit per tenant — requests, compute seconds, storage bytes — across several backend services that each consume from it. A tenant must not exceed its quota by much, no service may be slowed noticeably by the check, and usage must be reconcilable after the fact.",
      "",
      "Cover the usage record and where it lives, how a service checks and consumes quota, how concurrent consumption from several services is kept honest, and the consistency-versus-latency decision at the heart of it.",
    ].join("\n"),
    hints: [
      "One usage record per tenant in a store with atomic increments; services reserve an amount, do the work, then commit or release.",
      "Idempotent usage events — keyed by (service, request id) — so a retried request does not double-count.",
      "Strict consistency on every check versus local token leases per service that trade a little over-admission for latency.",
    ],
    rubric: [
      "- **Usage record** — one record per tenant per quota, in a store with atomic check-and-increment.",
      "- **Reserve, then commit or release** — the two-step protocol that keeps concurrent consumers honest without long locks.",
      "- **Idempotent events** — usage keyed by request id so retries do not double-count; a reconciler that recomputes from events.",
      "- **Consistency versus latency** — strong consistency on every check versus leased local allowances per service, with the over-admission bound stated.",
      "- **Operations** — quota changes take effect quickly, usage is queryable, and a tenant over quota gets a clear error rather than a timeout.",
    ].join("\n"),
    solution: [
      "## Core",
      "",
      "A quota service owns one usage record per (tenant, quota) in a store with atomic increments. A consuming service calls `reserve(tenant, quota, amount, request_id)`; the service increments if the result stays within the limit and returns a reservation, else rejects. After the work, the consumer calls `commit` (keeps the reservation) or `release` (gives it back). Reservations expire so a crashed consumer does not hold quota forever. Every event is keyed by request id and recorded, so a retry is a no-op and a reconciler can rebuild the record from events.",
      "",
      "## The trade-off to argue",
      "",
      "Strong consistency on every check — one atomic increment at the quota store per request — gives an exact limit and puts a network round trip on every request in every service. Local token leases — each service periodically leases a slice of the tenant's remaining quota and admits locally — remove the round trip and allow over-admission bounded by the sum of outstanding leases. Choose by what the quota protects: billing-grade limits lean strict; abuse-protection limits lean leased.",
      "",
      "## Hot tenants",
      "",
      "One large tenant can turn its record into a hot key. Shard the record into counters that are summed on read, or lease to services as above; both trade exactness for throughput.",
      "",
      "## Probes",
      "",
      "- *Quota lowered below current usage?* Admit nothing new until usage falls; never reclaim committed usage.",
      "- *The quota store is down?* Services fall back to their last lease or a conservative local limit, and alert — fail-open versus fail-closed is a per-quota decision.",
    ].join("\n"),
  },
  {
    slug: "design-distributed-metrics-system",
    title: "Design a Distributed Metrics System",
    category: "system-design",
    difficulty: "medium",
    companies: ["snowflake"],
    summary: "Agents batch to an ingest tier, a time-series store partitioned by metric and time, downsampling for age — and a hard line on cardinality.",
    prompt: [
      "Design a metrics system for a large fleet: hosts and services emit counters, gauges and histograms with labels; engineers query them for dashboards and alerts.",
      "",
      "Cover collection, the ingest tier, the storage layout and how data ages, the query path, and the two decisions that shape such systems: push versus pull collection, and how to keep label cardinality from destroying the store.",
    ].join("\n"),
    hints: [
      "Agents aggregate locally and send batches to an ingest tier that validates, applies limits and writes to a time-series store partitioned by metric and time.",
      "Downsample old data — raw for days, one-minute rollups for months — and query the resolution the range asks for.",
      "Cardinality is the hidden cost: a label with unbounded values (user id, request id) creates a series per value. Enforce per-metric series limits at ingest.",
    ],
    rubric: [
      "- **Collection** — push from agents with local pre-aggregation versus pull by scrapers, with the argument for the fleet in question.",
      "- **Ingest** — a stateless tier that validates, enforces limits and batches writes; a durable buffer in front for spikes.",
      "- **Storage** — a time-series store partitioned by metric and time, compressed, with an inverted index from labels to series.",
      "- **Retention** — downsampling to coarser resolutions as data ages, and queries that pick the resolution by range.",
      "- **Cardinality control** — per-metric series limits, rejected or dropped labels, and visibility into who is producing them.",
    ].join("\n"),
    solution: [
      "## Core",
      "",
      'Agents on hosts collect counters, gauges and histograms, pre-aggregate over a few seconds, and push batches to an ingest tier. Ingest validates names and labels, enforces cardinality limits, and writes to a time-series store partitioned by metric name and time window. An inverted index maps label values to series ids so a query like `latency{service="api", region="eu"}` resolves to series before touching samples. A durable buffer in front of ingest absorbs spikes.',
      "",
      "## Retention",
      "",
      "Keep raw samples for a short window, then downsample: one-minute averages, minima and maxima for a longer window, five-minute for a year. Queries select the resolution from the time range, which keeps dashboards over a quarter as cheap as dashboards over an hour.",
      "",
      "## The trade-off to argue",
      "",
      "Push versus pull. Pull (a scraper hits each target) gives the system control over load and a natural health signal — a target that cannot be scraped is down — and needs service discovery and reachable targets. Push works through NATs and for short-lived jobs and lets a misbehaving client flood the system unless ingest applies quotas. Fleets of long-lived hosts lean pull; serverless and batch workloads lean push; many systems do both through a gateway.",
      "",
      "## Cardinality",
      "",
      "The store's cost is the number of series, not the number of samples. A label with unbounded values creates unbounded series. Enforce a per-metric series limit at ingest, reject or drop the offending label, and report the offending emitters; this is the control that keeps the system alive.",
      "",
      "## Probes",
      "",
      "- *Alerting?* An evaluator that runs queries on a schedule against the recent window; alerts are themselves metrics.",
      "- *Histograms?* Fixed buckets per metric, merged across hosts at query time; quantiles are estimates, say so.",
    ].join("\n"),
  },
  {
    slug: "design-web-crawler",
    title: "Design a Web Crawler at Scale",
    category: "system-design",
    difficulty: "medium",
    companies: ["snowflake"],
    summary:
      "A frontier of URLs partitioned by host, fetchers that respect per-host limits, dedup by URL and by content, and failure handling that never stalls the crawl.",
    prompt: [
      "Design a web crawler that, given seed URLs and two primitives — `fetchPage(url)` and `parseUrls(html)` — visits as much of the web as its budget allows and stores what it fetched.",
      "",
      "Cover the frontier of URLs to visit and how it is partitioned, how fetchers are scheduled so no host is overwhelmed, how duplicates are detected by URL and by content, how failures and slow hosts are handled so the crawl never stalls, and how the system resumes after a crash.",
    ].join("\n"),
    hints: [
      "Partition the frontier by host so one worker owns a host's queue and can enforce politeness — a delay between requests and a concurrency of one or two per host.",
      "Dedup URLs after normalisation with a set or a Bloom filter; dedup content by hashing the page so mirrors are stored once.",
      "Retries with backoff per URL, a per-host failure budget that pauses a misbehaving host, and timeouts so a slow host cannot hold fetchers.",
    ],
    rubric: [
      "- **Frontier** — a durable, prioritised queue of URLs partitioned by host, with a seen-set for URL dedup after normalisation.",
      "- **Politeness and scheduling** — per-host rate limits and concurrency, robots rules, and a scheduler that keeps every fetcher busy without hammering one host.",
      "- **Dedup by content** — hashing fetched pages so duplicates and mirrors are stored once.",
      "- **Failure handling** — timeouts, retries with backoff, per-host circuit breaking, and a dead-letter list; the crawl never blocks on one host.",
      "- **Recovery** — frontier and seen-set persisted so a crash resumes without refetching everything.",
    ].join("\n"),
    solution: [
      "## Core",
      "",
      "The frontier is a durable queue of URLs with priorities, partitioned by host; each partition is owned by one fetcher process at a time. A fetcher pops a URL, checks the seen-set, fetches with a timeout, hashes the content, stores the page if the hash is new, parses out links, normalises them, and pushes unseen ones onto the frontier. The seen-set is a Bloom filter in memory backed by an exact store, because a crawl of billions of URLs cannot keep an exact set per process.",
      "",
      "## Politeness",
      "",
      "Partitioning by host is what makes politeness enforceable: one owner means one place to apply the per-host delay and concurrency limit, and to honour robots rules. The scheduler keeps fetchers busy by giving each one many hosts, so waiting on one host's delay never idles a worker.",
      "",
      "## Failure handling",
      "",
      "Every fetch has a timeout. Failures retry with backoff a bounded number of times, then go to a dead-letter list. A per-host failure budget pauses a host that keeps failing, so a broken site cannot consume the retry capacity. Because the frontier is durable and the seen-set is persisted, a crashed fetcher's partition is simply reassigned and resumes.",
      "",
      "## The single-process version",
      "",
      "The same algorithm with one queue and one seen-set is [Crawl Every Reachable Page](/problems/crawl-reachable-pages); with several threads, the seen-set's check-and-add must be atomic and termination must count in-flight fetches.",
      "",
      "## Probes",
      "",
      "- *Traps and infinite pages?* Depth limits, per-host page budgets, and URL pattern rules.",
      "- *Freshness?* Recrawl priority from how often a page changed before; the frontier is a priority queue for a reason.",
    ].join("\n"),
  },
  {
    slug: "design-count-nodes-in-server-tree",
    title: "Count the Nodes in a Tree of Servers",
    category: "system-design",
    difficulty: "medium",
    companies: ["snowflake"],
    summary:
      "A request fans down the tree and counts fan back up; messages can be lost or duplicated, so every message carries an id and every handler is idempotent.",
    prompt: [
      "Servers are arranged in a tree: each knows its children and can send them asynchronous messages, and messages may be delayed, lost or delivered twice. Design a protocol by which the root learns how many servers are in the tree.",
      "",
      "Describe the messages, what each server stores while a count is in progress, how retries work without double counting, how a server with a crashed child completes, and how a second count can start while the first is still finishing.",
    ].join("\n"),
    hints: [
      "Two message types: a count request flowing down and a count reply flowing up. A leaf replies 1; an inner node replies 1 plus the sum of its children's replies.",
      "Give every count a request id. A node remembers the id and its partial sums, so a duplicate request is answered from memory and a duplicate reply from a child is ignored.",
      "Retry a child that has not replied, with a timeout; after enough retries, report the child as unreachable in the reply rather than hanging the whole count.",
    ],
    rubric: [
      "- **Protocol** — a request down and a reply up, with a leaf replying 1 and an inner node summing.",
      "- **Idempotency** — request ids, per-id state at each node, duplicate requests answered from memory, duplicate replies ignored.",
      "- **Retries and timeouts** — per-child retries with backoff, and a bounded wait after which the child is reported missing.",
      "- **Concurrent counts** — state keyed by request id so overlapping counts do not interfere, with expiry for old ids.",
      "- **Honesty about failure** — the reply says what was counted and what was unreachable instead of pretending to be exact.",
    ].join("\n"),
    solution: [
      "## Protocol",
      "",
      "`Count(request_id)` travels down; `Reply(request_id, count, unreachable)` travels up. A leaf replies immediately with count 1. An inner node records the request id, forwards `Count` to every child, and keeps a table of which children have replied and with what. When every child has replied — or has been given up on — it replies with 1 plus the sum, and the list of unreachable subtrees.",
      "",
      "## Idempotency",
      "",
      "Messages can be duplicated, so the request id is the whole mechanism: a node that receives `Count` for an id it has already seen re-sends its stored reply if it has one, or does nothing if the count is still in progress; a reply from a child that already replied for that id is dropped. No message is ever processed twice in a way that changes the sum.",
      "",
      "## Loss and crashes",
      "",
      "A parent retries `Count` to a silent child with backoff until a deadline. If the child never answers, the parent completes its reply with that child marked unreachable, so a single crashed server delays the count by one timeout rather than blocking it forever. The root then reports a count and a list of subtrees it could not reach — an honest answer, not an exact one.",
      "",
      "## Concurrent counts",
      "",
      "All per-count state is keyed by request id, so two counts in flight do not mix. Entries expire after the deadline plus a grace period so a late duplicate is still recognised, and memory does not grow without bound.",
      "",
      "## Probes",
      "",
      "- *The tree changes mid-count?* A node answers for the children it knew when it received the request; the next count sees the new shape.",
      "- *Exactly-once?* Not achievable over a lossy channel; at-least-once delivery plus idempotent handling is the standard answer, and this protocol is a small example of it.",
    ].join("\n"),
  },
];
