import type { Problem } from "./types";

// Pinterest design-round prompts, final pair of shorter sketches: visual
// search (Lens) and a blob storage service. See seed-design-a.ts for the
// series notes.

export const designProblemsD: Problem[] = [
  {
    slug: "design-visual-search",
    title: "Design Visual Search",
    category: "system-design",
    difficulty: "hard",
    companies: ["pinterest"],
    summary:
      "Embeddings, sharded ANN retrieval, and fresh pins searchable in seconds.",
    prompt: [
      '"Design visual search: given a query image (or a crop of one), return visually similar pins with low latency. The index covers billions of images, and a newly created pin should be searchable within seconds."',
      "",
      "Assume an embedding model exists; you design the serving system. Budget ~200 ms per query including embedding inference. Billions of pin embeddings at 256 floats ≈ 1 KB each means terabytes of index — sharded and quantized. Metadata filters (country, safety) must apply during retrieval, not as an afterthought.",
      "",
      "Cover: the root/leaf retrieval architecture, how the index shards and what that costs in recall, realtime inserts into an ANN index under concurrent reads, deletions, and how you'd know retrieval quality is degrading.",
      "",
      '*Reported as: "Design visual search backed by Pinterest Lens (image embedding + ANN retrieval + ranking)" (TechScreen); "Build a visual search system" (System Design Handbook).*',
    ].join("\n"),
    hints: [
      "The size forces the architecture: terabytes of embeddings can't fit one box, so a root fans out to leaf shards each holding an ANN graph over a partition, and merges top-k — lightweight scoring at the leaves, a heavier reranker at the root.",
      "Apply metadata filters during graph traversal, not after: post-filtering top-k can leave you with zero results when the filter is selective.",
      "Freshness comes from a separate realtime segment — new embeddings ingested via a log into an in-memory index that's periodically sealed and merged — so the big immutable index never blocks on writes.",
    ],
    rubric: [
      "- **Scale math driving shape** — billions × ~1 KB embeddings → terabytes → sharded, quantized index; a root/leaf scatter-gather with per-leaf top-k and root-side rerank.",
      "- **Partitioning tradeoff** — hash partitioning (every query touches all shards, full recall) vs coarse-cluster partitioning (fewer shards per query, recall risk); states the choice and its cost.",
      "- **Two-stage scoring** — cheap similarity at the leaves, heavier reranker at the root using metadata and engagement; query-image-hash result caching.",
      "- **Filtered retrieval** — country/safety filters applied during ANN traversal rather than post-filtering, with the zero-results failure mode named.",
      "- **Realtime index path** — new pins flow through a log into an in-memory realtime segment (lock-free inserts, briefly imperfect connectivity accepted), sealed and merged periodically; deletions as tombstones filtered at query time with compaction.",
      "- **Quality observability** — continuous recall monitoring: ANN results compared against exact KNN on a sample so index degradation is visible before users notice.",
    ].join("\n"),
    solution: [
      "## Shape and numbers",
      "",
      "Billions of pin embeddings at 256 floats ≈ 1 KB each → terabytes: the index is sharded and quantized by necessity. Query budget ~200 ms including embedding inference. Pinterest's relevant practice: one **unified** embedding trained to serve multiple tasks (search, related pins, shopping) rather than one per surface — it simplifies the fleet and the index.",
      "",
      "## Query path",
      "",
      "An inference service computes the query image's embedding (crops re-embed the cropped region). A root service fans out to leaf shards, each holding an HNSW graph over its partition of pins; leaves apply metadata filters (country, safety) **during traversal** — post-filtering a selective filter can leave zero results — and return local top-k with distances. The root merges, then reranks with a heavier model that sees pin metadata and engagement, and caches results by query-image hash.",
      "",
      "Partitioning is the stated tradeoff: hash of pin id spreads load and preserves recall but every query touches every shard; coarse clustering (route to the nearest centroids' shards) cuts fan-out at a recall cost. Start with hash; move hot surfaces to clustered routing when the fleet cost demands it.",
      "",
      "## Deep dive: freshness without blocking the big index",
      "",
      "New pins enter through Kafka into an in-memory realtime segment — an LSM-flavored arrangement: lock-free inserts under concurrent reads (accepting briefly imperfect graph connectivity, guarded by a memory barrier), periodically sealed, flushed, and merged into the main segments. This is how Pinterest's Manas Realtime and HNSW Realtime work; fresh embeddings become searchable in seconds while the large immutable segments stay read-optimized.",
      "",
      "Deletions: tombstones filtered at query time, cleaned up by compaction that reuses the largest segment rather than rebuilding — full rebuilds at this size are a last resort.",
      "",
      "## Deep dive: knowing it still works",
      "",
      "ANN quality degrades silently — graphs fragment, quantizers drift from the embedding distribution. Continuously sample queries and compare ANN results against exact KNN on the sample; alert on recall@k drops. Track per-leaf latency and result-count balance so a sick shard (returning few or poor candidates) is visible before users notice worse results.",
      "",
      "## Probes to expect",
      "",
      "- *Why HNSW and not IVF-PQ everywhere?* HNSW gives better recall-latency at high recall targets and supports incremental inserts; quantization still applies for memory. The realtime segment needs insertability above all.",
      "- *Model version upgrade?* Embeddings from different model versions aren't comparable — dual-write to a new index and cut over per surface; the unified-embedding strategy is what keeps this from being N migrations.",
      "- *Crops?* Embed the crop region, not the whole image; the object-detection front end that proposes crops is the product's entry point, but the serving system just sees another embedding.",
    ].join("\n"),
  },
  {
    slug: "design-blob-storage",
    title: "Design a Blob Storage Service",
    category: "system-design",
    difficulty: "medium",
    companies: ["pinterest"],
    summary:
      "Metadata plane vs data plane, chunk replication, and the atomic-commit moment.",
    prompt: [
      '"Design a highly available blob storage service similar to S3 — or, in its product framing, a Google Photos-like service: users upload files or photos, retrieve them from anywhere, and never lose data."',
      "",
      "Cover: the split between the metadata plane and the data plane, the write path and where the object atomically comes into existence, replication versus erasure coding, what background processes keep the system healthy, and — for the Photos framing — dedup and quotas.",
      "",
      '*Reported as: "Design highly available blob storage service similar to S3" and "Design a Google Photos-like service" (PracHub).*',
    ].join("\n"),
    hints: [
      "Separate planes: object name → chunk list, versions, and ACLs in a sharded strongly consistent metadata store; immutable content-addressed chunks of a few MB on storage nodes placed by a placement service.",
      "The metadata commit is the atomic 'the object exists' moment — chunks written first, metadata last. Everything a crashed client leaves behind is orphaned chunks for GC.",
      "Have the replication-vs-erasure-coding numbers ready: 3× replication is 200% overhead and fast reads; 10+4 erasure coding is 40% overhead with costlier reads and repairs.",
    ],
    rubric: [
      "- **Plane separation** — metadata (name → chunks, versions, ACLs; sharded, strongly consistent per key) distinct from the data plane (immutable content-hashed chunks placed across failure domains).",
      "- **Write path atomicity** — chunk, hash, replicate (or encode) each chunk before the metadata commit that makes the object exist; the dangerous window is named, and orphaned chunks are GC'd via reference counts.",
      "- **Durability strategy** — replication vs erasure coding argued with overhead and repair-cost numbers, placed across failure domains; scrubbing for bit rot and re-replication on node loss.",
      "- **Read path** — metadata lookup then parallel chunk fetches, CDN for hot public objects.",
      "- **Consistency story** — strong per-key metadata, trivially consistent immutable chunks; what a reader can and cannot observe mid-upload.",
      "- **Product layer (Photos framing)** — client-side dedup by content hash before upload, per-user quotas enforced in the metadata plane.",
    ].join("\n"),
    solution: [
      "## Two planes",
      "",
      "**Metadata plane:** object name → ordered list of chunk ids, versions, ACLs, size — in a sharded, strongly consistent store (consensus-replicated per shard). **Data plane:** immutable chunks of a few MB, addressed by content hash, placed on storage nodes by a placement service that spreads replicas across failure domains (rack, AZ). The separation lets each plane scale and fail independently — metadata is small and hot; data is huge and cold.",
      "",
      "## Write path",
      "",
      "The client streams to a front end that chunks and hashes; each chunk is written to N replicas (or erasure-coded into k+m fragments) **before** the metadata commit. The metadata commit is the atomic \"the object exists\" moment — a reader either sees the complete object or nothing. A client that crashes mid-upload leaves orphaned chunks, which garbage collection reclaims via reference counts maintained by the metadata store (chunks are shared across objects because they're content-addressed, so refcounts, not ownership).",
      "",
      "## Read path",
      "",
      "Metadata lookup, then parallel chunk fetches from the nearest replicas, reassembled by the front end or the client; a CDN fronts hot public objects. Range reads map directly to chunk offsets — one reason for fixed-ish chunk sizes.",
      "",
      "## Deep dive: replication vs erasure coding",
      "",
      "3× replication: 200% storage overhead, reads hit any single replica, repair is a copy. 10+4 erasure coding: 40% overhead, but reads of a degraded stripe and repairs require k fragments and compute. The standard resolution is temperature-tiered: replicate hot and recent data for read performance, erasure-code cold data for cost, with a background demotion job. State the failure-domain requirement either way: replicas or fragments must not share a rack or AZ.",
      "",
      "## Background machinery",
      "",
      "Scrubbing continuously re-reads chunks and verifies content hashes (bit rot is real at petabyte scale); re-replication restores redundancy on node loss, prioritized by how many replicas remain; GC walks unreferenced chunks past a safety window. Each is throttled so the maintenance plane cannot starve foreground traffic.",
      "",
      "## The Photos layer",
      "",
      "Client-side dedup: hash before upload and skip the transfer when the chunk exists (the same photo shared into many libraries stores once). Per-user quotas live in the metadata plane, enforced at commit time. Album/browse structures are metadata-plane rows referencing objects — the data plane never learns about products.",
      "",
      "## Probes to expect",
      "",
      "- *Consistency model?* Strong per-key metadata; immutable chunks are trivially consistent; the only ambiguous window is pre-commit, and it's invisible to readers by construction.",
      "- *Hot object?* Chunks are immutable → replicate hot chunks wider and let the CDN absorb public traffic; the metadata row caches with a short TTL.",
      "- *Version and delete semantics?* Metadata versions are cheap (new chunk list, shared unchanged chunks); delete drops references and GC does the rest — which also gives trash/undelete for free within the GC window.",
    ].join("\n"),
  },
];
