import type { Problem } from "./types";

// Pinterest design-round prompts 1–2 of the researched set (home feed,
// notifications), from the Pinterest_Design_Round_Prep research doc: each
// carries the prompt as reported by candidates, a rubric for the AI design
// review, and the worked L5-grade solution grounded in Pinterest's public
// engineering. Continues in seed-design-b/c/d.ts.

export const designProblemsA: Problem[] = [
  {
    slug: "design-pinterest-home-feed",
    title: "Design Pinterest's Home Feed",
    category: "system-design",
    difficulty: "hard",
    companies: ["pinterest"],
    summary:
      "Recsys serving, not a social timeline — retrieval funnels, session state, four nines.",
    prompt: [
      '"Design the Pinterest home feed. When a user opens the app they see a personalized, infinitely scrollable grid of pins drawn from boards they follow and from recommendations. It has to feel fresh, never repeat, and load fast for hundreds of millions of people."',
      "",
      "Assume a scoring model exists — your job is retrieval, serving, freshness, and state. The feed is mostly recommendations, not followed content, which should make you suspicious of pure fan-out-on-write. Target: first page p99 under ~400 ms end to end, four nines of read availability, new pins eligible within minutes, and in-session feedback (hide, save) influencing later pages.",
      "",
      "Cover: the retrieval-to-ranking funnel and why you cannot score the corpus online, pagination without repeats, the push/pull/hybrid decision for followed boards, and what degrades when each dependency fails. Ads insertion, model training, and moderation are out of scope.",
      "",
      "*Reported as: \"typical recsys\" (Blind L5 loop), \"Design Pin recommendation system powering the personalized home feed\" (PracHub), \"home feed ranking pipeline at billion-user scale\" (TechScreen), \"feed generation\" (Glassdoor forum).*",
    ].join("\n"),
    hints: [
      "Do the math first: 640M MAU → ~160M DAU → ~45k QPS peak. If each request scored 3k candidates with a heavy model that's 135M evaluations/s — impossible. The number forces a funnel: retrieve thousands → light score → heavy score hundreds.",
      "Pagination has two bad options — re-rank per page (results shift under the user) or a server-side iterator (dies with the box). One expensive ranking pass into a session cache keyed by an opaque id, with the cursor as an offset, avoids both.",
      "Followed boards are the only source that behaves like a social timeline. Fan out on write only below a follower threshold; mark celebrity boards as pull sources merged at read time. Recommendations dominate anyway, so the pull path stays small.",
    ],
    rubric: [
      "- **Estimates that shape the design** — derives ~160M DAU / ~45k QPS peak and concludes online scoring of the corpus is impossible, motivating a retrieve → light-score → heavy-score funnel. Numbers that appear but change nothing score low.",
      "- **Per-user vs global state** — separates hot per-user state (pools, session cache, seen filter in a wide-column KV) from globally shared, heavily cached pin metadata, and says how each is keyed and sharded.",
      "- **Followed-board fan-out** — push vs pull vs hybrid with a follower threshold; names write amplification for celebrity boards and keeps the async fan-out off the request path via a job queue that tolerates delay.",
      "- **Pagination and dedup** — one ranking pass cached per session with an opaque cursor; dedup twice (long-lived bloom filter at candidate generation, exact within the session); handles in-session hide/save without a re-rank.",
      "- **Availability and degradation** — a fallback tier per dependency (hedged pool reads across AZs, per-generator deadlines, light-score-only mode, precomputed or popular pools) and a metric for how much traffic each tier serves.",
      "- **Freshness paths** — new pins retrievable within minutes via an async embedding + realtime-index path; user signals stream into the per-request user embedding; neither is synchronous with the triggering write.",
    ].join("\n"),
    solution: [
      "## The shape of the problem",
      "",
      "Pinterest's feed is interest-driven, not a social timeline — recommendations dominate followed content. That single product fact drives everything: pure fan-out-on-write is the wrong primary design, and the system is a recommendation-serving funnel with per-user state around it.",
      "",
      "**Numbers first.** 640M MAU → assume ~160M DAU. At 8 feed loads/day that's ~1.3B requests/day ≈ 15k QPS average, ~45k peak. The corpus is 100B+ pins. If each request scored 3k candidates with a heavy model: 45k × 3k = 135M model evaluations per second — impossible. So the design is a funnel: retrieve ~thousands → cheap score → heavy score ~hundreds. Materialized per-user state is affordable: 2k pin ids × ~50 B = 100 KB/user × 640M ≈ 64 TB in a sharded KV; a 1% bloom filter over 10k recent impressions is ~12 KB/user.",
      "",
      "## API and data",
      "",
      "```",
      "GET  /v1/feed?cursor=<opaque>&page_size=25 → { pins:[...], cursor, session_id }",
      "POST /v1/feed/feedback { session_id, pin_id, action: hide|save|closeup }",
      "",
      "pin          (sharded MySQL object table)  pin_id → {image_sig, board_id, owner, title, link, created_at}",
      "board_pins   (mapping table, board's shard) board_id → [pin_id ordered by sequence]",
      "user_follows (mapping table, user's shard)  user_id → [board_id | user_id]",
      "user_pool    (wide-column KV)               user_id → sorted set of (score, pin_id, source), written async",
      "feed_session (KV, TTL 30 min)               session_id → ranked pin list + cursor position",
      "seen_filter  (KV)                           user_id → rolling bloom filter of impressed pin ids",
      "```",
      "",
      "The first structural decision: per-user hot state (pool, session, seen filter) and globally shared pin metadata live in different stores tuned for different workloads — Pinterest's own home-feed write-up describes exactly this split.",
      "",
      "## Read path",
      "",
      "The feed service reads the user's seen filter and realtime signals, fans out in parallel to candidate generators (followed boards, interest pools, graph walks) with a strict per-generator deadline (~40 ms), merges ~3k candidates, runs a lightweight two-tower scorer (pin embeddings precomputed; the user embedding computed once per request from recent signals — the hot-path op is a dot product), sends the top ~500 to the full ranker, blends for source diversity, dedups against the seen filter, writes the ranked list into the session cache, and returns page one. Subsequent pages are a cursor into the cache: no re-retrieval, no repeats, stable ordering. When the cache expires the client gets a new session with an updated seen filter.",
      "",
      "## Deep dive: push, pull, or hybrid",
      "",
      "Fan-out on write makes reads trivial but write amplification equals follower count — a board with 5M followers means 5M KV appends per pin, dozens of times a day. Fan-out on read costs nothing to write but turns reads into hundreds of scatter reads. The hybrid: async fan-out through a job queue for boards under ~50–100k followers (a fan-out 30 seconds late is invisible; one that's lost is not — Pinterest's PinLater semantics), and mark larger boards as pull sources the feed service merges at request time. Because recommendations dominate, the pull path only needs a handful of candidates, keeping its latency bounded.",
      "",
      "## Deep dive: pagination without repeats",
      "",
      "Re-ranking every page is expensive and shifts results under the user; a server-side iterator means sticky sessions and state that dies with the box. The session cache avoids both: one expensive pass produces a few hundred pins under an opaque session id (KV, 30-minute TTL); the cursor is offset + session id, so any replica serves page five. Dedup happens twice — the bloom filter at candidate generation (approximate is fine; the corpus is enormous) and exactly within the session. On hide: drop remaining session pins within a cosine threshold of the hidden pin's embedding and down-weight the source next pass — a cheap filter over cached items, not a re-rank.",
      "",
      "## Deep dive: four nines on the read path",
      "",
      "The feed is the app, so every dependency needs a degradation story. Hedged reads: send the pool read to the primary and, past the p99.9 latency, to a standby cluster in another AZ; take the first answer (Pinterest reported this took feed reads past four nines). Per-generator deadlines: a slow graph server means fewer candidates, not a slow page. Ranker timeout: serve the light-scored ordering. Generation fully down: serve the precomputed pool, then a per-locale popular pool. Every fallback still returns a feed; the metric to watch is the fraction of requests served from each tier.",
      "",
      "## Freshness",
      "",
      "New pins: the creation event computes the embedding online (only pins a few hours old need online inference) and inserts into a realtime HNSW index via Kafka — retrievable by similarity within seconds. New signals: engagement events stream into a compact last-N-actions store feeding the per-request user embedding. Both async, both monitored for lag; the product requirement is minutes.",
      "",
      "## Probes to expect",
      "",
      "- *Why not fan out everything on write?* 90% of the feed depends on the user's current state, and celebrity boards make write amplification unbounded. Precompute what's stable; compute what's personal at request time.",
      "- *Cold start?* Onboarding interest picks seed the user embedding; serve per-interest/per-locale popular pools refreshed hourly, with an exploration-heavy blend.",
      "- *What breaks first at 10x?* Ranker GPU cost. Levers: tighter funnel, cache the user embedding across pages, batch ranker calls.",
      "- *How do you know it works?* Saves/closeups/hides per session, p99 time-to-first-page, fraction served per degradation tier; A/B for ranker changes (2–3% save lifts are meaningful at this scale).",
    ].join("\n"),
  },
  {
    slug: "design-notification-system",
    title: "Design a Notification System",
    category: "system-design",
    difficulty: "hard",
    companies: ["pinterest"],
    summary:
      "Fan-out, viral-pin aggregation under skew, and deciding not to send.",
    prompt: [
      '"Design Pinterest\'s notification system: push, email, and in-app notifications for comments, saves, follows, new pins on boards you follow, and recommendations. Billions of candidate events a day, with user preferences and volume limits."',
      "",
      'A reported variant sharpens the hard part: *"Send a push notification to a pin owner when someone comments on their pin. A pin can go viral and get thousands of comments in minutes; the owner should not get thousands of pushes."*',
      "",
      "Assume push (APNs/FCM), email, and an in-app inbox with unread counts. Social events should notify within ~5 s p99; board updates within minutes; digests are batched. Internally delivery is at-least-once — the user must still see at-most-once. Respect per-user caps, quiet hours, and per-type preferences; unsubscribe takes effect immediately. The system must absorb 100x spikes from viral pins without backing up unrelated traffic.",
      "",
      "*Reported as: 1point3acres 2018 onsite (candidate rejected on \"architecture\"), Dev Genius 2020 write-up, PracHub ×2, Glassdoor forum — the most-reported prompt after the feed.*",
    ].join("\n"),
    hints: [
      "The viral pin is a stream-aggregation problem with a hot key: 1M comments in 10 minutes is ~1.7k events/s hashing to one partition. Two-stage aggregation — partition by (pin, salt) for partial counts, then merge keyed by pin — turns the firehose into one message per salt per second.",
      "Exactly-once to the user on an at-least-once pipeline means the last hop is idempotent: a dedup key of (recipient, event or window id) with an atomic set-if-absent before calling the push provider.",
      "The senior half of the answer is volume control: fan-out produces candidates, not sends. A ranker over per-user event pools plus a feedback controller tuning score thresholds to hit send-volume targets is what separates plumbing from product.",
    ],
    rubric: [
      "- **Decoupled ingestion** — producers emit to a log/queue and move on; the notification path absorbs spikes without slowing the triggering writes. Synchronous fan-out anywhere is a major miss.",
      "- **Viral-pin aggregation under skew** — windowed per-(owner, pin, type) state with escalating digest thresholds, and a salted two-stage aggregation for the hot partition. This is the make-or-break dive.",
      "- **Idempotent delivery** — names where duplicates arise and makes the final send idempotent via a dedup key and atomic set-if-absent; articulates the duplicate-vs-loss tradeoff per channel.",
      "- **Fan-out strategy for large boards** — paged reads of the follower mapping, batched async appends with retries, and a pull path (or hot-sources table) above a follower threshold.",
      "- **Volume control and preferences** — candidates ≠ sends: ranking with per-user budgets/caps, quiet hours in the recipient's timezone, and preference/unsubscribe checks that are fresh at send time (compliance, not UX).",
      "- **Data model fit** — justifies the stores: sharded mapping table for follows (one-hop queries, not a graph DB), wide-column inbox with reverse-timestamp rows, counter cache with reconcile for unread.",
    ].join("\n"),
    solution: [
      "## Numbers and the two lanes",
      "",
      "Raw events (comment, save, follow, pin-to-board): assume 10B/day ≈ 115k/s average, ~500k/s peak. After fan-out and eligibility, ~1B candidates/day; after ranking and caps, ~500M sends/day ≈ 6k/s average. A viral pin does 1M comments in 10 minutes — 1.7k events/s on a single (owner, pin) key, which is the whole design. A board with 5M followers getting one pin means 5M candidate rows — async and batched, never synchronous. Inbox at 90 days ≈ 9 TB.",
      "",
      "Producers never call the notification system; they emit to Kafka and move on — that keeps the comment write fast and lets this path absorb spikes. From there, two lanes through one stream processor keyed by (recipient, object, type):",
      "",
      "- **Social lane** (comment, save, follow): straight to rank-and-policy for delivery within seconds.",
      "- **Board lane**: async fan-out into per-user daily event pools, swept by a ranker a few times a day at each user's best delivery hour.",
      "",
      "Both lanes end at per-channel queues whose senders check the sent-set before calling APNs/FCM/email, and write receipts back for model labels and unread counts.",
      "",
      "## Data",
      "",
      "```",
      "event_pool (wide-column KV)  recipient_id → [candidate: type, object_id, actors[], count, score, window_end]",
      "inbox      (wide-column KV)  recipient_id, reverse_ts → rendered notification; TTL 90 d",
      "unread     (Redis)           recipient_id → int, reconciled from inbox on read",
      "sent_set   (KV, TTL 7 d)     (recipient_id, dedup_key) → sent_ts        -- idempotency",
      "prefs      (SQL, cached)     recipient_id → channel prefs, caps, timezone, device tokens",
      "follows    (sharded mapping) from_id → [to_id]",
      "```",
      "",
      "On the database probe: follows are one-hop queries — \"all followers of X\" is a range scan, \"does U follow X\" a point lookup — so a sharded relational mapping table (from_id, to_id, sequence on from's shard) beats a graph database, which earns its complexity only on multi-hop traversals you never run.",
      "",
      "## Deep dive: viral-pin aggregation",
      "",
      "Keep windowed state per (owner, pin, \"comment\"): count, first few actor ids, window start. Emit the first event immediately (the owner wants to know in seconds), then suppress and emit digests when the window closes (~10 min) or the count crosses escalating thresholds (10, 100, 1k, 10k) — one push per escalation, not per comment.",
      "",
      "The skew: all 1.7k events/s hash to one partition. Two-stage aggregation fixes it — partition by (pin, salt) for a local pre-aggregate emitting partial counts every second, then merge in a stage keyed by pin. The hot key now costs one message per salt per second. The same trick protects the per-recipient token bucket sitting after aggregation as a second line of defense.",
      "",
      "## Deep dive: fan-out and deciding not to send",
      "",
      "The fan-out worker reads the follower mapping in pages, groups recipients by pool shard, and batch-appends through a job queue with retries. Above a follower threshold, skip fan-out: record the event once in a hot-sources table and let the pool ranker pull it at sweep time.",
      "",
      "The senior point: fan-out produces candidates, not sends. Pinterest's NEP moved from daily offline budgeting to streaming — every eligible user gets a daily candidate pool, a multi-task model predicts open/click/unsubscribe, and a **PID controller** tunes score thresholds per segment so actual send volume tracks a target; weekly per-user budgets are set by marginal utility across user states (dormant users get fewer). Push and email are decided separately from the same utility scores because their annoyance budgets differ.",
      "",
      "## Deep dive: exactly-once to the user",
      "",
      "Kafka plus retries means every stage can see an event twice. Make the last hop idempotent: the sender computes a dedup key (recipient, event or aggregation-window id), does an atomic set-if-absent in the sent-set (7-day TTL), and only calls the provider on success. If the provider is flaky, prefer set-after-send with a short in-flight lock — trading a rare duplicate for a rare loss — and say which the product prefers (for push: loss). Dead-letter queue for poison events; provider feedback (invalid token) prunes the device registry.",
      "",
      "## Preferences must be fresh at send time",
      "",
      "Cache prefs aggressively for eligibility, but re-check the source of truth at send time: an unsubscribe followed by one more email is a compliance problem. Quiet hours compute in the recipient's timezone; the send-time optimizer schedules into a time-bucketed delayed queue scanned by a scheduler, not in-memory timers.",
      "",
      "## Probes to expect",
      "",
      "- *A partition is hot from one viral pin — now what?* Salted two-stage aggregation absorbs it; if it's already burning, widen the aggregation window for that key only.",
      "- *Inbox ordering and unread accuracy?* Reverse-timestamp columns for newest-first scans; unread is a counter incremented on insert, reset on read-marker update, reconciled on inbox open.",
      "- *Push vs email: same pipeline?* Same candidates and ranker; separate policy, budgets, and queues.",
    ].join("\n"),
  },
];
