import type { Problem } from "./types";

// Apple front-end bank: React output and multiple-choice questions, one per
// problem — a reducer traced by hand, nested context providers, fetching on
// mount, and the context API. These are documents: predict or choose,
// explain, then open the Solution.

export const appleReactQuizProblems: Problem[] = [
  {
    slug: "redux-reducer-state-quiz",
    title: "Predict the State: A Redux Reducer",
    category: "frontend",
    difficulty: "easy",
    companies: ["apple"],
    summary: "Trace three dispatches through a reducer by hand — and read the case labels character by character.",
    prompt: [
      "What is the state after the three dispatches? Explain why.",
      "",
      "```js",
      "const initialState = { foo: [1], switch: false };",
      "",
      "function FooReducer(state = initialState, action) {",
      "  switch (action.type) {",
      "    case \"SET_FOO\":",
      "      return Object.assign({}, state, { foo: action.foo, switch: true });",
      "    case \"PUSH_FOO\":",
      "      return Object.assign({}, state, {",
      "        foo: [...state.foo, action.foo],",
      "        switch: !state.switch,",
      "      });",
      "    default:",
      "      return state;",
      "  }",
      "}",
      "",
      "dispatch({ type: \"SET_FOO\", foo: [1, 2] });",
      "dispatch({ type: \"PUSH_FOO\", foo: 3 });",
      "dispatch({ type: \"PUSH_FOO\", foo: 6 });",
      "```",
    ].join("\n"),
    hints: [
      "Trace the reducer one action at a time: each case returns a new object built from the previous state.",
      "Watch `switch`: the set makes it true, and each push flips it.",
    ],
    solution: [
      "## Answer: `{ foo: [1, 2, 3, 6], switch: true }`",
      "",
      "`SET_FOO` replaces `foo` with `[1, 2]` and sets `switch` to true. Each `PUSH_FOO` appends to a copy of `foo` and flips `switch`: false after the first push, true after the second.",
      "",
      "## Worth saying out loud",
      "",
      "- **Read case labels character by character.** If a case were written `\"SET FOO\"` while the actions use `\"SET_FOO\"`, every action would fall through to `default` and the state would stay `{ foo: [1], switch: false }` — with no error anywhere.",
      "- `Object.assign({}, state, ...)` and the spread both build a new object, which is what lets `connect` or `useSelector` notice the change.",
      "- Action type constants (or Redux Toolkit's `createSlice`) exist to make that typo impossible.",
    ].join("\n"),
  },
  {
    slug: "use-context-output-quiz",
    title: "Predict the Output: Nested Context Providers",
    category: "frontend",
    difficulty: "medium",
    companies: ["apple"],
    summary: "Default value, nearest provider, and why `memo` doesn't stop a context update.",
    prompt: [
      "What does this render? Explain why.",
      "",
      "```jsx",
      "const Theme = createContext(\"light\");",
      "",
      "const Label = memo(function Label() {",
      "  return <span>{useContext(Theme)} </span>;",
      "});",
      "",
      "function App() {",
      "  return (",
      "    <>",
      "      <Label />",
      "      <Theme.Provider value=\"dark\">",
      "        <Label />",
      "        <Theme.Provider value=\"blue\">",
      "          <Label />",
      "        </Theme.Provider>",
      "      </Theme.Provider>",
      "    </>",
      "  );",
      "}",
      "```",
    ].join("\n"),
    hints: [
      "The default passed to `createContext` is used only when there is no provider above the component.",
      "Which provider is nearest above each `Label` — and what does `memo` do, or not do, when a context value changes?",
    ],
    solution: [
      "## Answer: `light dark blue`",
      "",
      "- The default passed to `createContext` applies only when no provider is above the component.",
      "- The nearest provider wins.",
      "- **`memo` does not block context updates.** Every consumer re-renders when its provider's value changes by `Object.is`, so an inline object as `value` re-renders every consumer on every parent render — which is why provider values are usually wrapped in `useMemo`, and the functions inside them in `useCallback`.",
    ].join("\n"),
  },
  {
    slug: "fetch-on-mount-effect-quiz",
    title: "Which Effect Fetches Data Once on Mount?",
    category: "frontend",
    difficulty: "easy",
    companies: ["apple"],
    summary: "No dependency array loops, an async effect returns a promise, and a fetch in the render body runs every render.",
    prompt: [
      "Which option loads the users once, when `Users` first renders? Explain what goes wrong with the others.",
      "",
      "```jsx",
      "// A",
      "useEffect(() => {",
      "  fetch(\"/api/users\").then((res) => res.json()).then(setUsers);",
      "});",
      "",
      "// B",
      "useEffect(async () => {",
      "  const res = await fetch(\"/api/users\");",
      "  setUsers(await res.json());",
      "}, []);",
      "",
      "// C",
      "useEffect(() => {",
      "  fetch(\"/api/users\").then((res) => res.json()).then(setUsers);",
      "}, []);",
      "",
      "// D: no effect at all, in the component body",
      "fetch(\"/api/users\").then((res) => res.json()).then(setUsers);",
      "```",
    ].join("\n"),
    hints: [
      "An effect with no dependency array runs after every render.",
      "An `async` function returns a promise, and React expects an effect to return a cleanup function or nothing.",
    ],
    solution: [
      "## Answer: C",
      "",
      "- **A** has no dependency array, so it runs after every render. The state update causes a render, which runs the effect again: a loop.",
      "- **B** passes an `async` function directly. It returns a promise where React expects a cleanup function. Define the async function inside the effect and call it.",
      "- **D** fetches in the render body, so every render starts another request.",
      "- In real code, C also ignores a response that arrives after unmount: set a flag, or abort with an `AbortController`, in the effect's cleanup.",
      "",
      "## Worth saying out loud",
      "",
      "- In development, React's Strict Mode mounts effects twice on purpose — a correct cleanup makes that harmless.",
      "- Data libraries (React Query, SWR) or a framework's loader handle caching, deduplication and races that a bare effect doesn't.",
    ].join("\n"),
  },
  {
    slug: "react-context-api-quiz",
    title: "Which Statement About React Context Is Correct?",
    category: "frontend",
    difficulty: "easy",
    companies: ["apple"],
    summary: "Context in React 16.3 and later: how it's created and who can read it.",
    prompt: [
      "Which statement about context is correct in React 16.3 and later? Explain why the others are wrong.",
      "",
      "- A. Context can only be accessed in class components, using `this.context`.",
      "- B. A React context is created with `React.createContext()`.",
      "- C. The only way to access context in function components is the `Consumer` component.",
      "- D. Context values must always be primitive data types.",
    ].join("\n"),
    hints: [
      "Think about how a function component reads context today, and what kinds of values a provider can hold.",
    ],
    solution: [
      "## Answer: B",
      "",
      "A is wrong: `useContext` and `Consumer` work outside classes. C is wrong: `useContext` exists. D is wrong: any value works, objects and functions included.",
      "",
      "## Worth saying out loud",
      "",
      "- Context is for values many components need (theme, locale, the signed-in user), not a replacement for props or a state manager.",
      "- A provider value that's a new object on every render re-renders every consumer; memoize it.",
    ].join("\n"),
  },
];
