import type { Problem } from "./types";

// Snowflake system-design prompts, part B: infrastructure services — an ACL
// check, a cloud queue, a cluster control plane, audit logs, and a pipeline
// from bug tickets to generated pull requests.

export const snowflakeDesignProblemsB: Problem[] = [
  {
    slug: "design-acl-check-service",
    title: "Design an ACL Check Service",
    category: "system-design",
    difficulty: "medium",
    companies: ["snowflake"],
    summary: "A durable source of truth for grants, a cache of compiled decisions on the caller's hot path, and a closed fail mode.",
    prompt: [
      "Design an access-control service that other services call on their hot path: `isAllowed(subject, resource, action)`. Subjects belong to groups and roles, which nest; grants attach to resources and to hierarchies of resources.",
      "",
      "The callers care about latency above everything, and about never granting access that was revoked. Cover the source of truth, how a check is answered quickly, how a change to a grant or a group becomes visible, what happens when the store is unreachable, and how every decision can be audited later.",
    ].join("\n"),
    hints: [
      "Keep grants and memberships in a durable store, but answer checks from a cache of compiled rules keyed by (subject, resource): the hot path must not walk the hierarchy.",
      "Change events invalidate affected cache entries; the trade-off is flattening the group and role closure at write time (fast reads, slow invalidation) versus walking the hierarchy per read.",
      "When the store is unreachable, fail closed and say why: a false allow is a security incident, a false deny is an outage with a clear cause.",
    ],
    rubric: [
      "- **Source of truth** — grants, group and role membership in a durable store with versioned changes.",
      "- **Hot-path latency** — a cache of compiled rules keyed by (subject, resource), co-located with or close to the callers, with a measured hit rate target.",
      "- **Invalidation** — change events evict the affected keys; the candidate argues flattening at write time versus walking the hierarchy per read, and picks for the stated read/write ratio.",
      "- **Fail mode** — closed when the store is unreachable, with a short negative-cache TTL so recovery is quick.",
      "- **Audit** — every decision written to an audit log off the request path.",
    ].join("\n"),
    solution: [
      "## Core",
      "",
      "Two stores with different jobs. The durable store holds grants and memberships and is written rarely. The cache holds compiled decisions — for a (subject, resource) pair, the set of allowed actions — and is read on every request. A check is a cache lookup; a miss compiles the answer from the store by expanding the subject's groups and roles and the resource's ancestors, then caches it with a TTL.",
      "",
      "## Invalidation",
      "",
      "Every change to a grant or a membership publishes an event; subscribers evict the cache entries it can affect. Flattening the closure at write time — materialising every (subject, resource) decision a change touches — makes reads trivial and invalidation expensive when a large group changes; walking the hierarchy per read keeps writes cheap and reads slower. Choose by the read/write ratio, and say that a hybrid (flatten for groups below a size, walk for the rest) is common.",
      "",
      "## The trade-off to argue",
      "",
      "Fail closed. When the store is unreachable and the cache has no answer, deny. A false allow is a breach; a false deny is an outage that pages someone and has an obvious cause. Keep a short negative-cache TTL so that recovery does not wait on expiry.",
      "",
      "## Audit",
      "",
      "Write every decision — subject, resource, action, result, rule version — to an append-only log asynchronously. It is off the request path, so latency is unaffected, and it is what an investigation reads later.",
      "",
      "## Probes",
      "",
      "- *A group with a million members changes?* Invalidate by group id, not by member: entries carry the group versions they depended on.",
      "- *Caller cannot tolerate a miss?* Warm the cache from the callers' recent access patterns, and allow a bounded stale answer while a refresh runs.",
    ].join("\n"),
  },
  {
    slug: "design-cloud-queue-service",
    title: "Design a Cloud Queue Service",
    category: "system-design",
    difficulty: "medium",
    companies: ["snowflake"],
    summary: "Start from a Queue class, then make every step survive a client, server or network failure in the middle of it.",
    prompt: [
      "Start from a plain in-memory `Queue` class with `enqueue` and `dequeue`, and turn it into a cloud service that many clients use at once. Then make it correct when a client, a server or the network fails in the middle of an enqueue or a dequeue.",
      "",
      "Define the API, including what a client receives from `dequeue` and how it signals that it has finished with a message; the durability and replication behind an acknowledged enqueue; the visibility rules for a message that has been handed out; and the delivery guarantee you offer and why.",
    ].join("\n"),
    hints: [
      "API: enqueue(queue, message, idempotency_key), dequeue(queue) returning a message plus a receipt, and ack(receipt). Persist and replicate before acknowledging an enqueue.",
      "A dequeue hides the message for a visibility timeout rather than deleting it; no ack before the timeout means redelivery.",
      "At-least-once with consumer-side dedup versus at-most-once: a dequeue whose response is lost looks exactly like a crashed consumer, so redelivery is the only safe answer, and consumers must be idempotent.",
    ],
    rubric: [
      "- **API shape** — enqueue with an idempotency key, dequeue returning a receipt, ack by receipt; a lease rather than a delete.",
      "- **Durability** — an enqueue is acknowledged only after the message is persisted and replicated to a quorum.",
      "- **Visibility timeout** — handed-out messages are hidden, not removed; expiry returns them; the timeout is extendable for long work.",
      "- **Delivery guarantee** — at-least-once with consumer dedup, with the argument for why a lost dequeue response makes exactly-once impossible at this layer.",
      "- **Failure walk-through** — client dies after dequeue, server dies after persist but before reply, network loses the ack: each case named with its outcome.",
    ].join("\n"),
    solution: [
      "## From a class to a service",
      "",
      "```",
      "enqueue(queue, message, idempotency_key) -> message_id",
      "dequeue(queue, visibility_timeout)       -> (message, receipt) or empty",
      "ack(receipt)                             -> ok",
      "```",
      "",
      "The in-memory list becomes a replicated log per queue. An enqueue is persisted and replicated to a quorum before the client hears `ok`; the idempotency key lets a client that lost the response retry without creating a duplicate. A dequeue does not remove the message: it marks it invisible until `visibility_timeout` and returns a receipt. `ack` deletes the message; silence until the timeout returns it to the visible set.",
      "",
      "## The trade-off to argue",
      "",
      "A dequeue whose response is lost on the network is indistinguishable from a consumer that crashed after receiving the message. The service cannot know whether the work happened, so redelivery is the only safe choice: at-least-once delivery, with consumers that deduplicate by message id or make their effects idempotent. At-most-once — delete on dequeue — is simpler and loses messages exactly in the failure the prompt asks about.",
      "",
      "## Failures, one at a time",
      "",
      "- Client dies after dequeue: the lease expires, another consumer gets the message.",
      "- Server dies after persisting an enqueue but before replying: the client retries with the same idempotency key and receives the same message id.",
      "- Network drops an ack: the message is redelivered once; the consumer's dedup drops it.",
      "- A consumer needs longer than the timeout: it extends the lease with the receipt before expiry.",
      "",
      "## Probes",
      "",
      "- *Ordering?* Per-queue FIFO is possible with a single writer per queue; across partitions, only per-key ordering is realistic — say which you offer.",
      "- *Poison messages?* A receive count on each message; past a threshold, move it to a dead-letter queue instead of redelivering forever.",
    ].join("\n"),
  },
  {
    slug: "design-cluster-control-plane",
    title: "Design a Control Plane for Cloud Clusters",
    category: "system-design",
    difficulty: "medium",
    companies: ["snowflake"],
    summary: "Desired state in a consistent store, controllers that reconcile, heartbeating agents, and a failure detector that fences before it replaces.",
    prompt: [
      "Design the control plane that manages a fleet of cloud clusters: users declare clusters and their sizes, the system provisions hosts, keeps each cluster at its desired size, and detects and replaces unhealthy hosts.",
      "",
      "Cover the desired-state model and its store, how the actual state is observed, how the two are reconciled, how host health is judged — and in particular how you separate *the host is dead* from *the control plane cannot reach it* — and what the system does when the control plane itself is partitioned or down.",
    ].join("\n"),
    hints: [
      "Desired state lives in a consistent store; controllers run a reconcile loop that reads desired and actual state and issues the actions that close the gap. Agents on hosts heartbeat and report.",
      "A failure detector marks a host suspect after missed heartbeats and dead after a longer window; the trade-off is detection speed against false positives.",
      "Fence a host — revoke its credentials, detach its volumes, mark it in the store — before launching its replacement, or a host that was only unreachable comes back and runs beside its successor.",
    ],
    rubric: [
      "- **Desired versus actual state** — declared specs in a consistent store, observed state reported by agents, and controllers that reconcile the difference idempotently.",
      "- **Health detection** — heartbeats with suspect and dead thresholds, and the explicit speed-versus-false-positive argument.",
      "- **Partition handling** — *dead* separated from *unreachable*, with fencing before replacement.",
      "- **Control plane failure** — hosts keep running; reconciliation resumes from the store; leadership for controllers is elected, not assumed.",
      "- **Safety rails** — rate limits on replacements and a halt when too many hosts look dead at once, which is almost always a control-plane problem.",
    ].join("\n"),
    solution: [
      "## Core",
      "",
      "Three parts. The **store** holds the desired state — clusters, sizes, host specs — in a consistent database. **Agents** on every host heartbeat to the control plane with their status. **Controllers** run reconcile loops: read desired and actual, compute the difference, issue idempotent actions (provision, drain, terminate), and repeat. Reconciliation is level-triggered, so a missed event costs a loop iteration, not correctness.",
      "",
      "## Health",
      "",
      "The failure detector moves a host through *healthy → suspect → dead* on missed heartbeats. Short windows detect failures fast and flap on a congested network; long windows are calm and slow. Pick thresholds per host class and make them tunable, and treat a cluster-wide loss of heartbeats as a detector problem, not a fleet problem: halt automatic replacement above a threshold.",
      "",
      "## The trade-off to argue",
      "",
      "*The host is dead* and *the control plane cannot reach it* look identical from the outside. Before replacing a host, fence it: revoke its credentials, detach its storage, record the decision in the store. A host that was merely partitioned then cannot rejoin as a live duplicate when the network heals. The cost is a slower replacement; the alternative is two hosts believing they own the same work.",
      "",
      "## When the control plane is down",
      "",
      "Hosts keep serving — the data plane does not depend on the control plane being up. Controllers are stateless apart from leases; a restarted controller re-reads the store and continues. Controller leadership is elected through the store or a coordination service so two controllers never reconcile the same cluster.",
      "",
      "## Probes",
      "",
      "- *Rolling upgrades?* A controller that replaces hosts N at a time, gated on health of the replacements.",
      "- *Scaling decisions?* Metrics feed desired state; the reconciler never guesses, it only closes a declared gap.",
    ].join("\n"),
  },
  {
    slug: "design-audit-log-service",
    title: "Design an Audit Log Service",
    category: "system-design",
    difficulty: "medium",
    companies: ["snowflake"],
    summary:
      "Append-only events partitioned by account then time, a hot store for recent queries, object storage for retention, and tamper evidence per account.",
    prompt: [
      "Design a service that records audit events — who did what, to which resource, when — for many accounts, and answers queries scoped to one account: by time range, actor, resource or action.",
      "",
      "Cover the write path at high volume, the storage layout and how long events are kept, the read path for low-latency account-scoped queries, and how the log resists tampering. Say how much indexing you are willing to pay for on ingest and why.",
    ].join("\n"),
    hints: [
      "Partition by account and then by time: every query is account-scoped, so an account's events sit together and a time range is a contiguous scan.",
      "Keep recent events in a hot store with secondary indexes for the common filters, and age closed time buckets into object storage in a columnar format with per-file min/max metadata.",
      "A hash chain per account — each event carries the hash of the previous — makes deletion or alteration detectable; anchor the chain's head periodically to a write-once location.",
    ],
    rubric: [
      "- **Write path** — producers emit to a log, ingestion batches and writes append-only; no synchronous call on the producer's path.",
      "- **Partitioning** — by account then time, so every query touches one account's data and time ranges are contiguous.",
      "- **Hot and cold tiers** — a hot store with indexes on actor, resource and action for recent data; object storage with pruning metadata for retention; a query planner that fans out across both.",
      "- **Tamper evidence** — a per-account hash chain anchored externally, and append-only permissions on the stores.",
      "- **Indexing trade-off** — the candidate decides how much to index at ingest versus scan at query time and ties it to the query mix.",
    ].join("\n"),
    solution: [
      "## Write path",
      "",
      "Services emit events to a durable log and move on. Ingest workers batch by (account, time bucket), assign monotonically increasing sequence numbers within an account, compute the chain hash, and append to the hot store. Nothing on the producer's request path waits for indexing.",
      "",
      "## Storage",
      "",
      "Partition by account, then by time bucket. The hot tier keeps the last days or weeks with secondary indexes on actor, resource and action, because those are the filters people use. Closed buckets are compacted into columnar files in object storage with per-file min/max statistics on time, actor and resource, which is what lets a query over a year skip almost every file. Retention is a per-account policy applied bucket by bucket.",
      "",
      "## Read path",
      "",
      "A query is account-scoped by construction, so it goes to one partition family. The planner answers from the hot tier when the range is recent, from object storage when it is old, and merges when it straddles. Pagination is by (time, sequence) cursor, which is stable because the data never changes.",
      "",
      "## The trade-off to argue",
      "",
      "A write-optimised log versus query-optimised indexes: every index paid for on ingest speeds one kind of question and slows every write. Index the two or three filters the product actually offers, keep everything else as a scan with pruning, and revisit when query logs show a hot filter.",
      "",
      "## Tamper evidence",
      "",
      "Each event stores the hash of its predecessor in the same account; the head hash is published periodically to a write-once location outside the service. A deleted or altered event breaks the chain at that point. Combine with append-only credentials on the stores so the service itself cannot rewrite history.",
    ].join("\n"),
  },
  {
    slug: "design-ticket-to-pull-request-pipeline",
    title: "Design a Pipeline From Bug Tickets to Generated Pull Requests",
    category: "system-design",
    difficulty: "medium",
    companies: ["snowflake"],
    summary:
      "A ticket becomes a row with a state machine, a queue feeds long-running workers, and every step is idempotent because the AI step will be retried.",
    prompt: [
      "Design a system that watches a bug tracker, and for each eligible bug ticket produces a pull request fixed by an AI coding agent. A fix takes about thirty minutes of agent time; the repository is large; several hundred tickets may arrive in a day.",
      "",
      "Cover how tickets enter the system, the state a ticket moves through, how work is scheduled and bounded, how retries work when the agent step or the Git step fails, and how the system avoids opening two pull requests for one ticket.",
    ].join("\n"),
    hints: [
      "A poller or webhook writes a ticket row; a queue feeds workers; an explicit state machine — NEW, QUEUED, FIXING, PR_OPEN, FAILED — is what makes retries and monitoring sane.",
      "One idempotency key per ticket covers both the agent run and the pull request: a worker checks the state before each expensive step and the branch name derives from the ticket id.",
      "Thirty-minute jobs need a long visibility timeout with heartbeats; the retry policy for the AI step (expensive, non-deterministic) differs from the Git step (cheap, deterministic).",
    ],
    rubric: [
      "- **Ingestion** — webhook with a polling fallback, deduplicated by ticket id into a store that is the source of truth.",
      "- **State machine** — explicit states with the transitions a worker may make, so a crash leaves a ticket in a known place.",
      "- **Scheduling** — a queue with bounded concurrency (agent runs are expensive), long leases with heartbeats for thirty-minute jobs.",
      "- **Idempotency** — one key per ticket, deterministic branch names, and a check-before-act on every side-effecting step so there is never a second PR.",
      "- **Retry policy** — separate policies for the AI step and the Git step, with a dead-letter state and a human in the loop.",
    ].join("\n"),
    solution: [
      "## Flow",
      "",
      "A webhook (polling as fallback) upserts a ticket row keyed by ticket id with state NEW. A scheduler moves eligible tickets to QUEUED and publishes them. A worker claims one, sets FIXING with a lease, runs the agent in an isolated checkout, pushes a branch named from the ticket id, opens the pull request, and sets PR_OPEN with the PR URL. Failures set FAILED with a reason and a retry count.",
      "",
      "```",
      "tickets  ticket_id, state, attempts, lease_expires, branch, pr_url, last_error",
      "```",
      "",
      "## The trade-off to argue",
      "",
      "Polling versus webhooks: webhooks are immediate and can be missed; polling is late and complete. Run both, with the poller as reconciliation. Retries: the AI step is expensive and non-deterministic, so retry it a small number of times with backoff and then stop and ask a human; the Git step is cheap and deterministic, so retry it freely. One policy for both wastes money or gives up too early.",
      "",
      "## Idempotency",
      "",
      "The ticket id is the idempotency key. Before each side effect the worker re-reads the row: if a branch already exists, reuse it; if a PR URL is recorded, the job is done. Branch names are deterministic, so even a lost database write cannot produce a second branch. Visibility timeouts are long and extended by heartbeats, because a thirty-minute job that gets redelivered at ten minutes would otherwise run twice.",
      "",
      "## Scaling",
      "",
      "Bound concurrency by agent capacity, not by ticket volume: a worker pool of fixed size pulls from the queue. Shard the store by ticket id if one tracker cannot hold the rate, and keep the checkout warm per worker so a large repository is not cloned per job.",
      "",
      "## Probes",
      "",
      "- *The agent produces a bad fix?* Tests in the pipeline gate PR_OPEN; failing tests go to FAILED with the diff attached for review.",
      "- *Two workers claim one ticket?* The lease in the row is a compare-and-set; the loser sees the state has moved on.",
    ].join("\n"),
  },
];
