import type { Problem } from "./types";

// Apple front-end bank (the JavaScript interview guide, 2026): the spoken
// knowledge-round questions candidates reported, grouped as the guide
// groups them, each with an answer short enough to say in under a minute.

const HOW_TO_ANSWER =
  "Answer each question out loud in under a minute: a definition, one concrete example, and one pitfall or trade-off. The answers are in the Solution section.";

export const appleConceptProblems: Problem[] = [
  {
    slug: "javascript-language-concepts",
    title: "JavaScript Knowledge Round: Language",
    category: "frontend",
    difficulty: "easy",
    companies: ["apple"],
    summary:
      "Closures, promise states, what ES6 fixed, inheritance against composition, endianness and OO basics, as candidates reported them.",
    prompt: [
      "Spoken questions reported from Apple JavaScript knowledge rounds. " + HOW_TO_ANSWER,
      "",
      "1. What is a closure? *(Blind, two posts; FrontendLead, Apr 2025; an IC3 assessment's topics)*",
      "2. What are the states of a promise? How do `then`, `catch` and `finally` behave? *(Medium, Aug 2025)*",
      "3. What are the best improvements in ES6? *(Glassdoor, Feb 2022)*",
      "4. Inheritance or composition? *(Glassdoor, Jun 2021)*",
      "5. What is endianness? *(Glassdoor, 2018 and 2021)*",
      "6. Name three things object-oriented languages share. *(Glassdoor, Mar 2019)*",
      "",
      "\"How does inheritance work in JavaScript?\" is answered in code in [Inheritance Without class](/problems/inheritance-without-class), and promise sequencing in [Run Promises in Sequence](/problems/run-promises-in-sequence).",
    ].join("\n"),
    hints: [
      "For each concept, have one line of code ready that shows it. For a closure, that is a counter factory.",
      "For \"ES6 improvements\", pick two and say what bug each one removed, rather than listing twelve features.",
    ],
    solution: [
      "## 1. Closures",
      "",
      "A function plus the variables of the scope it was created in. Those bindings stay alive after the outer function returns. **A closure captures the binding, not a snapshot of the value**, which is why a `var` loop counter is shared by every callback while `let` gives each iteration its own. Uses: private state (a counter factory), callbacks, and every utility like `debounce` and `once`.",
      "",
      "## 2. Promise states",
      "",
      "Pending, then fulfilled or rejected, and settled is final: a later `resolve` or `reject` is ignored. `then`, `catch` and `finally` each return a new promise, which is what makes chaining work. Handlers always run as microtasks, never synchronously, even on an already-settled promise. `finally` sees neither the value nor the reason, and passes the original outcome through unless it throws.",
      "",
      "## 3. ES6 improvements",
      "",
      "Block scope with `let` and `const`; arrow functions with lexical `this`; classes; modules; promises; destructuring and spread; template literals; `Map` and `Set`; iterators and generators. Pick two and say what each removed: `let` ended the shared-loop-variable bug, and modules ended global-namespace collisions between scripts.",
      "",
      "## 4. Inheritance or composition",
      "",
      "Inheritance models \"is a\" and ties the child to the parent's implementation, so a change in the base class ripples down. Composition models \"has a\" and combines small parts. Prefer composition when behaviors vary independently. In React, hooks and `children` are composition, which is why class hierarchies of components are rare.",
      "",
      "## 5. Endianness",
      "",
      "The byte order of multi-byte values. Big-endian stores the most significant byte first and is network byte order. x86 and Apple silicon are little-endian. In JavaScript it matters for binary data: typed arrays use the platform's order, while `DataView` defaults to big-endian unless told otherwise.",
      "",
      "## 6. Three things OO languages share",
      "",
      "Encapsulation, inheritance and polymorphism. Add abstraction if a fourth is welcome, and note that JavaScript gets inheritance from prototypes rather than classes.",
    ].join("\n"),
  },
  {
    slug: "browser-rendering-concepts",
    title: "Browser Knowledge Round: DOM, Rendering, and Performance",
    category: "frontend",
    difficulty: "medium",
    companies: ["apple"],
    summary:
      "Event phases, quirks mode, compositing, accessibility, the rendering pipeline, reflow against repaint, Core Web Vitals and keeping the UI responsive.",
    prompt: [
      "Spoken questions reported from Apple front-end rounds about the browser. " + HOW_TO_ANSWER,
      "",
      "## Browser and DOM",
      "",
      "1. What is event bubbling? *(FrontendLead, Apr 2025)*",
      "2. `preventDefault` or `stopPropagation`? *(Medium, 2022)*",
      "3. Why `<!DOCTYPE html>`? What is quirks mode? *(Medium, 2022; GreatFrontEnd's Apple list)*",
      "4. What is a compositing layer in CSS? *(Glassdoor, Feb 2014)*",
      "5. How do you make a page accessible? What accessibility work have you done? *(FrontendLead, Apr 2025; Glassdoor, Feb 2025; Medium, 2022)*",
      "6. How would you implement light and dark themes? *(Medium, 2022)*",
      "7. How do you adjust a border or a margin? What is an API? *(Glassdoor, Mar 2026)*",
      "",
      "## Rendering and performance",
      "",
      "8. Walk through how the browser turns HTML into pixels. *(Two senior rounds, each followed by question 9)*",
      "9. Repaint or reflow? *(Medium, Aug 2025)*",
      "10. What are FCP and LCP? *(Medium, Aug 2025)*",
      "11. How would you debug a blank page? *(Medium, 2022)*",
      "12. How would you make a site faster? *(Medium, 2022, asked in two rounds)*",
      "13. How do you deal with a slow API? *(Medium, 2022)*",
      "14. A heavy calculation over sales data freezes a React UI. What do you do? And without a worker? *(Medium, Aug 2025)*",
    ].join("\n"),
    hints: [
      "Questions 8 and 9 come as a pair. Learn the pipeline as six numbered steps, and answer 9 by naming which steps each kind of change re-runs.",
      "For performance questions, start with \"measure first\" and name the tool (the Performance panel, Lighthouse, real-user metrics) before listing fixes.",
    ],
    solution: [
      "## 1. Event bubbling",
      "",
      "An event travels in three phases: capture down from `window`, the target, then bubble back up. Listeners run in the bubble phase unless registered with `{ capture: true }`. Event delegation, one listener on a parent that handles events for its children, depends on bubbling. `focus`, `blur`, `mouseenter` and `mouseleave` do not bubble; `focusin` and `focusout` are their bubbling twins.",
      "",
      "## 2. `preventDefault` or `stopPropagation`",
      "",
      "`preventDefault` cancels the browser's default action, such as following a link or submitting a form, and the event still propagates. `stopPropagation` stops the event reaching further elements, and the default action still happens. **`stopImmediatePropagation` also skips the remaining listeners on the same element**, which was the follow-up.",
      "",
      "## 3. The doctype and quirks mode",
      "",
      "The doctype selects standards mode. Without it, browsers use quirks mode, which emulates 1990s layout behavior: unitless CSS lengths are accepted, and tables don't inherit the font size, for example. A third mode, limited quirks, comes from a few old doctypes.",
      "",
      "## 4. A compositing layer",
      "",
      "A part of the page painted into its own GPU texture. `transform`, `opacity` and `will-change` promote an element. The compositor can then move or fade it without layout or paint, which is why those two properties animate smoothly. Each layer costs memory, so promote sparingly.",
      "",
      "## 5. Accessibility",
      "",
      "Native elements first, since they bring role, focus and keyboard behavior for free. Then: a text name for every control, full keyboard operation with a visible focus ring, contrast of at least 4.5 to 1 for body text, `prefers-reduced-motion`, and ARIA only where no native element exists. Say you test with VoiceOver, and bring a real example of something you fixed.",
      "",
      "## 6. Light and dark themes",
      "",
      "Colors as CSS custom properties on the root. Follow `prefers-color-scheme` by default, and let a `data-theme` attribute on `<html>` override it. Store the choice, and set the attribute from an inline script in `<head>`, so the wrong theme never flashes before the stylesheet applies.",
      "",
      "## 7. Borders, margins, and \"what is an API\"",
      "",
      "The box model from the inside out: content, padding, border, margin. `box-sizing: border-box` makes `width` include the padding and border, which is why most resets set it everywhere. An API is a contract for how one piece of software calls another: the operations, their inputs and outputs, and the errors.",
      "",
      "## 8. From HTML to pixels",
      "",
      "1. **Parse HTML into the DOM.** A plain `<script>` pauses the parser; `defer` and `async` do not.",
      "2. **Parse CSS into the CSSOM.** CSS blocks rendering, and it also blocks any script that follows it.",
      "3. **Build the render tree** from the visible nodes and their computed styles. `display: none` nodes are left out.",
      "4. **Layout**, also called reflow: compute every box's size and position.",
      "5. **Paint** pixels into layers.",
      "6. **Composite** the layers on the GPU.",
      "",
      "## 9. Repaint or reflow",
      "",
      "A geometry change (size, position, font, adding nodes) re-runs steps 4 to 6. A visual-only change, such as a color, re-runs 5 and 6. `transform` and `opacity` re-run only step 6. Reading `offsetHeight` after a write forces layout immediately, and alternating reads and writes in a loop is layout thrashing: batch the reads, then the writes.",
      "",
      "## 10. FCP and LCP",
      "",
      "First Contentful Paint is when the first text or image appears; 1.8 s or less is good. Largest Contentful Paint is when the largest image or text block in the viewport appears; 2.5 s or less is good. LCP is one of the three Core Web Vitals, with Interaction to Next Paint and Cumulative Layout Shift.",
      "",
      "## 11. A blank page",
      "",
      "Console first, for a thrown error. Then the network tab: did the HTML, the bundle and the API calls return 200 with the right content type? Then the DOM: is the root element empty, or is content present but hidden by CSS? Then bisect recent deploys.",
      "",
      "## 12. Making a site faster",
      "",
      "Measure first. Then ship less: code-split, tree-shake, compress, and use modern image formats. Unblock rendering: `defer` scripts, inline critical CSS, and lazy-load below the fold. Cache: hashed filenames with a long `max-age`, and never cache the HTML. Move work: a CDN, server rendering, and parallel API calls instead of a waterfall.",
      "",
      "## 13. A slow API",
      "",
      "Show the page shell with a skeleton at once. Cache and revalidate, paginate, request in parallel, and cancel stale requests with `AbortController`. Then fix the cause on the server, because the client can only hide latency.",
      "",
      "## 14. A heavy calculation that freezes the UI",
      "",
      "Move it to a Web Worker, pass the data with `postMessage` (or transfer an `ArrayBuffer` to avoid copying), and terminate the worker in the effect's cleanup. The follow-up was \"and without a worker?\": split the work into chunks and yield to the event loop between them. The candidate's answer named `setImmediate`, which browsers don't have, and `requestIdleCallback`, which Safari did not enable by default as of 18.1. Feature-detect, and fall back to `setTimeout`. `useDeferredValue` keeps typing responsive while React renders the expensive result.",
    ].join("\n"),
  },
  {
    slug: "web-security-and-tooling-concepts",
    title: "Web Knowledge Round: Security, Storage, and Tooling",
    category: "frontend",
    difficulty: "medium",
    companies: ["apple"],
    summary:
      "CORS, cookies against Web Storage, securing a site, fetch against Axios, GraphQL, packaging, code review, Jest and when hooks memoize.",
    prompt: [
      "Spoken questions reported from Apple front-end rounds about the network, security and day-to-day practice. " + HOW_TO_ANSWER,
      "",
      "## Network, security and storage",
      "",
      "1. What is CORS? *(Medium, 2022; LeetCode, Jun 2025)*",
      "2. Cookies, `localStorage` or `sessionStorage`? *(Medium, 2022; GreatFrontEnd's Apple list)*",
      "3. How do you secure a site: HTTPS, CSP, cookies? *(LeetCode, Jun 2025; Glassdoor, Aug 2020 and Mar 2026)*",
      "4. Axios or `fetch`? *(Medium, Aug 2025)*",
      "5. What do you think of GraphQL? *(A senior front-end round in Europe, late 2025)*",
      "",
      "## Tooling and practice",
      "",
      "6. How do you build an npm package? *(Glassdoor, Dec 2019)*",
      "7. What makes a good code review? *(Medium, 2022)*",
      "8. How would you structure a repo from scratch? *(Glassdoor, Aug 2021)*",
      "9. Have you used Jest? *(Glassdoor, Oct 2023)*",
      "10. What is your relationship with React hooks? When would you use `useMemo` or `useCallback`? *(Glassdoor, Aug 2025; Medium, 2025)*",
    ].join("\n"),
    hints: [
      "For the security questions, name the attack each measure stops: HTTPS stops eavesdropping, CSP limits XSS, and `SameSite` with CSRF tokens stops cross-site request forgery.",
      "For the practice questions, answer from your own work first, then generalize.",
    ],
    solution: [
      "## 1. CORS",
      "",
      "Browsers block a page from reading responses from another origin (scheme, host and port) unless the server opts in with `Access-Control-Allow-Origin`. Requests that are not \"simple\" trigger an `OPTIONS` preflight first. With credentials, the origin must be named exactly, and a wildcard is refused. CORS protects users, not servers: any non-browser client can still call the API.",
      "",
      "## 2. Cookies against Web Storage",
      "",
      "Cookies are sent automatically with every matching request, hold about 4 KB each, and can expire. `localStorage` holds about 5 MB per origin, is never sent, and is synchronous. `sessionStorage` has the same API, but belongs to one tab and is cleared when the tab closes. **The security difference is the point:** an `HttpOnly` cookie can't be read by script, so a session token in one survives XSS, and anything in `localStorage` does not.",
      "",
      "## 3. Securing a site",
      "",
      "HTTPS everywhere, with HSTS. A Content Security Policy that allows scripts only from named sources or nonces limits XSS. Session cookies get `Secure`, `HttpOnly` and `SameSite`, plus CSRF tokens on state-changing requests. Escape output by default (React does for text), and never pass user input to `innerHTML`.",
      "",
      "## 4. Axios or `fetch`",
      "",
      "`fetch` is built in, but **it resolves on a 404 or a 500**, so check `res.ok`. It needs `AbortSignal.timeout` for timeouts. Axios rejects on error statuses, parses JSON and has interceptors, at the cost of a dependency. Its cancel tokens are deprecated in favor of `AbortController`, which both now share.",
      "",
      "## 5. GraphQL",
      "",
      "One round trip and no over-fetching for nested UI data, with a typed schema. In exchange: HTTP caching is harder, query cost must be limited on the server, and N+1 resolvers need batching. It pays off with many clients and deep data, less so for simple CRUD.",
      "",
      "## 6. Building an npm package",
      "",
      "`package.json` with `name`, `version`, `exports`, `types` and a `files` allow-list. Build to ESM, plus CommonJS if consumers need it, with type declarations. Frameworks go in `peerDependencies`. Check the contents with `npm pack --dry-run`, then `npm publish`, and bump by semver.",
      "",
      "## 7. A good code review",
      "",
      "Correctness and edge cases first, then readability and naming, tests, and consistency with the codebase. Small diffs, specific comments, and a clear split between blocking issues and preferences.",
      "",
      "## 8. Structuring a repo from scratch",
      "",
      "Group by feature, not by file type. Shared UI and utilities get their own folders, tests sit beside the code, and lint, format, type-check and test are wired into CI from the first commit.",
      "",
      "## 9. Jest",
      "",
      "Be ready to name what you test with it: pure functions, component behavior through Testing Library, and timers with fake timers, which is how you would test `debounce` without waiting.",
      "",
      "## 10. `useMemo` and `useCallback`",
      "",
      "`useMemo` caches a computed value, and `useCallback` caches a function's identity. Both matter only when the result feeds a memoized child, a dependency array, or a costly calculation. Used everywhere, they add cost and noise, and the React Compiler increasingly applies them automatically.",
    ].join("\n"),
  },
];
