import type { Problem } from "./types";

// Apple system-design prompts reported for Software Engineer loops (PracHub's
// Apple list, 2025–2026), part F: the smartwatch sensing subsystem and the
// wallet monolith-to-microservices migration. Prompts are restated in our own
// words; the smartwatch prompt is reconstructed from its published overview.

export const appleDesignProblemsF: Problem[] = [
  {
    slug: "design-smartwatch-sensor-subsystem",
    title: "Design a Smartwatch Sensor Subsystem",
    category: "system-design",
    difficulty: "hard",
    companies: ["apple"],
    summary:
      "Heart rate on a moving wrist inside a milliwatt budget: sensor choice, a sensor hub, motion-artifact rejection, and proof it works on everyone.",
    prompt: [
      "Design the sensing subsystem of a smartwatch that measures heart rate and activity all day and during workouts. This is a system-level question that spans hardware, firmware and algorithms rather than a distributed-systems one.",
      "",
      "Constraints: the watch has a battery of roughly 1 Wh that must last well over a day, so continuous sensing gets a budget of a few milliwatts on average; the sensor window on the back is a few square centimetres; and readings must hold up on a moving, sweating wrist across skin tones, ages, tattoos, cold weather and loose straps. A wrong heart rate shown confidently is worse than no reading.",
      "",
      "Cover: which sensors you choose and why; the trade-offs among accuracy, power, size and reliability; the architecture from sensor to application processor; the signal processing and how it stays robust; how hardware and firmware are integrated and calibrated; how you validate and debug the system; and how you work with component suppliers on quality.",
      "",
      "*Reported as: a smartwatch sensor subsystem design covering sensor selection, trade-offs, signal processing, hardware–firmware integration, validation and supplier quality (PracHub, Apple Software Engineer onsite, Feb 2026). The original prompt is not public; this version is reconstructed from its overview.*",
    ].join("\n"),
    hints: [
      "Optical heart rate (PPG) is dominated by LED power and corrupted by motion. Those two facts drive everything: adaptive LED current and sampling rate for the power budget, and an accelerometer sampled on the same clock as the noise reference for artifact rejection.",
      "Keep the application processor asleep. An always-on low-power sensor hub samples, buffers in hardware FIFOs, runs the first stage of signal processing, and wakes the main processor only in batches or on events.",
      "Output a confidence with every reading, and define validation before you build: reference devices, a participant matrix that covers skin tone and activity, recorded raw datasets you can replay through every new firmware build.",
    ],
    rubric: [
      "- **Sensor selection with reasons** — optical PPG with wavelength choices tied to use (green for motion, infrared for low-power background, red and infrared for oxygen), photodiode layout, an analog front end, an always-on accelerometer, a duty-cycled gyroscope, and optional sensors justified by a feature.",
      "- **Trade-offs quantified** — a power budget derived from battery capacity and target life, the LED as the dominant consumer, sampling-rate and duty-cycle modes, and the size and mechanical factors (LED–detector spacing, light leakage, strap coupling) that affect signal quality.",
      "- **Architecture** — sensor hub or coprocessor, FIFOs and batching, a shared timestamp domain across sensors, defined power modes, and minimal wake-ups of the application processor.",
      "- **Signal processing and robustness** — filtering, motion-artifact cancellation with the accelerometer as reference, frequency tracking that avoids locking onto step cadence, automatic gain control, on-wrist detection, and a signal-quality index that suppresses low-confidence output.",
      "- **Hardware–firmware integration** — bring-up and drivers, timing and jitter, FIFO overflow handling, per-unit factory calibration stored on the device, self-test, fault recovery and safe firmware update.",
      "- **Validation, debugging and supplier quality** — bench and human studies against reference devices across a participant matrix with stated metrics, replayable raw datasets as regression tests, raw-capture debug modes and field telemetry, plus component binning, incoming inspection, change control and failure analysis with suppliers.",
    ].join("\n"),
    solution: [
      "## Requirements and the budget",
      "",
      "Features: background heart rate all day, high-rate heart rate during workouts, steps and activity classification, sleep. Accuracy target: within ±5 beats per minute of an ECG chest strap for ~90% of workout time, and **coverage** — the fraction of time a valid reading exists — reported alongside it. Power: a ~300 mAh cell at 3.8 V is ~1.1 Wh; lasting 36 hours means ~30 mW average for the whole watch, so sensing gets perhaps 5–10% of that: **2–3 mW average**. Everything below is shaped by that number.",
      "",
      "## Sensors",
      "",
      "- **Optical heart rate (PPG):** green LEDs for workouts — haemoglobin absorbs green strongly and the shallow path is less sensitive to motion; infrared for background and sleep — lower power and invisible at night; red plus infrared if blood oxygen is a feature. Several photodiodes around the emitters give spatial diversity, so one poorly coupled detector does not lose the signal.",
      "- **Analog front end:** LED drivers with programmable current, a transimpedance amplifier, ambient-light cancellation and a high-resolution converter. The pulsatile component is often under 1% of the detected light, so dynamic range matters more than raw sensitivity.",
      "- **Accelerometer:** always on at 25–50 Hz for tens of microwatts; it counts steps, classifies activity, detects wrist raise, and is the noise reference for the optical signal.",
      "- **Gyroscope:** around a milliwatt, so it is duty-cycled and enabled only when a workout type needs orientation.",
      "- **Extras justified by a feature:** skin temperature, barometer, ECG electrodes. Each one must earn its area, power and test cost.",
      "",
      "## Trade-offs",
      "",
      "The LED dominates power, so accuracy is bought with current and sampling rate. Use modes: *background* — infrared at ~25 Hz, in short bursts every few minutes while the accelerometer says the wrist is still; *workout* — green at 100 Hz or more, continuously; *spot check* — highest quality for a short time. **Automatic gain control** raises LED current only as far as needed for a target signal-to-noise ratio, which also adapts to darker skin, tattoos and low perfusion in the cold instead of failing on them.",
      "",
      "Size and mechanics are part of the signal chain: wider LED–detector spacing probes deeper tissue but needs more light; optical barriers stop light leaking directly from emitter to detector; the curvature of the back crystal and the strap design decide how well the sensor stays coupled to skin. Reliability means sealed optics, scratch-resistant windows, and LED ageing allowances.",
      "",
      "## Architecture",
      "",
      "Sensors → analog front end → an always-on **sensor hub** (a low-power microcontroller or coprocessor) → application processor. The hub configures the sensors, drains their hardware FIFOs over SPI or I2C with DMA, runs filtering and the first-stage algorithms, and wakes the application processor only for a batch of results or a significant event. The application processor, which costs tens of milliwatts awake, stays asleep almost all the time.",
      "",
      "All sensors are timestamped in **one clock domain**. Motion-artifact cancellation subtracts what the accelerometer saw at the same instant; a few milliseconds of skew between the two streams visibly degrades it.",
      "",
      "## Signal processing",
      "",
      "1. Band-pass the optical signal to the plausible heart-rate band (about 0.5–4 Hz).",
      "2. **Motion-artifact rejection:** an adaptive filter, or spectral subtraction, using the accelerometer axes as the noise reference.",
      "3. Spectral peak estimation with a **tracker** (a Kalman or particle filter) that carries heart rate forward smoothly, so the estimate does not jump onto running cadence when cadence and pulse are close.",
      "4. A **signal-quality index** from signal-to-noise ratio, agreement between detectors and template consistency. Low quality suppresses the reading.",
      "5. On-wrist detection from infrared proximity so the watch never reports the pulse of a table.",
      "",
      "Showing a gap is a feature: a confident wrong number destroys trust faster than a missing one.",
      "",
      "## Hardware–firmware integration",
      "",
      "Bring up each device with register-level drivers and known-good captures before any algorithm work. Watch the unglamorous failure modes: sampling jitter, FIFO overflow when the hub is busy, interrupt latency, bus contention. Every unit is **calibrated at the factory** against an optical reference — LED output, detector responsivity, accelerometer offsets — and the constants are stored in non-volatile memory. Firmware includes self-test, a watchdog with sensor reset and re-initialisation, and updates with rollback.",
      "",
      "## Validation",
      "",
      "- **Bench:** optical phantoms with a programmable pulse, shaker tables for the inertial sensors, temperature and humidity chambers, water ingress.",
      "- **Human studies:** a participant matrix across Fitzpatrick skin types I–VI, age, body mass, wrist size, tattoos and hair; protocols from rest through walking, running, cycling, intervals and swimming; ECG chest strap and clinical oximeter as references.",
      "- **Metrics:** mean absolute error, percentage within ±5 bpm, Bland–Altman agreement, coverage — each reported per subgroup, because an average hides the people it fails.",
      "- **Replay:** raw captures from these studies become golden datasets, and every firmware or algorithm build is replayed against them in continuous integration, so a regression is caught before a wrist ever sees it.",
      "",
      "## Debugging",
      "",
      "Provide a raw-capture mode that streams unprocessed samples with timestamps, plus on-device traces of mode changes, gain settings and quality scores. To separate hardware, firmware and algorithm faults: look at the raw waveform first, swap the unit, replay the capture offline through the algorithm, then bisect firmware. Opt-in field telemetry reports quality statistics, not health data.",
      "",
      "## Supplier quality",
      "",
      "LED wavelength and detector responsivity vary by lot, so specify bins, inspect incoming parts, and qualify a second source. Build quality gates into engineering, design and production validation builds; check the calibration station itself with gauge repeatability studies; require change notices for any process change; and run a closed failure-analysis loop on returns, feeding findings back into both the supplier's process and the firmware's tolerance.",
      "",
      "## Probes to expect",
      "",
      "- *Halve the power?* Lower the background sampling duty cycle, gate sampling on stillness, lean on infrared, and accept lower coverage — state the accuracy you give up.",
      "- *It fails on one skin tone in the study?* Check gain-control headroom and LED current limits first, then detector saturation and algorithm thresholds tuned on an unrepresentative dataset.",
    ].join("\n"),
  },
  {
    slug: "design-wallet-monolith-migration",
    title: "Migrate a Monolithic Wallet to Microservices",
    category: "system-design",
    difficulty: "hard",
    companies: ["apple"],
    summary:
      "Strangle the monolith in phases, keep money movement inside one ledger's transaction, and use sagas only around the outside world.",
    prompt: [
      "You run a high-scale consumer digital wallet with person-to-person payments — in the shape of Apple Cash — built as a monolith with one database. Plan its migration to microservices.",
      "",
      "Define the service boundaries (for example identity and KYC, wallet, ledger, payments orchestration, risk and fraud, notifications); who owns which data and how it is migrated; API design and idempotency; how transactions that cross services work, and whether you would use sagas or two-phase commit; consistency and reconciliation; authentication and authorisation; PCI and PII compliance; observability; and the rollout strategy, including strangler routing, canaries and rollback.",
      "",
      "Finish with a phased plan, the key risks, and the metrics that tell you the migration succeeded.",
      "",
      "*Reported as: migrating a monolithic digital wallet to microservices (PracHub, Apple Software Engineer technical screen, Sep 2025).*",
    ].join("\n"),
    hints: [
      "Draw boundaries around data ownership and rate of change, not around nouns. The ledger — immutable double-entry postings — is the one place money truth lives; everything else holds references to it.",
      "A transfer between two wallets is a single atomic posting inside the ledger service, so it needs no distributed transaction. Sagas are for the legs that touch the outside world: card funding, bank cash-out.",
      "Never dual-write money. Feed the new ledger from the monolith's change stream in shadow, reconcile until the books match continuously, then flip the writer per cohort behind a routing layer that can flip back.",
    ],
    rubric: [
      "- **Service boundaries and data ownership** — boundaries justified by ownership, compliance scope and change rate; one owner per dataset, no shared database; the ledger as the money source of truth with balances derived from postings.",
      "- **Migration mechanics** — a strangler facade in front of the monolith, extraction order from low to high risk, backfill plus change data capture instead of dual writes, shadow mode with continuous reconciliation, cohort cutover and a rehearsed rollback.",
      "- **APIs and idempotency** — idempotency keys on every mutating call with stored outcomes, transaction ids carried end to end, versioned contracts with consumer-driven tests.",
      "- **Cross-service transactions** — a reasoned saga-versus-two-phase-commit answer: money movement kept inside one ACID boundary, orchestrated sagas with compensations and explicit pending states for external legs, outbox for reliable events.",
      "- **Consistency, reconciliation and compliance** — ledger invariants, reconciliation against processor and bank files, PCI scope minimised with a tokenisation vault, field-level PII encryption and key management, strong service-to-service identity and user step-up authentication.",
      "- **Observability, rollout and success criteria** — tracing keyed by transaction id, service-level objectives, canary and automated rollback, expand-and-contract schema changes, named risks, and measurable success metrics.",
    ].join("\n"),
    solution: [
      "## Why migrate, and what must not change",
      "",
      "State the goals first, because they decide the order: independent deploys for teams that block each other, isolation of compliance scope, and scaling the payment path separately from everything else. The invariant throughout: **no customer's balance is ever wrong, and no payment is lost or duplicated.** A migration that improves deploy frequency and loses a cent has failed.",
      "",
      "## Service boundaries",
      "",
      "| Service | Owns | Notes |",
      "|---|---|---|",
      "| Identity and KYC | customers, verification status, documents | heaviest PII; its own compliance scope |",
      "| Ledger | accounts, immutable double-entry postings, holds | the only source of truth for money |",
      "| Wallet | user-facing wallet state, limits, balance read model | balance is a projection of the ledger |",
      "| Payments orchestration | payment intents and their state machines | drives sagas; holds no money state |",
      "| Funding and payout | card and bank integrations | talks to processors and banks |",
      "| Card vault | card numbers and tokens | the only service in PCI scope |",
      "| Risk and fraud | decisions, signals, models | synchronous decision plus asynchronous learning |",
      "| Notifications | templates, delivery state | lowest risk |",
      "",
      "Each dataset has exactly one owner and no service reads another's tables. The test for a boundary: can this team change its schema without a meeting?",
      "",
      "## Cross-service transactions: saga or two-phase commit?",
      "",
      "Two-phase commit across services couples their availability, holds locks across the network, and is not offered by card networks or banks anyway. But the more useful answer is to **need fewer distributed transactions**. A transfer from Ann to Bob is one posting with two entries — debit Ann, credit Bob — inside the ledger's own ACID transaction. No saga is required for the money itself.",
      "",
      "Sagas handle the legs that leave the building, with an orchestrator and explicit pending states:",
      "",
      "- **Add money from a card:** risk check → authorise with the processor → capture → post credit to the ledger. Compensation: void or refund; the ledger entry is reversed by a new opposite entry, never edited.",
      "- **Cash out to a bank:** place a **hold** in the ledger → submit the transfer → on settlement convert the hold to a debit; on a return, release it.",
      "",
      "Every step is idempotent and keyed by the payment id, state changes and their events are written together through an **outbox**, and the orchestrator can resume any saga after a crash from its recorded state.",
      "",
      "## APIs and idempotency",
      "",
      "Every mutating endpoint requires an `Idempotency-Key`; the service stores `(caller, key) → outcome` and returns the stored outcome on a retry, with a conflict if the same key arrives with a different body. A transaction id created at the edge travels through every call, log line and ledger posting. Contracts are versioned and verified by consumer-driven tests, so the monolith and the new services can evolve independently during the long coexistence.",
      "",
      "## Data migration without dual writes",
      "",
      "Dual writes from application code are how books diverge — one write succeeds, one fails, and nobody knows. Instead, for each extracted dataset:",
      "",
      "1. **Backfill** history into the new service.",
      "2. Stream ongoing changes from the monolith's database with **change data capture**, so the new store follows in near real time.",
      "3. Run in **shadow**: the new service computes answers that are compared with the monolith's but not used. For the ledger that means continuous reconciliation — per-account balances, entry counts, and the invariant that all postings sum to zero.",
      "4. **Flip the writer** per cohort — employees, 1%, one region, everyone — through the routing layer. The monolith now calls the service instead of its tables.",
      "5. Keep a reverse feed for a rollback window, then remove the old tables.",
      "",
      "## Phased plan",
      "",
      "- **Phase 0 — foundations:** a facade or gateway in front of the monolith (the strangler routing point), tracing, deployment pipeline, service identity, idempotency keys added inside the monolith, and clear module boundaries in the existing code.",
      "- **Phase 1 — notifications:** low risk, proves the platform.",
      "- **Phase 2 — identity and KYC, and the card vault:** shrinks PII and PCI scope early, which is a compliance win by itself.",
      "- **Phase 3 — risk:** run in shadow and compare decisions before it becomes authoritative.",
      "- **Phase 4 — the ledger:** the critical step, using the shadow-and-reconcile sequence above.",
      "- **Phase 5 — payments orchestration and funding:** last, because they depend on everything else.",
      "- **Phase 6 — decommission** and delete dead paths.",
      "",
      "## Consistency and reconciliation",
      "",
      "The ledger is strongly consistent per account, sharded by account, with transfers across shards handled by the database's distributed transactions or a hold-then-post pattern. Wallet balances are a read model rebuilt from postings. Daily reconciliation matches ledger totals against processor settlement files and bank statements; breaks open tickets with tooling to investigate, and the break count is a top-level metric.",
      "",
      "## Security and compliance",
      "",
      "Users authenticate with OpenID Connect and device-bound credentials, with step-up authentication for risky actions. Services authenticate each other with mutual TLS and workload identities, and authorise with narrow scopes — nothing is trusted because of where it runs. Card numbers exist only in the vault; everyone else holds tokens, which removes them from PCI scope. PII is encrypted per field with keys in a managed key service or hardware module, rotated, with access logged. Logs and traces carry ids, never PII or card data.",
      "",
      "## Observability and rollout",
      "",
      "Distributed tracing keyed by transaction id; service-level objectives per service with error budgets; business metrics — payment success rate, time to complete, reconciliation breaks — on the same dashboards as latency. Every cutover is a **canary** with automated rollback on budget burn, schema changes follow expand-then-contract, and rollback is rehearsed in game days rather than assumed.",
      "",
      "## Risks",
      "",
      "- A **distributed monolith**: services that must deploy together or chat synchronously on every request, multiplying latency and failure.",
      "- Divergent books during ledger coexistence.",
      "- Compliance scope spreading because a token was logged or a field copied.",
      "- The migration stalling half way, leaving two systems to operate indefinitely.",
      "",
      "## Success metrics",
      "",
      "Reconciliation breaks at zero through every cutover; payment success rate and p99 latency no worse than the baseline; deploy frequency and lead time per team up; incident count and time to restore down; percentage of traffic on new services; size of PCI and PII scope reduced; monolith code and tables deleted.",
      "",
      "## Probes to expect",
      "",
      "- *Why not rewrite and switch over?* A big-bang cutover of a money system has no partial rollback; the strangler gives a reversible step at every stage.",
      "- *Exactly-once payments?* At-least-once delivery plus idempotent handlers and a unique constraint on the transaction id gives an exactly-once effect.",
    ].join("\n"),
  },
];
