import type { Problem } from "./types";

// Apple design-lite prompts reported inside technical phone screens: the
// 200 TB media migration (AI/ML full-stack) and the voice-only ML-evaluation
// platform design. Each carries the reported wording, a rubric for the AI
// design review, and a worked answer. Same sourcing as seed-apple-a.ts.

export const appleDesignProblems: Problem[] = [
  {
    slug: "design-media-migration-gpu-pipeline",
    title: "200 TB Media Migration, Then Feed the GPUs",
    category: "system-design",
    difficulty: "hard",
    companies: ["apple"],
    summary:
      "Do the bandwidth arithmetic out loud, land in object storage, and never let the GPUs read small files.",
    prompt: [
      "> \"You have 200 TB of media data — images and video — and you need to get it onto the compute hosts that will preprocess, run inference, and train on it. How would you design that?\"",
      "",
      "Reported for an Apple AI/ML full-stack role, open-ended, with the interviewer explicitly crediting the clarifying questions. A 200 TB media-migration design also appears in an independent Apple question list.",
      "",
      "Cover: the questions you would ask first; the transfer arithmetic and the network-versus-shipping decision; where the data lands and why; how the transfer survives failure; and the follow-up that always comes — how the training and inference hosts consume the data without starving the GPUs. Assume the interviewer will ask what changes if the transfer becomes recurring.",
    ].join("\n"),
    hints: [
      "200 TB is 1.6 × 10^15 bits: about 18.5 days at 1 Gbps, 1.85 days at 10 Gbps, 4.4 hours at 100 Gbps — and roughly 40% worse at a realistic 70% of line rate. When the transfer takes longer than shipping disks, ship the disks.",
      "The data does not go onto a processing host's local disk. It lands in object storage, which decouples transfer from consumption, survives a resumed upload, and can be read by the whole cluster.",
      "Millions of small files are a metadata and IOPS problem, not a bandwidth one — preprocess offline into large sharded archives so training reads are sequential, and stream shards with prefetch instead of staging 200 TB locally.",
    ],
    rubric: [
      "- **Clarifying questions first** — one-time or recurring; source location and whether a private link exists; available bandwidth; deadline; one host or a cluster; millions of small files or a few large ones. Asked before designing, not after.",
      "- **Transfer arithmetic** — converts 200 TB to bits, computes time at 1 / 10 / 100 Gbps, discounts to a realistic fraction of line rate, and states the ship-the-disks threshold. Numbers that appear but do not drive the decision score low.",
      "- **Landing zone** — data lands in object storage rather than a host's local disk, with the reason: decoupling transfer from consumption, resumability, cluster-wide reads.",
      "- **Transfer mechanics** — chunked, parallel streams to fill a fat link; per-chunk checksums so a failure retransmits one chunk; encryption in transit and at rest; idempotent resume.",
      "- **Feeding the GPUs** — preprocesses small files into large sharded archives (WebDataset / TFRecord), streams shards with prefetch, overlaps decode with compute across workers, uses a shuffle buffer rather than a global shuffle, and names which resource to profile first.",
      "- **From migration to pipeline** — for the recurring case, object-storage event notifications into a queue with workers autoscaled on queue depth; says what monitoring and backfill look like.",
    ].join("\n"),
    solution: [
      "## Clarify, then do the arithmetic out loud",
      "",
      "Ask, in this order: one-time or recurring? Where is the source, and is there a private link or only the public internet? What bandwidth? What is the deadline? One host or a cluster? Millions of small files or a few large ones — because small files are a metadata and IOPS problem, not a bandwidth one.",
      "",
      "Then the calculation that is the whole differentiator. 200 TB is 1.6 × 10^15 bits.",
      "",
      "| Link | Ideal time | At ~70% of line rate | Verdict |",
      "|---|---|---|---|",
      "| 1 Gbps | 18.5 days | 26 days | Ship physical appliances |",
      "| 10 Gbps | 1.9 days | 2.6 days | Network is viable |",
      "| 100 Gbps | 4.4 hours | 6.3 hours | Network is clearly best |",
      "",
      "The rule you state next: when the transfer takes longer than shipping disks, ship the disks.",
      "",
      "## Landing zone",
      "",
      "The point almost certainly being scored: the data does not go onto a processing host's local disk. It lands in object storage — a **landing zone** — which decouples transfer from consumption, survives a resumed upload, and can be read by the whole cluster. Keep a manifest (path, size, checksum, status) so the transfer is idempotent and auditable.",
      "",
      "## Network path",
      "",
      "Chunk the files and run many parallel streams, because a single TCP stream is RTT-limited and will not fill a fat link. Per-chunk checksums so a failure retransmits one chunk, not the file. Jumbo frames on a private link. TLS in transit, KMS-managed keys at rest. Resume from the manifest after any interruption.",
      "",
      "## Feeding the GPUs",
      "",
      "The AI/ML follow-up that always comes: do not let the GPUs starve. Never read millions of small files at train time — preprocess offline into large sharded archives (WebDataset tar shards, TFRecord) to turn random reads into sequential ones. Stream shards from object storage with prefetch instead of staging 200 TB locally. Overlap decode with compute across worker processes. Use a shuffle buffer rather than a global shuffle. Then say which resource you would profile first — storage throughput, decode CPU, or PCIe — to find the bottleneck.",
      "",
      "## If it becomes recurring",
      "",
      "Object-storage event notifications into a queue, workers consuming from it, autoscaled on queue depth. That is the step from a migration to a pipeline, and it is the answer to \"what if this runs every day?\" Add dead-letter handling for corrupt media and a backfill path keyed by the manifest.",
      "",
      "## Worth saying out loud",
      "",
      "- Two or three clarifying questions, then commit: the reported interviewer credited the clarifying step, and endless clarifying reads as stalling.",
      "- Give the bandwidth numbers before being asked; the arithmetic is the signal.",
      "- \"Landing zone\" and \"sharded archives\" are the two phrases that show you have done this rather than read about it.",
    ].join("\n"),
  },
  {
    slug: "design-ml-evaluation-platform",
    title: "Design an ML Evaluation Platform, Out Loud",
    category: "system-design",
    difficulty: "hard",
    companies: ["apple"],
    summary:
      "A voice-only design round: a fixed spoken structure, versioned benchmarks, cached (model, item) runs, and confidence intervals.",
    prompt: [
      "Two reported Apple technical phone screens had no coding at all. One, with a senior engineer on ML Infrastructure, was a verbal discussion of designing an ML infrastructure system; another, with a senior manager, was a feed design conducted as a voice call with no whiteboard and no CoderPad.",
      "",
      "Design the evaluation platform for an AIML organisation: it runs benchmarks across many model versions, scores results with both automatic scorers and human raters, and produces comparisons people make ship decisions on. Present it as you would on a voice call — a fixed spoken structure that substitutes for a diagram: requirements and scale numbers → the API → the data model → the write path → the read path → the bottleneck → what you would trade.",
      "",
      "Cover: benchmark and dataset versioning; a run orchestrator that fans work across models; the scorer interface; result storage keyed for reproducibility; aggregation with confidence intervals; human-annotation intake with agreement tracking; and the two hard parts — caching so an unchanged (model, item) pair is never re-run, and versioning so a scorer change does not silently invalidate history.",
    ].join("\n"),
    hints: [
      "Announce the order and number the components aloud (\"three services: ingest, store, query\") — that is what keeps a listener oriented without a picture.",
      "Key every result by (model version, benchmark version, item id, scorer version). That single key gives you reproducibility, caching, and the ability to explain any number on a dashboard.",
      "A scorer change is a new scorer version, not an edit: old results stay attached to the old version and a re-score is an explicit, auditable job. Raw agreement between raters misleads on skewed labels — track kappa.",
    ],
    rubric: [
      "- **Spoken structure** — states an order up front (requirements → API → data model → write path → read path → bottleneck → trade-offs) and numbers the components; a listener could reconstruct the diagram.",
      "- **Registry and versioning** — benchmarks, datasets and scorers are immutable versions; a change creates a new version and re-scoring is an explicit job, so historical numbers never change silently.",
      "- **Orchestration** — a run fans (model, item) work across a worker pool with retries and per-item idempotency; explains how a run resumes and how cost is bounded.",
      "- **Reproducible results and caching** — results keyed by (model version, benchmark version, item id, scorer version); an unchanged pair is served from the cache, and the design says how cache validity is decided.",
      "- **Aggregation with uncertainty** — reports means with bootstrap or paired-bootstrap confidence intervals, and says what staleness or approximation the comparison tolerates.",
      "- **Human labels and judges** — annotation intake with inter-annotator agreement (kappa) and adjudication; names LLM-as-judge failure modes (position, verbosity, self-preference, correlated judges) and how they are mitigated.",
    ].join("\n"),
    solution: [
      "## The spoken structure",
      "",
      "You cannot draw, so announce a fixed order and keep to it: requirements and scale → API → data model → write path → read path → bottleneck → trade-offs. Number the components aloud: six services — registry, orchestrator, scorer runtime, result store, aggregation, annotation intake.",
      "",
      "## Requirements and numbers",
      "",
      "Tens of benchmarks, each with 10^3–10^5 items; dozens of model versions a week; every (model, benchmark) run must be reproducible months later. Reads are dashboards and comparisons; writes are bursty when a new model version lands. Latency for a comparison query matters far less than never presenting a number nobody can regenerate.",
      "",
      "## API",
      "",
      "```",
      "POST /benchmarks            register a benchmark version (immutable items + scorer bindings)",
      "POST /runs                  { model_version, benchmark_version }  -> run id (idempotent on the pair)",
      "GET  /runs/{id}             status, per-item progress, cost so far",
      "GET  /compare?a=&b=&bench=  aggregate with confidence intervals, paired where items overlap",
      "POST /annotations           human labels for (benchmark_version, item_id), with rater id",
      "```",
      "",
      "## Data model",
      "",
      "Registry: benchmark versions (immutable item sets with content hashes), dataset versions, scorer versions. Results: one row per `(model_version, benchmark_version, item_id, scorer_version)` holding the raw model output, the score, the scorer inputs, and a trace id — that key is the whole design. Annotations: `(benchmark_version, item_id, rater_id) → label`, with adjudicated labels stored as their own scorer version.",
      "",
      "## Write path",
      "",
      "A run request expands into (model, item) tasks on a queue. Workers check the result store first — an unchanged `(model_version, benchmark_version, item_id, scorer_version)` is never re-run — then call the model, then the scorer plugin, and write the row idempotently. Retries are safe because the key is deterministic; a run resumes by re-enqueueing missing keys. Cost is bounded per run and per day.",
      "",
      "## Read path",
      "",
      "Aggregation reads the rows for a run, computes the mean and a bootstrap confidence interval, and for comparisons uses a paired bootstrap over shared items, which is tighter because it cancels item difficulty. Dashboards read materialised aggregates, recomputed when new rows land, never on the request path.",
      "",
      "## The two hard parts",
      "",
      "**Caching.** The key makes it exact: the same model version on the same item with the same scorer version is the same result. The subtlety is what \"same model version\" means — pin the weights hash and the decoding parameters, or the cache lies.",
      "",
      "**Versioning.** A scorer change silently invalidates every historical number unless it is a new scorer version. Old results stay attached to the old version; re-scoring history is an explicit, auditable job that writes new rows, and dashboards say which scorer version they show.",
      "",
      "## Human labels and model judges",
      "",
      "Annotation intake tracks inter-annotator agreement — Cohen's kappa for two raters, Fleiss' for more — and routes disagreements to adjudication. Model-based judging is a scorer version like any other, with its known failure modes named: position bias, verbosity bias, self-preference, and correlated errors across judges, so a panel of nine carries far fewer independent votes than nine.",
      "",
      "## Bottleneck and trade-offs",
      "",
      "The bottleneck is model inference cost, which is why the cache and the idempotent key matter more than any storage choice. The trade: eventual consistency in dashboards (aggregates lag new rows by minutes) in exchange for reads that never touch the write path.",
      "",
      "## Worth saying out loud",
      "",
      "- For the feed variant of this round, the axis is push versus pull: fan-out-on-write reads fast and hurts on celebrity accounts, fan-out-on-read is the reverse, and the honest answer is hybrid. \"Fresh and performant\" is the tension in the prompt; name it as the trade rather than picking one.",
      "- For a debugging round, narrate a method rather than hunting: what the code should do, the smallest failing input, which invariant is violated, where state first diverges — and read the code aloud, because silence is indistinguishable from being lost.",
    ].join("\n"),
  },
];
