import type { Problem } from "./types";

// Apple system-design prompts reported for Software Engineer loops (PracHub's
// Apple list, 2025–2026), part B: cloud photo sync, centralized logging, and
// cross-device wallpaper sync. Prompts are restated in our own words; each
// carries a rubric for the AI design review and a worked answer.

export const appleDesignProblemsB: Problem[] = [
  {
    slug: "design-cloud-photo-sync",
    title: "Design Cloud Photo Storage and Multi-Device Sync",
    category: "system-design",
    difficulty: "medium",
    companies: ["apple"],
    summary:
      "Bytes go straight to object storage; a per-library change feed with sync tokens is the actual product.",
    prompt: [
      "Design a cloud photo service in the shape of iCloud Photos: a user's library lives in the cloud, every device can upload and download, and a change made on one device — a new photo, an edit, a delete, an album move — shows up on the others.",
      "",
      "Assume 200M active users with about three devices each, ~4 new photos per user per day at ~3 MB (so petabytes of new bytes daily), libraries of 10k+ assets, and devices that spend hours or weeks offline. A new photo should appear on the user's other online devices within seconds as a thumbnail; originals may arrive later or on demand.",
      "",
      "Cover: the upload path and where an asset atomically comes into existence; the sync protocol between the server and a device that has been offline; the metadata model and how it is partitioned; conflicts between devices (edit vs edit, edit vs delete); failure recovery for interrupted uploads; and what you would measure.",
      "",
      "*Reported as: a cloud photo-storage service with upload, download, and multi-device synchronization (PracHub, Apple Software Engineer onsite, Aug 2026).*",
    ].join("\n"),
    hints: [
      "Separate the planes before anything else: photo bytes go from the device straight to object storage through a resumable upload session; your API tier only handles small metadata records. The asset exists when its metadata commits, which happens after the bytes are durable.",
      "Sync is a per-library ordered change log. Every mutation gets the library's next sequence number; a device stores a cursor and asks for everything after it. A silent push only means 'poll now' — correctness never depends on the push arriving.",
      "Make every client mutation idempotent with a client-generated id, and decide conflict rules per record type: non-destructive edits with a version check, delete-wins with a recoverable tombstone.",
    ],
    rubric: [
      "- **Plane separation and the commit point** — bytes upload directly to object storage (presigned, chunked, resumable); metadata commits last and is the moment the asset exists; orphaned bytes are garbage-collected. An API tier that proxies photo bytes is a major miss.",
      "- **Sync protocol** — a per-library monotonically ordered change log with device cursors (sync tokens), paginated catch-up, push as a hint rather than a guarantee, and a full-resync path when a token is older than the compacted log.",
      "- **Metadata model and partitioning** — assets, albums, memberships, tombstones keyed by library; sharded by user or library so one library's sequence is assigned by a single writer; states why per-library strong consistency is affordable.",
      "- **Conflicts and idempotency** — client-generated asset and operation ids so retries are safe; content-hash dedup for the same photo imported twice; explicit edit-vs-edit and edit-vs-delete rules with tombstones and a recovery window.",
      "- **Device-aware delivery** — derivatives (thumbnail, screen-size) generated asynchronously, thumbnails synced first, originals on demand or on Wi-Fi; storage-optimised devices evict originals safely.",
      "- **Failure recovery and observability** — resumable uploads, backoff, replicated metadata and erasure-coded objects across regions; metrics such as commit-to-device sync lag, cursor staleness, upload success rate, orphaned bytes.",
    ].join("\n"),
    solution: [
      "## Numbers that shape the design",
      "",
      "200M users × 4 photos/day = 800M uploads/day ≈ 9k/s average, ~30k/s at peak. At 3 MB that is ~2.4 PB of new bytes per day, so bytes can never transit the API tier. Metadata is tiny by comparison: ~1 KB per asset × 10k assets = 10 MB per library, 2 PB across all users — a sharded database problem, not a storage problem. Reads are dominated by thumbnails, which are small, immutable and perfectly cacheable.",
      "",
      "## API and data",
      "",
      "```",
      "POST /libraries/{lib}/uploads          { asset_id (client UUID), sha256, size }  -> upload session + part URLs",
      "PUT  <object-store part URL>           bytes, resumable by part number",
      "POST /libraries/{lib}/assets/{id}:commit   { sha256, captured_at, exif }        -> 201 | 200 if already committed",
      "PATCH /libraries/{lib}/assets/{id}     If-Match: <version>  { adjustments | favourite | deleted }",
      "GET  /libraries/{lib}/changes?since=<token>&limit=500   -> { changes[], next_token, more }",
      "",
      "asset      (lib_id, asset_id) -> sha256, size, state, version, captured_at, adjustments, deleted_at",
      "change_log (lib_id, seq)      -> { record_type, record_id, version }        append-only, compacted",
      "blob       sha256             -> object location, derivatives, ref_count     content-addressed, immutable",
      "device     (lib_id, device_id)-> last_acked_seq, push_token",
      "```",
      "",
      "Shard by `lib_id`. One shard leader assigns a library's sequence numbers, so ordering inside a library is total and cheap, and no cross-shard transaction is ever needed: a commit writes the asset row and the change-log row in one local transaction.",
      "",
      "## Upload path",
      "",
      "The device asks for an upload session, PUTs parts directly to object storage, and may resume from the last acknowledged part after any interruption. Only when the object store confirms the full object — and its hash matches — does the device call `commit`. That metadata commit is the atomic moment the asset exists; it appends to the change log in the same transaction. Bytes first, metadata last means a crash leaves orphaned bytes (swept by a GC that looks for unreferenced objects older than a day), never a visible asset without bytes. `commit` is idempotent on `asset_id`, so a retry after a timeout returns the same result. A second device importing the same file produces the same `sha256`: the blob is stored once and reference-counted, and within one library the duplicate import resolves to the existing asset.",
      "",
      "Derivatives are asynchronous: a commit event drives thumbnail and screen-size generation. Other devices learn about the asset immediately and render a placeholder until the thumbnail derivative is ready, which is normally a second or two.",
      "",
      "## Sync protocol",
      "",
      "Each device stores a sync token — the last sequence it has applied. `GET /changes?since=token` returns ordered change records in pages; the device applies them and advances its token only after they are durably applied locally. After a commit the server sends a silent push to the library's other devices, but the push only says *poll now*. If it is dropped, the device polls on wake, on foreground and on a slow timer, so correctness never depends on it.",
      "",
      "The change log is compacted: older entries collapse to the latest change per record. A device whose token predates compaction — a phone in a drawer for a year — gets `410 Gone` and performs a snapshot resync: page through current records, then resume from the snapshot's token. Thumbnails sync eagerly; originals download on demand, or in the background on Wi-Fi and power.",
      "",
      "## Conflicts",
      "",
      "Offline devices queue mutations locally with client operation ids and replay them in order on reconnect; the server drops operation ids it has already applied. Edits are non-destructive adjustment records guarded by `If-Match: version`. On a version mismatch the device re-reads, and the rule is last-writer-wins per field — favourite and caption merge trivially, two competing adjustment stacks keep the later one while the original stays intact. Edit versus delete: delete wins, but a delete is a tombstone with a 30-day recovery window, so nothing is lost to a race.",
      "",
      "## Failure recovery",
      "",
      "Metadata shards replicate synchronously within a region and asynchronously across regions; objects are erasure-coded across failure domains and replicated cross-region before an original is ever evicted from the uploading device. A region failover may replay a few seconds of change log; because operations are idempotent and devices re-request from their own token, replay is harmless. Uploads back off with jitter and respect cellular and low-power settings.",
      "",
      "## What to measure",
      "",
      "Commit-to-device sync lag (p50/p99), distribution of device cursor staleness, upload session completion rate and resume counts, derivative latency, orphaned bytes, `410` resync rate, and conflict rates by type.",
      "",
      "## Probes to expect",
      "",
      "- *Why not sync by timestamp?* Device clocks lie and ties lose updates. A server-assigned per-library sequence is total and gap-free.",
      "- *End-to-end encryption?* The server can no longer generate derivatives or dedup across users; the client uploads encrypted thumbnails alongside the original. Say what you give up.",
      "- *A user with 500k photos?* The library is still one shard-local log; snapshot resync pages by key, and thumbnail download is the long pole, not metadata.",
    ].join("\n"),
  },
  {
    slug: "design-centralized-logging",
    title: "Design a Centralized Logging System",
    category: "system-design",
    difficulty: "medium",
    companies: ["apple"],
    summary:
      "Agents, a durable buffer, tiered storage — and deciding how much to index before the bill decides for you.",
    prompt: [
      "Design the logging platform for a large company: thousands of services on tens of thousands of hosts emit logs, and engineers search them to debug incidents, follow a request by trace id, and drive alerts.",
      "",
      "Assume ~2M log events per second at peak, ~1 KB each. Recent logs (7–30 days) must be searchable within seconds of being written; older logs are kept a year for audit at much lower cost. Emitting a log line must never slow down or take down the service that emits it, and one noisy service must not starve everyone else.",
      "",
      "Cover: collection on the host, the ingestion path, how producers are decoupled from consumers, partitioning, storage tiers and indexing strategy, the query path, delivery guarantees, multi-tenancy and sensitive data, and how you monitor the logging system itself.",
      "",
      "*Reported as: a centralized logging system covering ingestion, storage, indexing and query serving (PracHub, Apple Software Engineer onsite, Jun 2026); a logging-system design also appears in a reported 2026 Apple onsite.*",
    ].join("\n"),
    hints: [
      "Do the arithmetic: 2M events/s × 1 KB is ~2 GB/s, roughly 170 TB a day before compression. That number rules out indexing every token of every line forever and forces tiers.",
      "Put a durable log (Kafka or similar) between collection and everything else. It absorbs bursts, lets indexers fall behind without losing data, and lets you add consumers — alerting, archival, security — without touching producers.",
      "Indexing is the cost lever. Compare a full inverted index on hot data with a label index plus compressed chunks that are scanned in parallel; most queries filter by service, time range and trace id first.",
    ],
    rubric: [
      "- **Estimates that drive decisions** — derives bytes per second and per day, applies a compression ratio, and uses the result to justify tiering and selective indexing.",
      "- **Collection that cannot hurt the application** — a host agent that tails files or stdout, buffers to bounded local disk, batches and compresses, and sheds load by severity; the application never blocks on the network.",
      "- **Decoupling and partitioning** — a durable buffer between ingestion and consumers, partitioned to avoid hot partitions from one noisy service, with per-tenant quotas and backpressure.",
      "- **Storage tiers and indexing strategy** — time-partitioned hot storage with an explicit indexing choice and its cost, cheaper warm and cold tiers on object storage, retention per tenant, and how a query spans tiers.",
      "- **Query path** — a frontend that splits by time and shard, runs in parallel with limits and caching, and makes trace-id and recent-window queries fast.",
      "- **Guarantees, safety and self-monitoring** — at-least-once with dedup keys, ordering only per source, PII scrubbing and access control, and independent monitoring of ingest lag and drop counts.",
    ].join("\n"),
    solution: [
      "## Numbers first",
      "",
      "2M events/s × 1 KB ≈ 2 GB/s ≈ 170 TB/day raw. Logs compress 5–10×, so ~20–35 TB/day lands on disk, ~1 PB for a 30-day hot window before replication. A full inverted index can add 50–100% on top. Those numbers make the two big decisions: storage must be tiered, and indexing must be selective.",
      "",
      "## Collection",
      "",
      "Applications write to stdout or a local file and return immediately. A per-host agent tails the files, attaches metadata (service, host, region, deployment), batches, compresses and ships. The agent keeps a bounded on-disk buffer with file offsets checkpointed, so a restart or a network partition resumes where it left off. When the buffer fills, it sheds by severity — debug first, never error — and counts what it dropped. The application never blocks on logging; that is the first requirement and the agent is how it is met.",
      "",
      "## Ingestion and the durable buffer",
      "",
      "Agents send to a stateless ingestion gateway that authenticates the tenant, enforces per-tenant rate quotas, normalises to a common envelope, and appends to a durable log such as Kafka. The log is the decoupling point: indexers can lag or be redeployed without data loss, and alerting, archival and security analytics are just additional consumer groups.",
      "",
      "Partition by tenant and service with a bounded spread — hash of (service, agent id) across that service's partition range — rather than by service alone, so one service that starts logging 100× does not pin a single partition. Quotas at the gateway plus per-tenant partition ranges are what keep a noisy neighbour from starving the rest.",
      "",
      "## Processing",
      "",
      "Stream processors parse structured fields, scrub sensitive data (tokens, emails, account numbers) before anything is stored, apply sampling rules for high-volume debug streams, and route to the hot store and the archive in parallel.",
      "",
      "## Storage tiers and the indexing decision",
      "",
      "- **Hot (hours to days):** time-partitioned segments on local SSD, replicated. Index a small set of fields — service, level, host, trace id, a few tenant-defined labels — and store the message body in compressed columnar chunks.",
      "- **Warm (days to weeks):** the same chunks moved to object storage with a small per-chunk index: min/max time, label values, and a bloom filter for trace ids.",
      "- **Cold (up to a year):** compressed Parquet on the cheapest object tier, queryable by batch jobs, restored on request.",
      "",
      "The trade to state out loud: a full inverted index on every token gives fast arbitrary search and costs about as much again as the data; a label index plus parallel scanning of compressed chunks is several times cheaper and answers most real queries, because engineers nearly always narrow by service and time first. Choose the second by default and let tenants pay for full-text on specific streams.",
      "",
      "## Query path",
      "",
      "A query frontend parses the query, requires a time range, splits it into per-partition sub-queries across tiers, fans out to queriers, merges, and streams results. It enforces limits on scanned bytes and concurrency per tenant and caches results for repeated dashboard queries. Trace-id lookups use the per-chunk bloom filters to skip almost everything. Tailing the last minutes is served from the hot tier's in-memory segments.",
      "",
      "## Guarantees",
      "",
      "Delivery is at-least-once end to end; duplicates are removed with a key of (agent id, file, offset). Ordering is promised only within one source, by offset; across sources the timeline is by event timestamp with a note that clocks skew. Late data simply lands in the partition for its event time.",
      "",
      "## Multi-tenancy and sensitive data",
      "",
      "Tenant id on every event, retention and quotas per tenant, role-based access to streams, scrubbing at ingest, encryption at rest, and an audit trail of who queried what — logs are one of the largest stores of sensitive data a company has.",
      "",
      "## Watching the watcher",
      "",
      "The logging system cannot depend on itself to report its own outage. Export a minimal set of metrics through a separate path: agent drop counts and buffer depth, gateway rejects, consumer lag per partition, indexing latency (event time to searchable), query latency and error rate. Ingest lag is the headline service-level indicator.",
      "",
      "## Probes to expect",
      "",
      "- *A region loses connectivity?* Logs stay in-region, agents buffer locally, and queries federate across regions rather than shipping all bytes to one place.",
      "- *Exactly-once?* Not worth the cost for logs; idempotent writes keyed by source offset make duplicates invisible.",
      "- *What breaks first at 10×?* Indexing cost, then hot-tier disk. The levers are sampling, fewer indexed fields, and a shorter hot window.",
    ].join("\n"),
  },
  {
    slug: "design-wallpaper-sync",
    title: "Design Cross-Device Wallpaper Synchronization",
    category: "system-design",
    difficulty: "medium",
    companies: ["apple"],
    summary:
      "A client-side design: apply locally at once, converge eventually, and never let sync touch the main thread.",
    prompt: [
      "A user sets a wallpaper on one device and expects it on their other devices. Design the feature end to end, with most of the weight on the client.",
      "",
      "A local change must apply immediately, even offline. Remote changes apply eventually. Devices may be offline for weeks, and two devices may change the wallpaper at nearly the same time. Wallpaper images are large; devices have different screens, limited cache space, batteries, and metered networks; and the user interface must never stutter because of sync.",
      "",
      "Cover: the data model and why image assets are immutable; the conflict policy; the local-change and remote-change flows; authentication; retries; cache limits; battery and network controls; image decoding; and how the interface stays responsive throughout.",
      "",
      "*Reported as: cross-device wallpaper synchronization with offline devices and concurrent edits (PracHub, Apple Software Engineer onsite, Jun 2026).*",
    ].join("\n"),
    hints: [
      "Split the state in two: a tiny mutable configuration record (which asset, crop, version) and large immutable assets addressed by content hash. Only the small record ever conflicts.",
      "Only the latest configuration matters, so the outbound queue collapses to the last write and an offline device never replays history — it fetches the current record when it comes back.",
      "Treat a push as a hint. Download with the system's background transfer service, decode off the main thread at display size, and swap only when the new wallpaper is fully ready.",
    ],
    rubric: [
      "- **Data model** — a small versioned configuration record separate from immutable, content-addressed image assets; the asset is uploaded before any configuration references it, and garbage collection respects references.",
      "- **Conflict policy** — a deterministic rule (server version or hybrid logical clock with a device-id tiebreak), conditional writes, and devices that only ever move forward so they cannot flip-flop.",
      "- **Local-first flow** — immediate local apply, a persistent outbound queue that coalesces to the latest change, idempotent operations, and sensible behaviour while offline.",
      "- **Remote-change flow** — push as a hint with polling fallback, device-appropriate asset variant, download then decode then atomic swap, keeping the previous wallpaper until the new one is ready.",
      "- **Resource discipline** — bounded disk and memory caches, downsampled decoding, battery and network policy (Wi-Fi, low-power mode, discretionary background transfers), backoff with jitter.",
      "- **Security and responsiveness** — per-user authorisation, short-lived signed asset URLs, all I/O and decoding off the main thread, and metrics such as time to consistency and conflict rate.",
    ].join("\n"),
    solution: [
      "## The shape of the problem",
      "",
      "This is a local-first client design with a very small server. The only mutable state is one configuration record per user (or per user and scope, such as lock screen and home screen). Everything heavy — the image — is immutable. Getting that split right removes most of the difficulty.",
      "",
      "## Data model",
      "",
      "```",
      "wallpaper_config  (user_id, scope) -> { asset_hash, crop, effects, version, updated_by_device, hlc }",
      "asset             asset_hash       -> original + per-device-class derivatives, ref_count     immutable",
      "",
      "PUT  /wallpaper/{scope}      If-Match: <version>   { asset_hash, crop, effects, hlc, op_id }",
      "GET  /wallpaper/{scope}                            -> config + signed asset URLs",
      "HEAD /assets/{hash}  |  resumable upload           upload only when the hash is unknown",
      "```",
      "",
      "Assets are addressed by content hash, so an upload is naturally idempotent, the same image chosen twice is stored once, and caches never need invalidation. The asset must exist on the server before any configuration references it.",
      "",
      "## Local change",
      "",
      "1. Write the new configuration to the local store and render it immediately. The user's action never waits on the network.",
      "2. Append an operation to a persistent outbound queue. Because only the latest wallpaper matters, the queue coalesces: a newer local change replaces an unsent older one.",
      "3. When connectivity and policy allow, upload the asset if `HEAD` says it is missing, then `PUT` the configuration with `If-Match` on the version the device last saw.",
      "4. On `412`, fetch the current record and apply the conflict rule below.",
      "",
      "Operations carry an `op_id`, so a retry after a timeout cannot apply twice.",
      "",
      "## Conflict policy",
      "",
      "Last writer wins, decided deterministically: compare hybrid logical clocks (physical time plus a counter, so a fast clock cannot win forever), break ties by device id. The server increments `version` on every accepted write, and a device applies a remote record only if its version is higher than the one it holds — so devices converge and never flip-flop. If the remote change wins, the local choice is kept in a short history so the user can restore it. A per-device switch to opt out of sync is a product answer to people who want different wallpapers, not a conflict rule.",
      "",
      "## Remote change",
      "",
      "A silent push tells online devices to fetch. Pushes are best-effort, so the device also checks on wake, on foreground and on a slow timer. A device that was offline for a month fetches only the current record — there is no history to replay.",
      "",
      "Then: pick the derivative for this device class, download through the system background transfer service, verify the hash, decode **off the main thread** directly at display resolution (a 48-megapixel original decoded at full size is hundreds of megabytes), prepare the blurred or dimmed variants, and only then swap atomically. The previous wallpaper stays on screen until the new one is completely ready, and a failed download or decode leaves the old one in place.",
      "",
      "## Resource controls",
      "",
      "- **Cache:** an LRU disk cache bounded by bytes, always pinning the current and previous wallpaper; memory holds only the display-size bitmap.",
      "- **Network and battery:** large transfers are discretionary — preferably Wi-Fi, not in low-power mode, and ideally while charging; metered networks fetch the small configuration immediately and defer the asset, showing the change when it arrives.",
      "- **Retries:** exponential backoff with jitter, capped, and resumable transfers so progress survives suspension.",
      "",
      "## Authentication",
      "",
      "Requests carry a device-bound token scoped to the user; the server derives the user from the token, never from the body. Assets are served through short-lived signed URLs. If wallpapers are end-to-end encrypted, the client produces the derivatives, which costs upload bytes and battery — say so.",
      "",
      "## Keeping the interface responsive",
      "",
      "All sync work runs on background queues with cancellation; the main thread only swaps a ready bitmap. Rapid local changes are debounced before upload. Asset garbage collection on the server respects references from both the current record and the restore history.",
      "",
      "## What to measure",
      "",
      "Time to consistency per device, conflict rate, decode failures, cache hit rate, bytes moved on cellular, and background task expirations.",
      "",
      "## Probes to expect",
      "",
      "- *Why not vector clocks?* One small record with a product rule of 'latest wins' does not need causality tracking; a hybrid logical clock with a tiebreak is enough and far simpler.",
      "- *Live or dynamic wallpapers?* Same model — the asset is a bundle; the decode and prepare step grows, which is another reason it must stay off the main thread.",
    ].join("\n"),
  },
];
