import type { Problem } from "./types";

// Snowflake system-design prompts, part A: the two infrastructure designs
// that get the fullest treatment — a distributed job scheduler and a
// distributed key-value store.

export const snowflakeDesignProblemsA: Problem[] = [
  {
    slug: "design-distributed-job-scheduler",
    title: "Design a Distributed Job Scheduler",
    category: "system-design",
    difficulty: "hard",
    companies: ["snowflake"],
    summary:
      "A job store as the source of truth, dispatchers that claim due runs with a unique key, leased workers, and a reaper — then the policies a template answer forgets.",
    prompt: [
      "Design a distributed job scheduler. Users submit jobs — one-time or recurring on a cron expression — with a payload; a job can be paused and resumed; due jobs run on a fleet of workers; failures are retried according to a per-job policy. The same run must never be launched twice, even when a dispatcher or a worker dies in the middle of its work.",
      "",
      "Start by pinning down the requirements that change the design: one-time versus recurring and the cron precision, how many jobs fire in the busiest second, what happens to runs missed while a job was paused or the scheduler was down, whether two runs of the same job may overlap, and what *exactly once* means to the user. Then give the data model, the dispatch flow, how pause and resume work, the decisions you made and their alternatives, and how the system behaves when each component fails.",
    ].join("\n"),
    hints: [
      "Make the job store the source of truth and the queue only a carrier of work: every component reads or writes the store, so a crash anywhere is recovered from its rows and nothing depends on the queue being complete.",
      "The duplicate-launch guard is a unique key on (job_id, fire_time) in the runs table, claimed in the same transaction that advances next_fire_time; a second dispatcher's insert fails harmlessly. Workers add a lease with heartbeats so a dead worker's run can be retried.",
      "Pause is a state change — running work finishes untouched and the dispatcher skips PAUSED jobs. Resume recomputes next_fire_time from now unless the user asked to catch up, and that is a policy you have to ask about.",
    ],
    solution: [
      "## Requirements to settle in the first five minutes",
      "",
      "- One-time, recurring or both, and cron precision in seconds or minutes: sets the scan interval and the index.",
      "- How many jobs, and how many fire in the busiest second: cron piles up at minute and hour boundaries.",
      "- Missed runs while paused or while the scheduler was down: skipped, run once, or caught up in full.",
      "- Can two runs of one job overlap: a per-job concurrency policy.",
      "- What exactly once means: you can offer at-least-once launch plus an idempotency key, not exactly-once execution.",
      "",
      "## Data model",
      "",
      "```",
      "jobs  job_id, tenant, cron_expr, payload, state (ACTIVE | PAUSED | CANCELED), next_fire_time, shard",
      "      index on (shard, next_fire_time) for ACTIVE rows",
      "runs  job_id, fire_time, status, attempt, worker, lease_expires",
      "      unique (job_id, fire_time) -- what stops duplicates",
      "```",
      "",
      "## Flow",
      "",
      "1. A dispatcher scans its shards for ACTIVE jobs with `next_fire_time <= now`.",
      "2. In one transaction it inserts the `runs` row and advances `next_fire_time` to the next cron tick. The unique key makes a second dispatcher's insert fail harmlessly.",
      "3. An outbox relay publishes the run to a queue — after commit, never before, so no run is launched that the database does not know about.",
      "4. A worker takes the message, claims a lease on the run row, heartbeats while executing, and writes the final status.",
      "5. A reaper finds runs whose lease expired and re-queues them according to the job's retry policy.",
      "",
      "The job store is the source of truth; the queue only carries work. Every component reads or writes the store, so a crash anywhere is recovered from its rows.",
      "",
      "## Pause and resume",
      "",
      "Pause is a state change: the dispatcher skips PAUSED jobs and running work finishes untouched. Resume recomputes `next_fire_time` from the current time unless the user chose catch-up, in which case the missed ticks are enqueued with their original fire times.",
      "",
      "## Decisions to defend, each with its alternative",
      "",
      "- **Who dispatches:** shards with one lease-holding dispatcher per shard. A single elected leader is simpler and fine for modest volume, with slower failover.",
      "- **Finding due jobs:** a database index scan every second. An in-memory timing wheel preloaded with the next minute has lower latency at high fire rates and more state to rebuild after a crash.",
      "- **Dispatcher to worker:** a durable queue. Direct RPC to workers has fewer parts and loses retries, buffering and visibility.",
      "- **Duplicate launches:** the unique (job_id, fire_time) plus the worker lease. A distributed lock per job works too and adds a lock service to the hot path.",
      "- **Time source:** the database clock for every comparison. Scheduler clocks with NTP are the alternative if you accept a tick of skew.",
      "",
      "## Failure modes",
      "",
      "- Dispatcher dies after commit, before publish: the outbox relay publishes on restart; no run is lost.",
      "- Two dispatchers believe they own a shard: the unique key rejects the second insert.",
      "- Worker dies mid-run: the lease expires; the reaper retries if the job is marked idempotent, otherwise marks it failed and alerts.",
      "- Queue redelivers a message: the worker sees the run already leased or finished and drops it.",
      "- Scheduler down across a fire time: the missed-run policy decides — skip, run once, or catch up all.",
      "",
      "## What shows judgment beyond the reference architecture",
      "",
      "Bring these up unprompted: the minute-boundary pile-up and jittered dispatch, the missed-run and overlap policies, per-tenant fairness so one tenant's backlog cannot starve the others, and what you would alert on — dispatch lag, lease expiries, queue depth.",
    ].join("\n"),
  },
  {
    slug: "design-distributed-kv-store",
    title: "Design a Distributed Key-Value Store",
    category: "system-design",
    difficulty: "hard",
    companies: ["snowflake"],
    summary:
      "Non-functional requirements first, then one real decision per layer — and the large-value variant, where the lock must never cover the disk write.",
    prompt: [
      "Design a distributed key-value store: `put`, `get`, `delete`, and optionally `scan(prefix)` over sorted keys. Open by listing the non-functional requirements you need before choosing anything — read/write ratio, key and value sizes, latency target, durability, whether stale reads are acceptable, whether range scans are needed — and let them drive the design.",
      "",
      "Cover partitioning, replication and the consistency it implies, the storage engine on each node, and how replicas are repaired. Then take the large-value variant: values of many megabytes live on disk, and a writer holding a key's lock while writing to disk makes every reader and writer of that key wait. Fix the contention and be ready to write the acquire-and-release pseudocode.",
    ].join("\n"),
    hints: [
      "Each layer is a two-option decision with a rule for choosing: consistent hashing versus range partitions (ranges are required for prefix scans), Raft per shard versus leaderless quorums (the consistency-versus-availability call), LSM versus B-tree (write-heavy versus read-heavy), read repair versus anti-entropy (use both).",
      "For large values, separate keys from values: the index maps a key to (file, offset, length) and values go to an append-only log. Write the blob with no lock held, then take the key's lock only to swap the pointer.",
      "Readers copy the pointer under a shared lock, release it, then read the blob; old blobs stay valid until garbage collection, so a reader never blocks on a writer's I/O.",
    ],
    rubric: [
      "- **Requirements first** — read/write ratio, sizes, latency, durability, staleness tolerance and range scans are asked before any component is drawn, and each later choice refers back to one of them.",
      "- **Partitioning** — consistent hashing with virtual nodes versus range partitions that split when large, chosen by whether `scan(prefix)` is required.",
      "- **Replication and consistency** — one Raft group per shard (linearizable, writes need a majority) versus a leaderless N/R/W quorum (stays writable through more failures, readers may see stale data), stated as the consistency-versus-availability decision the use case needs.",
      "- **Storage engine** — LSM tree (write-ahead log, memtable, sorted files, compaction, Bloom filters) for write-heavy load versus a B-tree for read-heavy load with predictable latency.",
      "- **Repair** — read repair and hinted handoff for the cheap path, background anti-entropy with Merkle trees for cold keys.",
      "- **Large values and lock contention** — key/value separation with an append-only value log, write-then-swap under a short lock, readers that copy the pointer and read outside the lock, striped locks taken in a fixed order, and a value-log garbage collector — with pseudocode that a reviewer can check for the lock never covering disk I/O.",
    ].join("\n"),
    solution: [
      "## Open with the non-functional requirements",
      "",
      "Read/write ratio, key and value sizes, latency target, durability, whether stale reads are acceptable, and whether range scans are needed. Each decision below points back at one of them.",
      "",
      "## One decision per layer",
      "",
      "| Layer | Option A | Option B | How to choose |",
      "|---|---|---|---|",
      "| Partitioning | Consistent hashing with virtual nodes | Range partitions that split when large | Hashing spreads load evenly; ranges are required for `scan(prefix)` |",
      "| Replication | One Raft group per shard: linearizable, writes need a majority | Leaderless quorum with N, R, W: stays writable through more failures, readers may see stale data | This is the consistency-versus-availability decision; state which the use case needs and commit |",
      "| Storage engine | LSM tree: write-ahead log, memtable, sorted files, compaction, Bloom filters | B-tree: update in place | LSM for write-heavy load; B-tree for read-heavy load with predictable latency |",
      "| Repair (leaderless only) | Read repair and hinted handoff | Background anti-entropy with Merkle trees | Use both; the first is cheap, the second catches cold keys |",
      "",
      "## Large values on disk and lock contention",
      "",
      "The problem: a writer holding a key's lock while writing megabytes to disk makes every reader and writer of that key wait.",
      "",
      "- Separate keys from values: the index holds key → (file, offset, length); values go to an append-only value log.",
      "- Write the value first, lock second: append the blob with no lock held, then take the key's lock only to swap the pointer. The critical section becomes a few instructions.",
      "- Readers copy the pointer under a shared lock, release it, then read the blob. Old blobs stay valid until garbage collection, so readers never block on a writer's I/O.",
      "- Use striped locks — hash the key into a fixed array of locks — to bound memory. When an operation needs several keys, take the stripes in index order to avoid deadlock.",
      "- Garbage-collect the value log by copying live values forward and swapping pointers with the same short lock.",
      "",
      "```",
      "put(key, blob):",
      "  loc = value_log.append(blob)                 # slow disk write, no lock held",
      "  with stripes[hash(key) % N].write():         # short critical section",
      "    old = index.get(key)",
      "    index[key] = loc",
      "    wal.append(('put', key, loc))",
      "  if old: gc.mark_dead(old)",
      "",
      "get(key):",
      "  with stripes[hash(key) % N].read():",
      "    loc = index.get(key)                       # copy the pointer only",
      "  return value_log.read(loc) if loc else None  # disk read outside the lock",
      "```",
      "",
      "## Design-then-build",
      "",
      "When the round asks you to build a first version with `put`, `get`, `delete` and `scan(prefix)`, agree the smallest buildable slice before typing: a sorted structure answers the scan — a sorted list with binary search, or a skip list or tree if writes are frequent — and persistence, TTL and replication are extensions, in that order. Over-scoping the first version is the way to run out of time. The single-node version is [Key-Value Store With Prefix Scan](/problems/kv-store-with-prefix-scan).",
      "",
      "## Probes to expect",
      "",
      "- *A hot key?* Replicate reads of that key to more nodes, cache in front, or split the value if it is a large aggregate.",
      "- *Thread safety in one process?* One lock around the whole invariant first, then the refinements: read-write locks, lock striping, per-thread state.",
      "- *A crash mid-write?* The write-ahead log entry is written before the index swap; replay on restart; orphaned blobs in the value log are reclaimed by the collector.",
    ].join("\n"),
  },
];
