import type { Problem } from "./types";

// Pinterest design-round prompts 3 and 5 (search typeahead, ads event
// reporting) from the Pinterest_Design_Round_Prep research doc. Prompt 4
// (distributed rate limiter) already exists as design-rate-limiter and is
// Pinterest-tagged there. See seed-design-a.ts for the series notes.

export const designProblemsB: Problem[] = [
  {
    slug: "design-search-typeahead",
    title: "Design Search Typeahead",
    category: "system-design",
    difficulty: "medium",
    companies: ["pinterest"],
    summary:
      "Tries with precomputed top-k, prefix sharding, and freshness by atomic swap.",
    prompt: [
      '"Design the autocomplete box for Pinterest search. As the user types, show the top ten suggestions. It should feel instant, work for hundreds of millions of users, and reflect what\'s trending, not just what was popular last year."',
      "",
      "Assume prefix matching on the whole query plus the last token, no spell-correction in v1. Suggestions come from real user queries, ranked by a popularity score with time decay; blocked terms must never appear (a hard filter, not a ranking signal). Base popularity refreshes hourly; trending spikes should be visible within minutes. Latency budget: p99 under 100 ms end to end, which leaves ~20 ms in the service. Multi-language, per-locale suggestions.",
      "",
      "Cover: the data structure and its top-k tradeoff, how you shard, how snapshots roll out without downtime, and where trending freshness comes from.",
      "",
      "*Reported as: \"Design an Autocomplete feature for Pinterest\" (Roundz IC15 write-up — the candidate self-rated below average for missing \"social media scale specifics\"), \"Design Typeahead\" (1point3acres VO), \"typeahead box for a search engine\" (Exponent).*",
    ].join("\n"),
    hints: [
      "Size it before choosing a structure: ~100M distinct suggestible queries × 40 B ≈ 4 GB of strings, times 3–4 for per-node top-k lists. Tens of GB fits in RAM across a few shards — disk never belongs on the read path.",
      "Hash-sharding whole queries forces scatter-gather on every keystroke. Shard by prefix range so a lookup hits exactly one shard, then handle the skew ('s' vs 'x') with data-driven boundaries and per-shard replication.",
      "Incremental trie updates are the trap: a count change touches a list at every prefix node. Build snapshots offline, roll them out with an atomic pointer swap, and layer a tiny streaming delta on top for trends.",
    ],
    rubric: [
      "- **Traffic and memory math** — derives read QPS from searches × keystroke round trips (~300k peak) and concludes the whole index fits in RAM sharded; notes short prefixes dominate traffic and are edge-cacheable.",
      "- **Data structure tradeoff** — trie/FST with top-k per node (O(prefix) reads, expensive updates, L-times memory) vs sorted-array scans; resolves it with offline snapshot builds and capped top-k depth.",
      "- **Prefix sharding and skew** — shards by prefix range for single-shard lookups, with data-driven boundaries, deeper splits for hot prefixes, and replication weighted by traffic; shard map versioned with the snapshot.",
      "- **Freshness architecture** — hourly snapshot with time-decayed scores rolled out by atomic arena swap (instant rollback), plus a minute-level trending delta from a streaming top-k merged at query time; degradation when the streaming job dies is stale-not-broken.",
      "- **Product-scale specifics** — per-locale indexes, serve-time blocklist (takedowns without a rebuild), near-duplicate collapsing, click-through weighting, personalization as a rerank of global top-k (never a per-user index).",
      "- **Failure behavior** — fail open to fewer/no suggestions inside a tight deadline; replicas behind the shard map; the one unacceptable failure is being slow.",
    ].join("\n"),
    solution: [
      "## Numbers first",
      "",
      "Assume 2B searches/day across 640M MAU, ~4 server round trips per search after client debounce → 8B requests/day ≈ 93k QPS average, ~300k peak. Distinct queries worth suggesting: ~100M × 40 B ≈ 4 GB of strings; storing top-10 at every prefix node multiplies by 3–4×. Conclusion: the whole index is tens of GB — it lives in RAM across a handful of shards, and disk is never on the read path. Short prefixes (\"a\", \"ch\") are a tiny key space carrying a large traffic share → edge cache with a one-minute TTL and a near-100% hit rate.",
      "",
      "## API and data",
      "",
      "```",
      "GET /v1/suggest?q=cak&locale=en-US&n=10 → { suggestions:[{text, score}], version }",
      "cache-control: max-age=60 for len(q) ≤ 3, private otherwise",
      "",
      "Offline: search_log(query, locale, ts, user_id, clicked) → hourly agg (query, locale) → decayed_score",
      "Serving: trie / FST per locale shard; node = {children, top10: [(query_id, score)]}",
      "query_id → text table (dedup strings once)",
      "trending_delta(prefix → [(query, boost)])  -- small, refreshed every minute",
      "```",
      "",
      "## Read path",
      "",
      "Client debounces ~100 ms and cancels in-flight requests per keystroke. Prefixes of ≤3 chars come from the edge cache. Everything else hits the suggestion service, which maps the prefix to a shard, reads the precomputed top-k at that trie node, overlays the trending delta, drops blocklisted entries, optionally bubbles the user's own recent matching queries, and returns. Because every node stores its top-k, per-request work is one hash lookup plus a small merge no matter how many queries share the prefix.",
      "",
      "## Deep dive: the structure and its tradeoff",
      "",
      "A trie with top-k at every node gives O(prefix length) reads and zero scanning, but costs memory (each query appears in up to L nodes' lists) and makes incremental updates expensive (one count change touches L lists). A sorted array with binary search is compact and trivially updatable but scans everything sharing the prefix — catastrophic for \"s\". The snapshot design dissolves the dilemma: build offline where update cost is irrelevant, cap stored top-k at prefix lengths up to ~8 (longer prefixes have few completions and can scan), compress the string table. A finite-state transducer (what Lucene uses) is the production-grade version of the same idea.",
      "",
      "## Deep dive: sharding by prefix, not hash",
      "",
      "Hashing whole queries would spread one prefix's completions across every shard — scatter-gather per keystroke. Partition by prefix range so a lookup touches exactly one shard. The cost is skew: \"s\" carries far more than \"x\". Fixes: shard-map boundaries chosen from the data to balance size, hot prefixes split one level deeper (\"sa\", \"sh\", \"st\" as their own shards), read-heavy shards replicated more. The shard map is versioned with the snapshot so a rollout can rebalance.",
      "",
      "## Deep dive: freshness in two tiers",
      "",
      "Base scores use exponential time decay (half-life on the order of days) so last year's fad sinks without a cliff. The hourly job writes a versioned snapshot to object storage; each shard downloads its partition into a second memory arena and flips a pointer — readers never see a half-built index, and a bad build rolls back by flipping back. Trends that can't wait an hour come from a streaming job with a sliding 10-minute window (count-min sketch + a per-prefix top-k heap) writing a small delta the service merges at query time. If the streaming job dies, suggestions degrade to hourly freshness rather than failing.",
      "",
      "## What \"social media scale specifics\" means",
      "",
      "The gap the IC15 candidate named: tens of locales with separate indexes; the blocklist applied at serve time so a takedown is immediate without a rebuild; near-duplicate collapsing (\"cake recipe\" / \"cake recipes\") at build time; click-through weighting so typed-but-never-clicked queries decay faster; personalization as a rerank of the global top-k against the user's own history (a KV row fetched in parallel; a merge of two short lists, never a per-user index and no model call in the 20 ms budget). Pinterest's Dogmatix generates suggestion candidates from a term–query graph and a query–pin graph in parallel with the main search call, so suggestions never add latency to results.",
      "",
      "## Probes to expect",
      "",
      "- *A shard is down — what does the user see?* Retry once on a replica, then return edge-cached or empty. Failing open to \"no suggestions\" is fine; failing slow is not.",
      "- *Why not Elasticsearch's completion suggester?* It's an FST underneath and fine at modest scale, but you surrender control of top-k semantics, freshness cadence, delta merging, and per-shard memory — which are the actual problem.",
      "- *CJK / mid-word?* Tokenize per locale at build time and index each token's suffix as an entry point; memory roughly doubles, so restrict to locales that need it.",
    ].join("\n"),
  },
  {
    slug: "design-ads-event-reporting",
    title: "Design an Ads Event Reporting System",
    category: "system-design",
    difficulty: "hard",
    companies: ["pinterest"],
    summary:
      "Streaming for dashboards, batch for billing truth — and hot keys from viral ads.",
    prompt: [
      '"Design the system that ingests ad impression, click, and conversion events and serves advertiser reporting: impressions, clicks, spend, and conversions by campaign, ad group, and ad, over time, with near-real-time dashboards. Billing has to be exact."',
      "",
      "Two consumers with different contracts: dashboards want minute-level freshness and tolerate small later corrections; billing wants exactness and can wait hours. Dedup rules (one billable click per impression within 24 h, duplicate event ids dropped) change over time, so raw events must be kept. Mobile clients batch and retry, so events arrive hours late — conversions up to 30 days (the attribution window). Dimensions: advertiser → campaign → ad group → ad, plus time, country, device, placement. Ingestion must never block ad serving.",
      "",
      "Cover: where exactly-once actually matters and how you get it, event time and lateness, the click-to-impression join, hot keys from viral promoted pins, and how a billing bug gets backfilled.",
      "",
      '*Reported as: "Design an ads event reporting system — scalable, reliable event ingestion and analytics" (PracHub). Ads is Pinterest\'s revenue, and the ads marketplace is a named domain round.*',
    ].join("\n"),
    hints: [
      "Say the two-consumer split first — it is the whole design. Streaming feeds dashboards within a minute and may be slightly wrong; batch over exactly-once raw data owns billing truth and periodically overwrites the streaming aggregates.",
      "\"Exactly-once\" is a property of the pipeline, not a queue flag: idempotent producer + client event ids, checkpointed streaming state with an upsert sink, atomically committed batch partitions, and a ledger keyed by run id that replaces rather than increments.",
      "A viral promoted pin can be 5% of all impressions — one hot key. Pre-aggregate under (ad_id, salt), flush partials, merge keyed by ad_id; and partition the OLAP store by time, not advertiser.",
    ],
    rubric: [
      "- **The two-contract split** — leads with dashboards (fresh, approximately right) vs billing (exact, can wait), and derives the lambda shape: streaming for freshness, batch over raw events as truth that overwrites.",
      "- **Ingestion decoupling** — ad servers log locally and ship async (at-least-once) so serving survives pipeline incidents; raw events land exactly-once on cheap storage partitioned by time.",
      "- **Idempotency end to end** — client event ids, dedup with TTL state, upsert-by-(key, window) sinks, atomic batch commits, and a ledger keyed by (advertiser, day, run id) that replaces — so any stage can rerun for any day.",
      "- **Time and lateness** — event time with watermarks bounded by server receipt, a side output for very-late events handled by batch only, clicks buffered for the join window, 30-day conversion attribution done in batch, never in streaming state.",
      "- **Hot keys and OLAP layout** — salted two-stage aggregation for viral ads; OLAP partitioned by time with tiered rollups and retention; queries pick the coarsest satisfying granularity.",
      "- **Auditability** — lineage from ledger to raw events; backfill = rerun with a new run id, replaced rows, and the run-id diff as the audit artifact.",
    ].join("\n"),
    solution: [
      "## The split that is the design",
      "",
      "Dashboards and billing have incompatible contracts, so give them different paths and let one own truth. Numbers: assume 10B impressions/day (~115k/s avg, ~400k/s peak), clicks ~1%. Raw events at ~500 B → 5 TB/day; 90 days raw on object storage ≈ 450 TB, which is cheap. Aggregates: ~5M active ads × hourly buckets × ~10 dimension combos → ~1B rows/day → a columnar OLAP store with rollups. Query load is tiny (tens of thousands of advertisers); ingestion is the problem. And a viral promoted pin can be 5% of all impressions — one hot key.",
      "",
      "## Pipeline",
      "",
      "Ad servers and SDKs never write synchronously: they log to local disk and a host agent ships to Kafka at-least-once (Pinterest's spine: Singer → Kafka → Merced → S3, 150B+ messages/day by 2016, exactly-once into S3). Kafka is the fork:",
      "",
      "- **Streaming**: validate schema → drop duplicate event ids (keyed state, TTL) → join clicks to impressions (keyed by impression id, 24 h state TTL) → one-minute event-time aggregates with watermarks, **upserted** into OLAP by (key, minute) so reprocessing is idempotent. Dashboards read this within a minute.",
      "- **Batch** (hourly/daily over raw S3): invalid-traffic filtering, conversion attribution over the 30-day window, daily rollups, the billing ledger — and the daily job overwrites that day's OLAP segments so dashboards converge to billed truth.",
      "- A separate spend-pacing consumer tails the click topic and feeds near-real-time spend back to the ad server so campaigns don't overdeliver (Pinterest ran this on Kafka Streams).",
      "",
      "```",
      "event { event_id (client uuid), type, ad_id, impression_id, user_id_hash,",
      "        client_ts, server_ts, country, device, placement, bid_price_micros }",
      "OLAP rollup key: (ad_id, hour, country, device, placement) → {impr, clicks, spend, conv}",
      "Billing ledger:  (advertiser_id, day) → exact spend, with lineage to the batch run id",
      "```",
      "",
      "## Deep dive: exactly-once where it matters",
      "",
      "End-to-end exactly-once is a property of the whole pipeline: idempotent producer + client-generated event id; checkpointed streaming state with an idempotent sink (replay rewrites the same rows); batch partitions written to a staging prefix and committed atomically via manifest (Iceberg snapshot semantics if available) so a failed run leaves nothing half-written; a ledger keyed by (advertiser, day, run id) that **replaces, never increments**. With those four, duplication anywhere upstream is harmless and any stage can rerun for any day.",
      "",
      "## Deep dive: late and out-of-order events",
      "",
      "Use event time (client timestamp bounded by server receipt to defeat bad clocks) with watermarks; allow ~1 h lateness in streaming and route anything later to a side output only batch processes. The subtle join: a click can arrive before its delayed impression — buffer unmatched clicks in keyed state for the join window; a click still unmatched after it is invalid for billing but counted in raw clicks for debugging. Conversions (30-day window) never belong in streaming state; attribute in batch against history on S3.",
      "",
      "## Deep dive: hot keys",
      "",
      "Aggregating by ad id puts the viral ad on one partition. Pre-aggregate with (ad_id, salt 0–31), flush partials every few seconds, merge in a second stage keyed by ad_id — the hot key receives 32 small messages per flush instead of a firehose. The OLAP store needs the same care: partition by time, not advertiser, so a big advertiser doesn't own a shard. Pinterest's Aperture counting service adds a lesson worth repeating: store raw events in time buckets and compute counts at serve time, because dedup and attribution rules change and recomputing from raw is how you avoid migrations.",
      "",
      "## Serving and cost",
      "",
      "Tiered rollups (minute → hour → day) with tiered retention (7 d / 90 d / 2 y) bound the OLAP footprint; queries pick the coarsest granularity that satisfies the range; advertiser results cached for a minute; large exports go async to S3 with a notification.",
      "",
      "## Probes to expect",
      "",
      "- *Why both streaming and batch?* The alternative is one system that is either slow or wrong: streaming can't hold 30-day attribution state or rerun last month under a new dedup rule; batch can't do one-minute dashboards. Batch owns truth and overwrites.",
      "- *Kafka retention expired before a consumer recovered?* Replay from S3 raw — that's why the exactly-once landing exists. Size Kafka retention for the worst realistic outage, not forever.",
      "- *Backfill a month after a billing bug?* Rerun batch for those days under a new run id; ledger rows replaced, OLAP segments overwritten, and the run-id diff is the audit artifact for finance.",
      "- *Schema evolution?* Registry with backward-compatible changes only, plus a sanitization stage that quarantines invalid events so a bad client build can't poison aggregates.",
    ].join("\n"),
  },
];
