import type { Problem } from "./types";

// Database and distributed-systems concepts to explain in a minute each:
// storage and query-engine internals under SQL & Data, consensus and commit
// protocols under System Design. Document problems; the solution holds the
// answer.

const CLOSE = "Answer out loud in under a minute: a definition, one concrete example, and one pitfall or trade-off.";

const concept = (
  slug: string,
  title: string,
  category: "sql" | "system-design",
  summary: string,
  question: string,
  hint: string,
  solution: string[],
): Problem => ({
  slug,
  title,
  category,
  difficulty: "easy",
  companies: ["snowflake"],
  summary,
  prompt: [question, "", CLOSE].join("\n"),
  hints: [hint],
  solution: solution.join("\n"),
});

export const snowflakeConceptProblems: Problem[] = [
  concept(
    "mvcc-explained",
    "What Is MVCC?",
    "sql",
    "Writers create new versions instead of overwriting, so readers see a consistent snapshot without blocking writers.",
    "What is multi-version concurrency control, and what problem does it solve?",
    "Think about what a reader sees while a writer is halfway through a transaction, and how versions make that answer stable.",
    [
      "## The short version",
      "",
      "Writers create a new version of a row instead of overwriting it; each version is stamped with the transaction that created it. A reader works against a snapshot — the set of versions committed when it started — so it sees a consistent state without taking locks and without blocking writers.",
      "",
      "## Example",
      "",
      "A long report reads a table while a batch job updates it. Under MVCC the report sees the table as it was when the report began; the batch job's writes land as new versions and become visible to transactions that start afterwards.",
      "",
      "## Pitfall",
      "",
      "Old versions pile up and must be garbage-collected (vacuumed); a long-running reader pins versions and makes that collection wait. Snapshot isolation also permits write skew — two transactions each reading the other's row and writing their own — which serializable isolation prevents at extra cost.",
    ],
  ),
  concept(
    "lsm-tree-vs-b-tree",
    "LSM Tree vs B-Tree",
    "sql",
    "LSM buffers writes in memory and merges sorted files later; a B-tree updates in place for steadier reads.",
    "Compare an LSM tree with a B-tree as a storage engine. When would you pick each?",
    "Follow a single write and a single point read through both structures and count the disk operations.",
    [
      "## The short version",
      "",
      "An LSM tree appends writes to a log and an in-memory table, flushes sorted files to disk, and merges them in the background (compaction); a read may check several files, helped by Bloom filters. A B-tree updates pages in place, so reads are a predictable walk from the root and writes pay a random I/O.",
      "",
      "## Example",
      "",
      "An ingestion-heavy event store writes millions of rows an hour and reads recent ranges: LSM. A product catalogue read a thousand times per write with tight latency targets: B-tree.",
      "",
      "## Pitfall",
      "",
      "LSM compaction costs write amplification and can stall writes when it falls behind; B-trees fragment and pay for random writes. Neither is free — the choice is which cost matches the workload.",
    ],
  ),
  concept(
    "row-vs-columnar-storage",
    "Row vs Columnar Storage",
    "sql",
    "Rows suit point lookups and transactions; columns suit scans and aggregates and compress far better.",
    "What is the difference between row-oriented and column-oriented storage, and why does it matter for analytics?",
    "Think about which bytes a query over three columns of a hundred-column table has to read in each layout.",
    [
      "## The short version",
      "",
      "Row storage keeps all the fields of one record together, so fetching or updating a record touches one place. Columnar storage keeps all the values of one column together, so a query reads only the columns it references, and similar values sitting side by side compress very well.",
      "",
      "## Example",
      "",
      "`SELECT AVG(amount) FROM orders WHERE region = 'EU'` over a hundred-column table reads two columns in a columnar layout and every byte of every row in a row layout.",
      "",
      "## Pitfall",
      "",
      "Columnar stores are poor at single-row updates and point lookups, since a record is scattered across column files; they handle it with immutable files and rewrite-on-update, which is why they pair with batch or micro-batch ingestion.",
    ],
  ),
  concept(
    "vectorized-execution-explained",
    "What Is Vectorized Execution?",
    "sql",
    "Operators process batches of column values instead of one row at a time, cutting interpretation overhead and using CPU caches well.",
    "What is vectorized query execution, and why is it faster than row-at-a-time processing?",
    "Count how many function calls a filter makes over a million rows in each model.",
    [
      "## The short version",
      "",
      "A vectorized engine passes batches of column values — thousands at a time — between operators, and each operator runs a tight loop over the batch. Row-at-a-time (Volcano) execution calls `next()` once per row per operator, paying interpretation overhead on every call and defeating the CPU cache.",
      "",
      "## Example",
      "",
      "A filter `amount > 100` over a million rows is a million virtual calls in a row engine, and about a thousand loops over arrays of a thousand values in a vectorized one — loops the compiler can unroll and the CPU can run with SIMD instructions.",
      "",
      "## Pitfall",
      "",
      "Vectorization helps scans and aggregates and does little for operations that are inherently row-by-row, such as calling an opaque user-defined function; the batch size also trades cache fit against per-batch overhead.",
    ],
  ),
  concept(
    "write-ahead-log-explained",
    "What Is a Write-Ahead Log?",
    "sql",
    "Record the change durably before applying it, so a crash can be replayed.",
    "What is a write-ahead log, and how does it provide durability and crash recovery?",
    "Order the two writes — log entry and data page — and ask what a crash between them leaves behind.",
    [
      "## The short version",
      "",
      "Before a change touches the data structure, a record describing it is appended to a sequential log and flushed to stable storage. After a crash, the log is replayed to redo committed changes that never reached the data files, and to undo uncommitted ones. Sequential appends are cheap, so durability costs one flush per commit rather than a random write per page.",
      "",
      "## Example",
      "",
      "A transaction updates three pages. The three log records and a commit record are flushed; the pages are written later, lazily. If the machine dies before the pages are written, recovery replays the three records.",
      "",
      "## Pitfall",
      "",
      "The log grows forever unless checkpoints mark how far the data files have caught up; and `fsync` behaviour varies by file system and disk, so a log that is not actually flushed provides no durability at all.",
    ],
  ),
  concept(
    "transaction-isolation-levels",
    "Transaction Isolation Levels",
    "sql",
    "Read committed, repeatable read, snapshot, serializable — know which anomaly each permits.",
    "Name the transaction isolation levels and the anomaly each one permits.",
    "For each level, describe one interleaving of two transactions that produces a wrong result.",
    [
      "## The short version",
      "",
      "- **Read uncommitted** permits dirty reads of uncommitted data.",
      "- **Read committed** sees only committed data, but two reads in one transaction may differ (non-repeatable reads).",
      "- **Repeatable read** fixes a row once read, but new rows matching a predicate can appear (phantoms).",
      "- **Snapshot isolation** reads a consistent snapshot; it permits write skew, where two transactions each read what the other writes.",
      "- **Serializable** is equivalent to some serial order and permits none of these, at the cost of more aborts or locking.",
      "",
      "## Example",
      "",
      "Two doctors each check that at least one other doctor is on call and then go off call. Under snapshot isolation both reads succeed and both leave — write skew. Serializable aborts one.",
      "",
      "## Pitfall",
      "",
      'Databases name levels differently from the standard — some call snapshot isolation "repeatable read" — so ask what the engine actually guarantees rather than what the keyword says.',
    ],
  ),
  concept(
    "snowflake-three-layer-architecture",
    "Snowflake's Three Layers",
    "sql",
    "Database storage, independent compute warehouses, and a cloud services layer — a hybrid of shared-disk and shared-nothing.",
    "Describe Snowflake's architecture: what are its three layers, and what does separating them buy?",
    "Think about what happens when two teams run heavy queries on the same data at the same time.",
    [
      "## The short version",
      "",
      "Three layers. **Database storage** holds data reorganised into a compressed columnar format in micro-partitions. **Compute** is virtual warehouses: independent clusters that run queries and share no resources with each other. **Cloud services** coordinates everything — authentication, access control, metadata, query parsing and optimisation.",
      "",
      "It is a hybrid of shared-disk (one copy of the data, reachable by every warehouse) and shared-nothing (each warehouse's compute is its own). The consequence that matters: storage and compute scale separately, and many warehouses read the same data without contending.",
      "",
      "## Example",
      "",
      "A data-science team's warehouse runs a long training-set scan while the finance team's warehouse runs its month-end reports on the same tables; neither slows the other, and each is sized and billed on its own.",
      "",
      "## Pitfall",
      "",
      "Independence is not free: each warehouse warms its own local cache, and metadata operations go through the shared services layer, which is where cross-warehouse coordination lives.",
    ],
  ),
  concept(
    "micro-partitions-explained",
    "What Is a Micro-Partition?",
    "sql",
    "Immutable 50–500 MB columnar chunks created automatically, with per-column metadata that lets queries skip them.",
    "What is a micro-partition in Snowflake, and how does it make queries faster?",
    "Think about what a query with a date predicate needs to know about each file to skip it.",
    [
      "## The short version",
      "",
      "Tables are stored as micro-partitions: 50 MB to 500 MB of uncompressed data each, created automatically as data arrives, with columns stored independently inside. Every partition carries metadata per column — value ranges, distinct counts — so a query scans only the columns it references and prunes any partition whose range cannot match its predicate. Partitions are immutable; an update or delete writes new ones.",
      "",
      "## Example",
      "",
      "`WHERE order_date = '2026-03-01'` over a year of data: the engine reads the metadata, finds the handful of partitions whose date range covers that day, and never opens the rest.",
      "",
      "## Pitfall",
      "",
      "Pruning works only when a column's values are localised: data that arrives in random order leaves every partition covering the whole range. Clustering depth measures that overlap, and a clustering key reduces it — at the cost of background rewrites, since partitions are immutable.",
    ],
  ),
  concept(
    "two-phase-commit-explained",
    "Two-Phase Commit",
    "system-design",
    "Prepare on all participants, then commit; it blocks if the coordinator dies after prepare.",
    "What is two-phase commit, and what is its main weakness?",
    "Walk through a coordinator crash at each step and ask what the participants can safely do.",
    [
      "## The short version",
      "",
      "A coordinator asks every participant to **prepare** — do the work, write it durably, promise to commit on request — and, if all vote yes, tells them to **commit**; any no, or a timeout, becomes an abort. Participants that voted yes have given up the right to abort on their own.",
      "",
      "## Example",
      "",
      "Moving money between two banks' databases: both prepare the debit and the credit; the coordinator commits both; a crash on either side before prepare aborts cleanly.",
      "",
      "## Pitfall",
      "",
      "If the coordinator dies after participants have prepared, they are stuck holding locks until it returns — they cannot commit or abort safely. That blocking behaviour is why systems reach for consensus protocols or avoid distributed transactions with sagas and idempotent compensations.",
    ],
  ),
  concept(
    "raft-explained",
    "How Does Raft Work?",
    "system-design",
    "A leader replicates a log to a majority before committing; a new leader is elected by majority vote.",
    "Explain Raft: how is a leader chosen, how are entries committed, and what happens when the leader fails?",
    "Keep the two majorities in view: the one that elects a leader and the one that commits an entry must overlap.",
    [
      "## The short version",
      "",
      "Nodes are followers, candidates or a leader, and time is divided into terms. A follower that hears nothing from a leader becomes a candidate and asks for votes; a majority makes it leader for that term. The leader appends client commands to its log, replicates them to followers, and marks an entry committed once a majority has stored it; followers apply committed entries in order. Because any two majorities overlap, a new leader always holds every committed entry.",
      "",
      "## Example",
      "",
      "Five nodes; the leader replicates entry 7 to two followers and commits it. The leader then crashes. Any node that can win an election must have a log at least as up to date as a majority — so it has entry 7 — and the system continues without losing it.",
      "",
      "## Pitfall",
      "",
      "Raft trades availability for consistency: with a majority down, the cluster cannot commit. Writes also pay a round trip to a quorum, and a partitioned old leader can keep serving stale reads unless reads go through the quorum or a lease.",
    ],
  ),
];
