import type { Problem } from "./types";

// Apple front-end bank: JavaScript output-prediction questions, one snippet
// per problem. These are documents: predict, explain, then open the
// Solution. Every answer was re-run in Node. The React questions are in
// seed-apple-js-quiz-b.ts.

export const appleQuizProblems: Problem[] = [
  {
    slug: "promise-timer-order-quiz",
    title: "Predict the Output: Promise and Timer Order",
    category: "frontend",
    difficulty: "medium",
    companies: ["apple"],
    summary: "A promise resolved inside a timer, two more timers, and a microtask: the event loop decides the order.",
    prompt: [
      "What does this log, and in what order? Explain why.",
      "",
      "```js",
      "const p = new Promise((resolve) => {",
      "  console.log(1);",
      "  setTimeout(() => {",
      "    resolve();",
      "  });",
      "});",
      "",
      "Promise.resolve().then(() => console.log(2));",
      "setTimeout(() => console.log(3));",
      "p.then(() => console.log(4));",
      "setTimeout(() => console.log(5));",
      "```",
    ].join("\n"),
    hints: [
      "Sort each callback into one of two queues. Timers are tasks; promise callbacks and the code after an `await` are microtasks. After each task, every waiting microtask runs before the next task starts.",
      "The executor passed to `new Promise` runs synchronously.",
    ],
    solution: [
      "## Answer: `1, 2, 4, 3, 5`",
      "",
      "The executor runs synchronously, so 1 prints first. When the script ends, the microtask queue runs and prints 2. The first timer then resolves `p`, which queues its `then` callback as a microtask. **Microtasks drain after every task, so 4 prints before the next timer prints 3.**",
      "",
      "The loop in three steps: run one task (the script, a timer callback, an event handler), drain *all* microtasks (`then`, `catch` and `finally` callbacks, code after an `await`, `queueMicrotask`), render if a frame is due, then take the next task.",
    ].join("\n"),
  },
  {
    slug: "spread-shallow-copy-quiz",
    title: "Predict the Output: What a Spread Copies",
    category: "frontend",
    difficulty: "easy",
    companies: ["apple"],
    summary: "`{ ...first }` copies the top level only — a nested object stays shared.",
    prompt: [
      "What do the two `console.log` calls print? Explain why.",
      "",
      "```js",
      "let first = { name: \"Ada\", address: { city: \"Leeds\", country: \"UK\" } };",
      "let second = { ...first };",
      "first.name = \"Grace\";",
      "first.address.city = \"York\";",
      "console.log(first);",
      "console.log(second);",
      "```",
    ].join("\n"),
    hints: [
      "A spread copies the top-level properties. A nested object is copied as a reference, not as a new object.",
    ],
    solution: [
      "## Answer: `first` is Grace in York; `second` is still Ada, but also in York",
      "",
      "Spread copies top-level properties by value. `address` is a reference, so both objects share one address object. `structuredClone(first)`, or [a `cloneDeep`](/problems/implement-clone-deep), breaks the link.",
    ].join("\n"),
  },
  {
    slug: "arrow-method-this-quiz",
    title: "Predict the Output: `this` in an Arrow Method",
    category: "frontend",
    difficulty: "easy",
    companies: ["apple"],
    summary: "An arrow function takes `this` from where it is defined — and an object literal is not a scope.",
    prompt: [
      "What do the two lines print? Explain why.",
      "",
      "```js",
      "const shape = {",
      "  radius: 10,",
      "  diameter() {",
      "    return this.radius * 2;",
      "  },",
      "  perimeter: () => 2 * Math.PI * this.radius,",
      "};",
      "",
      "console.log(shape.diameter());",
      "console.log(shape.perimeter());",
      "```",
    ].join("\n"),
    hints: [
      "A regular method gets `this` from the call site. An arrow function has no `this` of its own.",
    ],
    solution: [
      "## Answer: `20`, then `NaN`",
      "",
      "An arrow function takes `this` from where it is defined, and an object literal is not a scope. In a classic script that outer `this` is `window`, so `this.radius` is `undefined` and the product is `NaN`. **In an ES module the second line throws a `TypeError` instead**, because top-level `this` is `undefined`. Naming that difference is the stronger answer.",
    ].join("\n"),
  },
  {
    slug: "temporal-dead-zone-quiz",
    title: "Predict the Output: The Temporal Dead Zone",
    category: "frontend",
    difficulty: "easy",
    companies: ["apple"],
    summary: "A block-scoped `const` shadows the outer one from the top of its block — before its line runs.",
    prompt: [
      "What happens when `foo()` runs? Explain why.",
      "",
      "```js",
      "function foo() {",
      "  const bar = \"bar\";",
      "  if (true) {",
      "    console.log(bar);",
      "    const bar = \"bar1\";",
      "  }",
      "}",
      "foo();",
      "```",
    ].join("\n"),
    hints: [
      "`let` and `const` are hoisted to the top of their block, but they can't be read until their declaration line has run.",
    ],
    solution: [
      "## Answer: `ReferenceError: Cannot access 'bar' before initialization`",
      "",
      "The inner `const bar` is hoisted to the top of its block but stays uninitialized until its line runs. Inside the block the name refers to the inner `bar`, so the outer one is shadowed and unreachable.",
    ].join("\n"),
  },
  {
    slug: "then-finally-chain-quiz",
    title: "Predict the Output: A then and finally Chain",
    category: "frontend",
    difficulty: "medium",
    companies: ["apple"],
    summary: "A promise settles once, `finally` passes values through, and a rejection handler can recover.",
    prompt: [
      "The executor calls both `reject` and `resolve`. What does the chain log? Explain why.",
      "",
      "```js",
      "const p = new Promise((resolve, reject) => {",
      "  reject(\"first\");",
      "  resolve(\"second\");",
      "});",
      "",
      "p.finally(() => {",
      "  console.log(\"finally 1\");",
      "  return \"ignored\";",
      "})",
      "  .then(",
      "    (v) => console.log(\"then\", v),",
      "    (e) => {",
      "      console.log(\"caught\", e);",
      "      return \"recovered\";",
      "    },",
      "  )",
      "  .finally(() => console.log(\"finally 2\"))",
      "  .then((v) => console.log(\"then\", v));",
      "```",
    ].join("\n"),
    hints: [
      "A promise settles once: whichever of `resolve` or `reject` runs first wins.",
      "`finally` receives no argument and its return value is discarded, unless it throws or returns a rejected promise.",
    ],
    solution: [
      "## Answer: `finally 1`, `caught first`, `finally 2`, `then recovered`",
      "",
      "- A promise settles once. The later `resolve` is ignored.",
      "- `finally` receives no argument, and its return value is discarded. The original value or reason passes through.",
      "- `finally` changes the outcome only if it throws or returns a rejected promise.",
      "- A rejection handler that returns normally turns the chain back to fulfilled.",
    ].join("\n"),
  },
  {
    slug: "var-hoisting-shadowing-quiz",
    title: "Predict the Output: var Hoisting With Shadowing",
    category: "frontend",
    difficulty: "easy",
    companies: ["apple"],
    summary: "A `var` inside the function is hoisted and initialized to `undefined`, shadowing the outer one.",
    prompt: [
      "What does `logIt()` print? Explain why.",
      "",
      "```js",
      "var text = \"outside\";",
      "function logIt() {",
      "  console.log(text);",
      "  var text = \"inside\";",
      "}",
      "logIt();",
      "```",
    ].join("\n"),
    hints: [
      "`var` declarations are hoisted to the top of the function and initialized to `undefined`.",
    ],
    solution: [
      "## Answer: `undefined`",
      "",
      "The inner `var text` is hoisted to the top of `logIt` and initialized to `undefined`, shadowing the outer variable. With `let` or `const` the same code would throw a `ReferenceError` instead — the temporal dead zone.",
    ].join("\n"),
  },
  {
    slug: "type-coercion-quiz",
    title: "Predict the Result: Type Coercion",
    category: "frontend",
    difficulty: "medium",
    companies: ["apple"],
    summary: "What adding \"0\" to a number does, and a table of `+`, `==` and comparison gotchas.",
    prompt: [
      "What happens when you add `\"0\"` to a number? Evaluate each expression:",
      "",
      "```js",
      "1 + \"0\"            1 - \"0\"            1 + +\"0\"           \"5\" * \"2\"",
      "1 + null           1 + undefined      true + true        [] + {}",
      "[1, 2, 3] + [4]    0 == \"\"            \"0\" == \"\"          null == 0",
      "null == undefined  [] == ![]          \"10\" > \"9\"         10 > \"9\"",
      "0.1 + 0.2 === 0.3  NaN === NaN        typeof null",
      "```",
    ].join("\n"),
    hints: [
      "`+` concatenates as soon as either side becomes a string; every other arithmetic operator converts to numbers.",
      "Under `==`, `null` equals only `undefined`, and objects are converted to primitives before comparing.",
    ],
    solution: [
      "## Answer",
      "",
      "The rule behind all of them: `+` concatenates if either side becomes a string, and every other arithmetic operator converts to numbers.",
      "",
      "| Expression | Result | Expression | Result |",
      "|---|---|---|---|",
      "| `1 + \"0\"` | `\"10\"` | `\"0\" == \"\"` | `false` |",
      "| `1 - \"0\"` | `1` | `null == 0` | `false` |",
      "| `1 + +\"0\"` | `1` | `null == undefined` | `true` |",
      "| `\"5\" * \"2\"` | `10` | `[] == ![]` | `true` |",
      "| `1 + null` | `1` | `\"10\" > \"9\"` | `false` |",
      "| `1 + undefined` | `NaN` | `10 > \"9\"` | `true` |",
      "| `true + true` | `2` | `0.1 + 0.2 === 0.3` | `false` |",
      "| `[] + {}` | `\"[object Object]\"` | `NaN === NaN` | `false` |",
      "| `[1, 2, 3] + [4]` | `\"1,2,34\"` | `typeof null` | `\"object\"` |",
      "| `0 == \"\"` | `true` | | |",
      "",
      "Two strings compare character by character, so `\"10\" > \"9\"` is false. `null` equals only `undefined` under `==`. `[] == ![]` is true because `![]` is `false`, and both sides then become `0`.",
    ].join("\n"),
  },
  {
    slug: "async-await-ordering-quiz",
    title: "Predict the Output: async/await and the Microtask Queue",
    category: "frontend",
    difficulty: "medium",
    companies: ["apple"],
    summary: "An async function runs synchronously up to its first await; the rest is a microtask.",
    prompt: [
      "What does this log, and in what order? Explain why.",
      "",
      "```js",
      "async function a() {",
      "  console.log(\"a1\");",
      "  await null;",
      "  console.log(\"a2\");",
      "}",
      "console.log(\"start\");",
      "setTimeout(() => console.log(\"timeout\"), 0);",
      "a();",
      "Promise.resolve().then(() => console.log(\"then 1\")).then(() => console.log(\"then 2\"));",
      "queueMicrotask(() => console.log(\"microtask\"));",
      "console.log(\"end\");",
      "```",
    ].join("\n"),
    hints: [
      "Sort each callback into one of two queues. Timers are tasks; promise callbacks and the code after an `await` are microtasks. After each task, every waiting microtask runs before the next task starts.",
      "An `async` function runs synchronously until its first `await`.",
    ],
    solution: [
      "## Answer: `start, a1, end, a2, then 1, microtask, then 2, timeout`",
      "",
      "An `async` function runs synchronously up to its first `await`; the rest of it is a microtask queued before `then 1`.",
    ].join("\n"),
  },
  {
    slug: "var-let-loop-closure-quiz",
    title: "Predict the Output: var and let in a Loop With Timers",
    category: "frontend",
    difficulty: "easy",
    companies: ["apple"],
    summary: "`var` gives the loop one shared binding; `let` gives each iteration its own.",
    prompt: [
      "What do the timers log? Explain why.",
      "",
      "```js",
      "for (var i = 0; i < 3; i++) setTimeout(() => console.log(\"var\", i));",
      "for (let j = 0; j < 3; j++) setTimeout(() => console.log(\"let\", j));",
      "```",
    ].join("\n"),
    hints: [
      "The callbacks run after both loops finish. Ask which variable each closure sees at that point.",
    ],
    solution: [
      "## Answer: `var 3` three times, then `let 0, let 1, let 2`",
      "",
      "`var` gives the loop one shared binding. `let` gives each iteration its own, and each closure keeps the one it was created in.",
    ].join("\n"),
  },
];
