import type { Problem } from "./types";

// Apple front-end bank (the JavaScript interview guide, 2026): the
// output-prediction quiz, split into a JavaScript and a React document.
// Most snippets come from one 60-minute online screen (Medium, Jul 2025).
// These are documents: predict, explain, then open the Solution. Every
// answer was re-run in Node.

export const appleQuizProblems: Problem[] = [
  {
    slug: "javascript-output-quiz",
    title: "JavaScript Output Quiz: Promises, Scope, and this",
    category: "frontend",
    difficulty: "medium",
    companies: ["apple"],
    summary:
      "Six reported snippets and a coercion round: the event loop, shallow copies, `this` and hoisting. Predict, then explain.",
    prompt: [
      "Six snippets and one round of coercion questions, reported from Apple screens. Snippets 1 to 5 come from a single 60-minute online screen in July 2025. For each, predict the output, then say *why*. The explanation is what an interviewer listens for. The answers are in the Solution section, and two practice drills on the same topics follow at the end.",
      "",
      "## 1. Promise and timer order",
      "",
      "```js",
      "const p = new Promise((resolve) => {",
      "  console.log(1);",
      "  setTimeout(() => {",
      "    resolve();",
      "  });",
      "});",
      "",
      "Promise.resolve().then(() => console.log(2));",
      "setTimeout(() => console.log(3));",
      "p.then(() => console.log(4));",
      "setTimeout(() => console.log(5));",
      "```",
      "",
      "## 2. Spread is a copy of what, exactly?",
      "",
      "```js",
      "let first = { name: \"Ada\", address: { city: \"Leeds\", country: \"UK\" } };",
      "let second = { ...first };",
      "first.name = \"Grace\";",
      "first.address.city = \"York\";",
      "console.log(first);",
      "console.log(second);",
      "```",
      "",
      "## 3. `this` in an arrow method",
      "",
      "```js",
      "const shape = {",
      "  radius: 10,",
      "  diameter() {",
      "    return this.radius * 2;",
      "  },",
      "  perimeter: () => 2 * Math.PI * this.radius,",
      "};",
      "",
      "console.log(shape.diameter());",
      "console.log(shape.perimeter());",
      "```",
      "",
      "## 4. The temporal dead zone",
      "",
      "```js",
      "function foo() {",
      "  const bar = \"bar\";",
      "  if (true) {",
      "    console.log(bar);",
      "    const bar = \"bar1\";",
      "  }",
      "}",
      "foo();",
      "```",
      "",
      "## 5. A `then` and `finally` chain",
      "",
      "The screen had a chain mixing `then` and `finally` on a promise whose executor called both `reject` and `resolve`. The exact code wasn't published; this one exercises the same rules.",
      "",
      "```js",
      "const p = new Promise((resolve, reject) => {",
      "  reject(\"first\");",
      "  resolve(\"second\");",
      "});",
      "",
      "p.finally(() => {",
      "  console.log(\"finally 1\");",
      "  return \"ignored\";",
      "})",
      "  .then(",
      "    (v) => console.log(\"then\", v),",
      "    (e) => {",
      "      console.log(\"caught\", e);",
      "      return \"recovered\";",
      "    },",
      "  )",
      "  .finally(() => console.log(\"finally 2\"))",
      "  .then((v) => console.log(\"then\", v));",
      "```",
      "",
      "## 6. `var` hoisting with shadowing",
      "",
      "```js",
      "var text = \"outside\";",
      "function logIt() {",
      "  console.log(text);",
      "  var text = \"inside\";",
      "}",
      "logIt();",
      "```",
      "",
      "## 7. \"What happens when you add '0' to a number?\"",
      "",
      "A senior candidate described a round of gotchas like this one. Evaluate each expression:",
      "",
      "```js",
      "1 + \"0\"            1 - \"0\"            1 + +\"0\"           \"5\" * \"2\"",
      "1 + null           1 + undefined      true + true        [] + {}",
      "[1, 2, 3] + [4]    0 == \"\"            \"0\" == \"\"          null == 0",
      "null == undefined  [] == ![]          \"10\" > \"9\"         10 > \"9\"",
      "0.1 + 0.2 === 0.3  NaN === NaN        typeof null",
      "```",
      "",
      "## Practice drills",
      "",
      "The same screen's 20 multiple-choice questions covered closures, prototypes, `async`/`await`, the event loop and the DOM, and none were published. These two drills are practice on those topics, not reported questions.",
      "",
      "```js",
      "async function a() {",
      "  console.log(\"a1\");",
      "  await null;",
      "  console.log(\"a2\");",
      "}",
      "console.log(\"start\");",
      "setTimeout(() => console.log(\"timeout\"), 0);",
      "a();",
      "Promise.resolve().then(() => console.log(\"then 1\")).then(() => console.log(\"then 2\"));",
      "queueMicrotask(() => console.log(\"microtask\"));",
      "console.log(\"end\");",
      "```",
      "",
      "```js",
      "for (var i = 0; i < 3; i++) setTimeout(() => console.log(\"var\", i));",
      "for (let j = 0; j < 3; j++) setTimeout(() => console.log(\"let\", j));",
      "```",
      "",
      "*Reported in: a 60-minute online screen for a Frontend Engineer role in Hyderabad (Medium, Jul 2025), for snippets 1 to 5; Glassdoor (Oct 2017) for snippet 6; Blind, undated, for the coercion round.*",
    ].join("\n"),
    hints: [
      "For every async snippet, sort each callback into one of two queues. Timers are tasks; promise callbacks and the code after an `await` are microtasks. After each task, every waiting microtask runs before the next task starts.",
      "A spread copies the top-level properties. A nested object is copied as a reference, not as a new object.",
      "`+` concatenates as soon as either side becomes a string; every other arithmetic operator converts to numbers.",
    ],
    solution: [
      "## 1. Promise and timer order: `1, 2, 4, 3, 5`",
      "",
      "The executor runs synchronously, so 1 prints first. When the script ends, the microtask queue runs and prints 2. The first timer then resolves `p`, which queues its `then` callback as a microtask. **Microtasks drain after every task, so 4 prints before the next timer prints 3.**",
      "",
      "The loop in three steps: run one task (the script, a timer callback, an event handler), drain *all* microtasks (`then`, `catch` and `finally` callbacks, code after an `await`, `queueMicrotask`), render if a frame is due, then take the next task. Snippets 1 and 5 and the first drill all reduce to this loop.",
      "",
      "## 2. Shallow copy: `first` is Grace in York; `second` is still Ada, but also in York",
      "",
      "Spread copies top-level properties by value. `address` is a reference, so both objects share one address object. `structuredClone(first)`, or [a `cloneDeep`](/problems/implement-clone-deep), breaks the link.",
      "",
      "## 3. `this` in an arrow method: `20`, then `NaN`",
      "",
      "An arrow function takes `this` from where it is defined, and an object literal is not a scope. In a classic script that outer `this` is `window`, so `this.radius` is `undefined` and the product is `NaN`. **In an ES module the second line throws a `TypeError` instead**, because top-level `this` is `undefined`. Naming that difference is the stronger answer.",
      "",
      "## 4. The temporal dead zone: `ReferenceError: Cannot access 'bar' before initialization`",
      "",
      "The inner `const bar` is hoisted to the top of its block but stays uninitialized until its line runs. Inside the block the name refers to the inner `bar`, so the outer one is shadowed and unreachable. As reported, the snippet never called `foo`, and without the call nothing is logged at all; the call is added here.",
      "",
      "## 5. The chain: `finally 1`, `caught first`, `finally 2`, `then recovered`",
      "",
      "- A promise settles once. The later `resolve` is ignored.",
      "- `finally` receives no argument, and its return value is discarded. The original value or reason passes through.",
      "- `finally` changes the outcome only if it throws or returns a rejected promise.",
      "- A rejection handler that returns normally turns the chain back to fulfilled.",
      "",
      "## 6. `var` hoisting: `undefined`",
      "",
      "The inner `var text` is hoisted to the top of `logIt` and initialized to `undefined`, shadowing the outer variable. Compare with snippet 4: `var` gives `undefined`, while `let` and `const` throw.",
      "",
      "## 7. Coercion",
      "",
      "The rule behind all of them: `+` concatenates if either side becomes a string, and every other arithmetic operator converts to numbers.",
      "",
      "| Expression | Result | Expression | Result |",
      "|---|---|---|---|",
      "| `1 + \"0\"` | `\"10\"` | `\"0\" == \"\"` | `false` |",
      "| `1 - \"0\"` | `1` | `null == 0` | `false` |",
      "| `1 + +\"0\"` | `1` | `null == undefined` | `true` |",
      "| `\"5\" * \"2\"` | `10` | `[] == ![]` | `true` |",
      "| `1 + null` | `1` | `\"10\" > \"9\"` | `false` |",
      "| `1 + undefined` | `NaN` | `10 > \"9\"` | `true` |",
      "| `true + true` | `2` | `0.1 + 0.2 === 0.3` | `false` |",
      "| `[] + {}` | `\"[object Object]\"` | `NaN === NaN` | `false` |",
      "| `[1, 2, 3] + [4]` | `\"1,2,34\"` | `typeof null` | `\"object\"` |",
      "| `0 == \"\"` | `true` | | |",
      "",
      "Two strings compare character by character, so `\"10\" > \"9\"` is false. `null` equals only `undefined` under `==`. `[] == ![]` is true because `![]` is `false`, and both sides then become `0`.",
      "",
      "## Drills",
      "",
      "- **First drill:** `start, a1, end, a2, then 1, microtask, then 2, timeout`. An `async` function runs synchronously up to its first `await`; the rest of it is a microtask queued before `then 1`.",
      "- **Second drill:** `var 3` three times, then `let 0, let 1, let 2`. `var` gives the loop one shared binding. `let` gives each iteration its own, and each closure keeps the one it was created in.",
    ].join("\n"),
  },
  {
    slug: "react-output-quiz",
    title: "React Output Quiz: Reducers, Context, and Effects",
    category: "frontend",
    difficulty: "medium",
    companies: ["apple"],
    summary:
      "A reducer traced by hand, three context providers deep, and the reported multiple-choice questions on effects and context.",
    prompt: [
      "Four React questions from front-end screens. Predict or choose, then explain. The answers are in the Solution section.",
      "",
      "## 1. Redux reducer state",
      "",
      "What is the state after the three dispatches?",
      "",
      "```js",
      "const initialState = { foo: [1], switch: false };",
      "",
      "function FooReducer(state = initialState, action) {",
      "  switch (action.type) {",
      "    case \"SET_FOO\":",
      "      return Object.assign({}, state, { foo: action.foo, switch: true });",
      "    case \"PUSH_FOO\":",
      "      return Object.assign({}, state, {",
      "        foo: [...state.foo, action.foo],",
      "        switch: !state.switch,",
      "      });",
      "    default:",
      "      return state;",
      "  }",
      "}",
      "",
      "dispatch({ type: \"SET_FOO\", foo: [1, 2] });",
      "dispatch({ type: \"PUSH_FOO\", foo: 3 });",
      "dispatch({ type: \"PUSH_FOO\", foo: 6 });",
      "```",
      "",
      "## 2. `useContext` output",
      "",
      "An IC3 technical round opened with a React snippet using `useContext` and asked for its output. The snippet wasn't published; this one covers the three rules it can test. What does it render?",
      "",
      "```jsx",
      "const Theme = createContext(\"light\");",
      "",
      "const Label = memo(function Label() {",
      "  return <span>{useContext(Theme)} </span>;",
      "});",
      "",
      "function App() {",
      "  return (",
      "    <>",
      "      <Label />",
      "      <Theme.Provider value=\"dark\">",
      "        <Label />",
      "        <Theme.Provider value=\"blue\">",
      "          <Label />",
      "        </Theme.Provider>",
      "      </Theme.Provider>",
      "    </>",
      "  );",
      "}",
      "```",
      "",
      "## 3. Fetching data when a component loads",
      "",
      "Which effect loads the users once, when `Users` first renders? The four reported options weren't published; these follow the wrong answers this question always offers.",
      "",
      "```jsx",
      "// A",
      "useEffect(() => {",
      "  fetch(\"/api/users\").then((res) => res.json()).then(setUsers);",
      "});",
      "",
      "// B",
      "useEffect(async () => {",
      "  const res = await fetch(\"/api/users\");",
      "  setUsers(await res.json());",
      "}, []);",
      "",
      "// C",
      "useEffect(() => {",
      "  fetch(\"/api/users\").then((res) => res.json()).then(setUsers);",
      "}, []);",
      "",
      "// D: no effect at all, in the component body",
      "fetch(\"/api/users\").then((res) => res.json()).then(setUsers);",
      "```",
      "",
      "## 4. Which statement about context is correct in React 16.3 and later?",
      "",
      "- A. Context can only be accessed in class components, using `this.context`.",
      "- B. A React context is created with `React.createContext()`.",
      "- C. The only way to access context in function components is the `Consumer` component.",
      "- D. Context values must always be primitive data types.",
      "",
      "*Reported in: the same 60-minute online screen as the JavaScript quiz (Medium, Jul 2025), for questions 1, 3 and 4; an IC3 technical round (Medium and LeetCode, 2025) for question 2.*",
    ].join("\n"),
    hints: [
      "Trace the reducer one action at a time, and read the case labels character by character.",
      "For context: which provider is nearest above each `Label`, and what does `memo` do, or not do, when a context value changes?",
      "An effect with no dependency array runs after every render. An `async` function returns a promise, and React expects an effect to return a cleanup function or nothing.",
    ],
    solution: [
      "## 1. The reducer: `{ foo: [1, 2, 3, 6], switch: true }`",
      "",
      "`switch` goes true on the set, false on the first push, and true on the second. **The candidate's own write-up gives `switch: false`, which is wrong**; running the reducer confirms `true`.",
      "",
      "The write-up also prints the case labels as `'SET FOO'`, with a space, while the actions use `'SET_FOO'`. If the real question had that mismatch, every action falls through to `default` and the state stays `{ foo: [1], switch: false }`. Read case labels character by character.",
      "",
      "## 2. Context: `light dark blue`",
      "",
      "- The default passed to `createContext` applies only when no provider is above the component.",
      "- The nearest provider wins.",
      "- **`memo` does not block context updates.** Every consumer re-renders when its provider's value changes by `Object.is`, so an inline object as `value` re-renders every consumer on every parent render. That is the bridge to the `useMemo` and `useCallback` follow-ups the candidate got.",
      "",
      "## 3. The effect: C",
      "",
      "- **A** has no dependency array, so it runs after every render. The state update causes a render, which runs the effect again: a loop.",
      "- **B** passes an `async` function directly. It returns a promise where React expects a cleanup function. Define the async function inside the effect and call it.",
      "- **D** fetches in the render body, so every render starts another request.",
      "- In real code, C also ignores a response that arrives after unmount: set a flag, or abort with an `AbortController`, in the effect's cleanup.",
      "",
      "## 4. Context: B",
      "",
      "A is wrong: `useContext` and `Consumer` work outside classes. C is wrong: `useContext` exists. D is wrong: any value works, objects and functions included.",
    ].join("\n"),
  },
];
