import type { Problem } from "./types";

// Apple system-design prompts reported for Software Engineer loops (PracHub's
// Apple list, 2025–2026), part D: disk-based inventory serving, the
// digit-square (happy number) service at scale, and a video sharing platform.
// Prompts are restated in our own words.

export const appleDesignProblemsD: Problem[] = [
  {
    slug: "design-disk-based-inventory",
    title: "Design Disk-Based Inventory Serving",
    category: "system-design",
    difficulty: "hard",
    companies: ["apple"],
    summary:
      "No SSD, little RAM: count seeks, make writes sequential, and keep the hot counters — not the metadata — in memory.",
    prompt: [
      "Design the software for a single machine that serves inventory requests. The machine has **spinning disks only — no SSD — and a small amount of RAM**.",
      "",
      "Records are keyed by item id and hold an available quantity, a reserved quantity, and descriptive metadata. The service must support reads, updates, and **conditional reservations**: reserve one unit only if the available quantity is greater than zero, without ever overselling — including across a crash.",
      "",
      "Discuss the on-disk data layout, the indexing strategy, what you cache and why, the write path, the read path, how a reservation stays atomic and durable, recovery, and how you keep latency acceptable given what a disk head can do.",
      "",
      "*Reported as: inventory serving on a machine with no SSD and little RAM (PracHub, Apple Software Engineer technical screen, senior, Oct 2025).*",
    ].join("\n"),
    hints: [
      "Start from the physics: a 7200 rpm disk does roughly 100–150 random operations a second (8–10 ms each) but 100+ MB/s sequentially. The design goal is at most one seek per read and zero seeks per write.",
      "Separate what changes from what is big. Quantities are a few bytes and change constantly; metadata is large and nearly static. Fixed-width counter records can be addressed directly by offset, so they need no in-memory index at all.",
      "Writes go to an append-only log with group commit and are applied to the data file later in one sorted sweep. A reservation is a check against the in-memory value plus a log append, owned by a single writer per partition.",
    ],
    rubric: [
      "- **Reasons from disk physics** — quotes seek time, random operations per second and sequential throughput, and derives the goals: one seek per read, sequential-only writes, group commit.",
      "- **Data layout** — separates small, hot, fixed-width quantity records from large, cold metadata; explains placement across spindles and why fixed-width records help.",
      "- **Indexing within the RAM budget** — sizes a full in-memory index and rejects or justifies it; offers direct addressing, an on-disk hash table, or a sparse index over sorted blocks, with bloom filters for misses.",
      "- **Write path and durability** — append-only log, group commit with a stated latency cost, in-memory dirty table, batched sorted apply or compaction, checksums, checkpoints and replay on restart.",
      "- **Atomic conditional reservation** — single writer per partition or equivalent, check-and-decrement against the authoritative in-memory value, durable before acknowledging, idempotent under client retries; never oversells across a crash.",
      "- **Caching and latency management** — caches hot counters rather than metadata, argues hit rate from skew, schedules I/O (dedicated log disk, elevator ordering, background work throttled), and bounds queues to protect tail latency.",
    ].join("\n"),
    solution: [
      "## Start from what a disk can do",
      "",
      "A 7200 rpm drive: ~8–10 ms per random access, so ~100–150 random operations per second per spindle; ~100–200 MB/s sequentially. A rotation is ~8 ms, which is also the floor for a lone `fsync`. Two goals follow. **A read may cost at most one seek** — so finding a record cannot itself need a disk-resident index traversal. **A write may cost zero seeks** — so writes must be sequential appends, committed in groups.",
      "",
      "## Layout: split hot from big",
      "",
      "- **Counter file:** one fixed-width record per item — `item_id, available, reserved, version, metadata_offset` — about 32 bytes. For 100M items that is ~3 GB, contiguous.",
      "- **Metadata file:** append-only variable-length blobs, referenced by offset from the counter record, rewritten only when metadata changes.",
      "- **Write-ahead log:** append-only, ideally on its **own spindle** so its head never moves.",
      "",
      "The quantities are tiny and change constantly; metadata is large and almost static. Mixing them would make every hot update rewrite a cold kilobyte and would waste the little cache there is.",
      "",
      "## Indexing inside a small RAM budget",
      "",
      "A full hash index for 100M keys costs well over 1.5 GB — probably the whole machine. Fixed-width records avoid needing one: if ids are dense, `offset = id × record_size`; if they are sparse, the counter file is an on-disk open-addressed hash table, sized for ~70% load, where the home slot is computed from the id and a lookup is one read of one block in the common case. If range scans matter, keep the file sorted and hold a **sparse index** in RAM — one key per 64 KB block is only ~50k entries — for a binary search in memory plus one block read. A bloom filter (~1.2 bytes per key at 1% false positives) answers most lookups for unknown ids without touching the disk.",
      "",
      "## Read path",
      "",
      "Check the in-memory dirty table, then the counter cache, then one disk read. Metadata is a second seek only when the caller asks for it. Cache hit: microseconds. Miss: ~10 ms. RAID-1 mirroring lets either disk serve a read, which halves read queueing.",
      "",
      "## Write path",
      "",
      "1. Append the change to the log with a checksum and the client's request id.",
      "2. **Group commit:** flush every few milliseconds, or when the batch fills, so hundreds of writes share one rotation. The cost is ~5–10 ms added latency; the gain is thousands of writes per second instead of ~100.",
      "3. Update the in-memory dirty table (a million dirty counters is only ~32 MB) and acknowledge.",
      "4. Periodically apply: sort dirty records by file offset and write them in **one elevator sweep**, then record a checkpoint — the log position up to which the data file is current — and truncate the log.",
      "",
      "A torn page in the counter file is recoverable because the log still holds every change since the last checkpoint.",
      "",
      "## Conditional reservation",
      "",
      "Partition items by id and give each partition a **single writer thread**, so check-and-decrement needs no locks. The writer reads the authoritative value (dirty table, cache, or one disk read), and if `available > 0` appends a log record carrying the resulting values — `available − 1, reserved + 1, version + 1` — and acknowledges only after the group commit. Writing resulting values rather than deltas makes replay idempotent. The request id goes into the log and into a recent-requests table, so a client retry after a timeout returns the original outcome instead of reserving twice. After a crash, replay from the checkpoint rebuilds exactly the acknowledged state: nothing acknowledged is lost, and nothing is oversold.",
      "",
      "## What to cache",
      "",
      "Only counter records. Demand is skewed, so a few hundred megabytes holds many millions of 32-byte records and absorbs most reads; a CLOCK or LRU policy is enough. Hot items therefore reserve without any disk read — the log append is the only I/O. Caching kilobyte metadata would evict thousands of counters per entry.",
      "",
      "## Keeping latency acceptable",
      "",
      "Dedicate a spindle to the log; spread partitions across data disks to multiply random-read capacity; issue reads in elevator order; throttle the apply sweep and metadata compaction so they yield to foreground reads; bound the request queue and shed load early rather than letting a 10 ms seek become a 2-second queue. Publish the real numbers: cached read < 1 ms, uncached ~10 ms, write ~5–10 ms.",
      "",
      "## Recovery and integrity",
      "",
      "On restart, load the last checkpoint and replay the log, verifying per-record checksums and stopping at the first torn record. Scrub the counter file in the background to catch latent sector errors, which mirrored disks can repair.",
      "",
      "## Probes to expect",
      "",
      "- *Why not a B-tree?* Its upper levels fit in RAM, so reads are about one seek too — but in-place updates are random writes. With a log in front it works; the fixed-width file is simply cheaper.",
      "- *Why not a full LSM tree?* Reads may touch several sorted runs — several seeks — which is exactly what this hardware cannot afford; a single data file plus one in-memory delta keeps reads at one seek.",
      "- *Flash sale on one item?* It lives in memory; throughput is bounded by group commit, which is thousands per second.",
    ].join("\n"),
  },
  {
    slug: "design-digit-square-service",
    title: "Scale Digit-Square Convergence Requests",
    category: "system-design",
    difficulty: "medium",
    companies: ["apple"],
    summary:
      "One pass plus a 1,621-entry table makes compute free — so the design is about avoiding the network, not caching.",
    prompt: [
      "A service answers one question: given a positive integer `n`, repeatedly replace it with the sum of the squares of its decimal digits — does the sequence eventually reach 1? (This is the happy-number test.)",
      "",
      "Design the service for very high volume: billions of requests over time, low latency per request, and no expensive repeated computation for common inputs. You are given an observation to exploit: after a small number of transformations, any fixed-width integer collapses into a small numeric range.",
      "",
      "Cover: the per-request algorithm and its cost; what you precompute and how big it is; whether and where caching helps; the API, including batching; capacity planning; input validation; deployment and latency; and how you would test and monitor it.",
      "",
      "*Reported as: a high-volume service for the digit-square convergence operation (PracHub, Apple Software Engineer technical screen, senior, Oct 2025).*",
    ].join("\n"),
    hints: [
      "Bound the first step: a d-digit number maps to at most 81·d. For a 64-bit integer that is at most 1,620 — so after one pass every input lands in a range you can tabulate completely at start-up.",
      "Once the answer is one digit pass plus an array lookup, the computation costs tens of nanoseconds. Ask what a network hop to a shared cache costs by comparison.",
      "When compute is free, the request itself is the expense: think batching, connection reuse, immutable responses cached at the edge, or shipping the table to the caller.",
    ],
    rubric: [
      "- **Algorithmic insight with the bound** — derives that one transformation maps a d-digit input to at most 81·d, gives the concrete bound for 32- and 64-bit inputs, and handles arbitrarily long inputs with a second pass.",
      "- **Precomputation** — builds a complete table for the reduced range at start-up with cycle detection done once, states its size (kilobytes or a ~200-byte bitset), and notes that request time needs no cycle detection.",
      "- **Judgement about caching** — recognises that a distributed cache is slower than the computation; keeps state in-process; uses immutable HTTP caching at the edge or client-side evaluation where it actually removes work.",
      "- **API and protocol efficiency** — single and batch endpoints, compact encoding, persistent connections, and clear validation and error responses for non-positive or oversized inputs.",
      "- **Capacity and deployment** — converts billions per day into requests per second, sizes by network and TLS rather than CPU, stateless replicas behind a load balancer, regional placement, load shedding and rate limits.",
      "- **Verification and monitoring** — self-check of the table against brute force, property tests, latency percentiles, batch-size distribution, edge hit ratio, error rates.",
    ].join("\n"),
    solution: [
      "## The algorithm, and why it is nearly free",
      "",
      "The sum of squared digits of a d-digit number is at most 81·d. A 32-bit integer has at most 10 digits (≤ 810); a 64-bit integer at most 20 (≤ 1,620). So **after one transformation every fixed-width input lies in 1…1,620.** Precompute the answer for that whole range once:",
      "",
      "```",
      "LIMIT = 1620",
      "happy = [False] * (LIMIT + 1)",
      "for start in 1..LIMIT:",
      "    seen = {}; x = start",
      "    while x != 1 and x not in seen: seen.add(x); x = digit_square_sum(x)",
      "    happy[start] = (x == 1)          # every unhappy number falls into the cycle through 4",
      "",
      "is_happy(n) = happy[digit_square_sum(n)]    # one pass over <= 20 digits + one array read",
      "```",
      "",
      "The table is 1,621 booleans — about 1.6 KB, or a 203-byte bitset that lives in L1 cache. A request costs ~20 digit operations and one load: tens of nanoseconds, with no loop, no cycle detection and no allocation. For arbitrarily long decimal strings, read the digits as text: N digits give at most 81·N, and one more pass brings that under the table bound, so the table never grows.",
      "",
      "## What that does to the architecture",
      "",
      "The interesting conclusion is what *not* to build. A shared cache such as Redis costs a network round trip — hundreds of microseconds — to avoid tens of nanoseconds of arithmetic. It would be the slowest part of the system and its only failure mode. All state is the immutable in-process table; every replica is identical and stateless.",
      "",
      "With compute free, the request is the expense — parsing, TLS, framing, the network. So the levers are:",
      "",
      "- **Do not make the request at all.** The function is pure and the table is 203 bytes: ship it as a client library. Say this first; it is the honest optimum.",
      "- **Batch.** `POST /v1/happy:batch { numbers: [...] } → { results: [...] }` amortises per-request overhead across thousands of values; use a compact encoding (protobuf or packed integers) over persistent HTTP/2 or gRPC connections.",
      "- **Cache at the edge.** `GET /v1/happy/{n}` is immutable forever: `Cache-Control: public, max-age=31536000, immutable`. Popular inputs are answered by the CDN and never reach the origin. This is the caching that removes work.",
      "",
      "## Capacity",
      "",
      "One billion requests a day is ~12k/s; 50 billion is ~600k/s average, perhaps 2M/s at peak. A well-written server handles on the order of a million trivial requests per second per core-pair, bounded by packets and TLS, not arithmetic — so the fleet is tens of cores per region, sized from network throughput and connection counts, with headroom for one zone being down. Batching divides these numbers by the batch size.",
      "",
      "## API and validation",
      "",
      "Accept `n` as a decimal string to avoid big-integer parsing; reject zero, negatives, non-digits and anything longer than a configured maximum with `400`, and oversized batches with `413`. Responses are tiny: a boolean, or a bitset for a batch. Per-client rate limits protect the fleet from a runaway caller.",
      "",
      "## Deployment and latency",
      "",
      "Stateless replicas behind a layer-4 load balancer, deployed in every region callers live in, since the network is the whole latency budget. Prefer a runtime without long garbage-collection pauses or keep allocation off the hot path; shed load early under overload rather than queueing. Rollouts are trivial because there is no state to migrate.",
      "",
      "## Testing and monitoring",
      "",
      "At start-up, self-check the table against a brute-force implementation and refuse to serve on mismatch. Property tests: `is_happy(n) == brute(n)` for random values, and at the edges — 1, 7, the largest 64-bit value, the longest accepted string. Monitor requests per second, latency percentiles, batch-size distribution, edge hit ratio, rejects by reason, and connection churn.",
      "",
      "## Probes to expect",
      "",
      "- *Would an LRU of recent inputs help?* No — a hash lookup costs more than recomputing.",
      "- *Why does the sequence always terminate?* Anything ≥ 1,000 shrinks (81·d < n), so every sequence enters the small range, where it reaches 1 or the 8-cycle containing 4.",
      "- *What if the operation were expensive?* Then the answer flips: memoise shared sub-results in-process, consider a distributed cache, and coalesce identical in-flight requests.",
    ].join("\n"),
  },
  {
    slug: "design-video-sharing-platform",
    title: "Design a Video Sharing Platform",
    category: "system-design",
    difficulty: "hard",
    companies: ["apple"],
    summary:
      "A transcoding pipeline feeding a CDN: egress is the bill, so codec, ladder and cache strategy are the design.",
    prompt: [
      "Design a YouTube-like service: creators upload videos; the platform transcodes them into multiple bitrates, stores them across tiers, and delivers them through a CDN; viewers search, watch, like and comment; and a recommendations interface feeds the home page.",
      "",
      "Assume 100M daily viewers watching ~25 minutes a day and ~1M uploads a day averaging 100 MB.",
      "",
      "Cover: traffic and storage estimates; the ingestion pipeline from upload to playable, including thumbnails; the storage tiers; delivery, caching and adaptive bitrate; metadata, search indexing and engagement counters; the contract with the recommendation system; rate limiting; multi-region availability; encryption and DRM; and the cost trade-offs you would actually pull on.",
      "",
      "*Reported as: a YouTube-like video platform, one of two systems in a single onsite round (PracHub, Apple Software Engineer onsite, Sep 2025).*",
    ].join("\n"),
    hints: [
      "Estimate egress before anything else: 100M viewers × 25 minutes × a few megabits per second is tens of petabytes a day. Delivery cost dwarfs storage and compute, so CDN hit ratio and codec efficiency are first-order design decisions.",
      "Model ingestion as a workflow of idempotent tasks: split the source into segments, transcode segments in parallel per rendition, package, then publish. Make the video playable at a low rendition first and add the rest later.",
      "Views, likes and search are asynchronous by design: events go to a log, counters are aggregated off the request path, and the search index is fed by change data capture from the metadata store.",
    ],
    rubric: [
      "- **Estimates that drive the design** — upload volume, stored bytes after the rendition ladder, and daily egress; concludes that delivery dominates cost and that the API tier must never carry video bytes.",
      "- **Ingestion pipeline** — resumable direct-to-storage upload, a task workflow with segment-parallel transcoding, packaging for adaptive streaming, thumbnails, idempotent retries, and a publish state machine that goes live at the first usable rendition.",
      "- **Storage tiering** — treatment of sources versus renditions, hot versus long-tail content, lifecycle policies, and regenerate-versus-store decisions.",
      "- **Delivery** — adaptive bitrate with short immutable segments, multi-tier CDN with origin shielding, signed URLs, behaviour for long-tail misses and for large premieres.",
      "- **Metadata, search and engagement** — sharded metadata store, asynchronous counters with dedup, comment storage, a search index kept consistent by an event stream, and a clear contract with fallbacks for recommendations.",
      "- **Cross-cutting concerns** — rate limiting, multi-region strategy and failover, encryption and DRM, observability of quality of experience, and concrete cost levers such as codec choice by popularity.",
    ].join("\n"),
    solution: [
      "## Numbers",
      "",
      "Uploads: 1M/day × 100 MB = 100 TB/day of source. A rendition ladder (240p to 1080p or 4K) adds roughly 1–2× the source, so plan ~250 TB/day, ~90 PB/year before tiering. Viewing: 100M × 25 min × ~2.5 Mbps ≈ **47 PB of egress per day**. Storage and transcoding are real costs; egress is the dominant one. Read-to-write ratio in requests is thousands to one.",
      "",
      "## Ingestion",
      "",
      "```",
      "POST /videos                  -> { video_id, upload session }          metadata only",
      "PUT  <object-store part URLs>    resumable, direct to storage",
      "POST /videos/{id}:complete    -> 202, state = processing",
      "",
      "state: uploaded -> processing -> playable (first rendition) -> ready (full ladder) -> published | blocked",
      "```",
      "",
      "Upload-complete emits an event that starts a workflow: validate the container, scan, fingerprint for copyright matching, **split into GOP-aligned segments**, fan out transcode tasks per (segment, rendition) across a worker pool — spot capacity is fine because tasks are small and idempotent — then package to CMAF segments with HLS and DASH manifests, generate thumbnails and scrubbing sprites, and update state. Each task is keyed by `(video_id, rendition, segment)` so retries overwrite rather than duplicate; poison inputs go to a dead-letter queue with the reason surfaced to the creator. The video becomes playable as soon as one low rendition is complete — minutes, not the hour a 4K encode takes.",
      "",
      "## Storage tiers",
      "",
      "Sources move to an archival tier once processing succeeds (kept for re-encoding when a better codec arrives). Renditions of recent and popular videos stay on the hot tier; the long tail keeps only a reduced ladder on a cheaper tier, and rare renditions are produced on demand and cached. Lifecycle policies are driven by view counts, not just age.",
      "",
      "## Delivery",
      "",
      "Players use adaptive bitrate: a manifest lists renditions, segments are 2–6 seconds, and the player switches rendition per segment according to measured throughput. Segment URLs are **immutable**, so they cache indefinitely. The CDN is tiered — edge, regional, then an origin shield in front of object storage — so a miss on the long tail costs one origin fetch per region, not one per edge. Premieres are pre-warmed. Access uses short-lived signed URLs or tokens; premium content is encrypted at packaging time (common encryption) with keys issued by a licence service for FairPlay, Widevine and PlayReady.",
      "",
      "## Metadata, engagement and search",
      "",
      "Video and channel metadata live in a store sharded by `video_id` with a read-through cache in front of the watch page. **No counter is incremented synchronously.** Watch, like and comment events go to a log; a streaming job aggregates views with bot filtering and dedup, showing an approximate count quickly while a batch job produces the exact figure used for payouts. Comments are stored by `(video_id, time)` for cheap pagination. Search is an inverted index over titles, descriptions, captions and channel names, fed by change data capture from the metadata store; it is eventually consistent, and unpublishing a video triggers a priority delete so blocked content disappears quickly.",
      "",
      "## The recommendations interface",
      "",
      "Treat ranking as a separate system with a contract: `GET /recommendations?user_id&context&limit` returns ordered ids with a deadline of ~100 ms. The platform supplies the event stream and the metadata; the caller owns the **fallbacks** — trending by region, then subscriptions — so a slow recommender never blanks the home page.",
      "",
      "## Rate limiting",
      "",
      "Per-account upload quotas and concurrent-session limits, per-key API quotas, and stricter limits on comments and likes, where abuse concentrates. Apply them at the gateway with token buckets and return `429` with a retry hint.",
      "",
      "## Multi-region",
      "",
      "Uploads go to the nearest region; processing runs there; finished renditions replicate to the regions where the audience is, lazily for the long tail. Metadata uses a primary per video with asynchronous cross-region replicas, which is enough for reads; a region failure promotes replicas and may lose seconds of counters, which the event log can replay. The CDN hides most origin outages for anything already cached.",
      "",
      "## Cost levers",
      "",
      "- **Codec by popularity:** AV1 or HEVC cuts bits ~30% but costs several times the CPU; encode only videos whose projected egress repays it.",
      "- **Per-title encoding:** tune the ladder per video so simple content is not over-provisioned.",
      "- **Cache hit ratio:** every point of CDN hit ratio is petabytes of origin egress.",
      "- **Tiering and reduced ladders** for the long tail.",
      "",
      "## What to measure",
      "",
      "Time from upload to playable, transcode failure rate, start-up time, rebuffer ratio, average delivered bitrate, CDN hit ratio by tier, and cost per delivered hour.",
      "",
      "## Probes to expect",
      "",
      "- *Live streaming?* A different ingest (RTMP or SRT), one-pass low-latency encoding and much shorter segments; the delivery tier is shared.",
      "- *A creator re-uploads the same file?* Content hashing deduplicates the source; metadata is still separate.",
    ].join("\n"),
  },
];
