import type { Problem } from "./types";

// Apple system-design prompts reported for Software Engineer loops (PracHub's
// Apple list, 2025–2026), part E: a marketplace catalog and a local-business
// reviews platform. Prompts are restated in our own words.

export const appleDesignProblemsE: Problem[] = [
  {
    slug: "design-marketplace-catalog",
    title: "Design a Marketplace Catalog System",
    category: "system-design",
    difficulty: "hard",
    companies: ["apple"],
    summary:
      "Category-driven attribute schemas, products versus offers, and a search index that is always rebuildable from the source of truth.",
    prompt: [
      "Design the catalog for a large marketplace: hundreds of millions of items across thousands of categories, supplied by many sellers and partners, browsed and searched by shoppers in many locales.",
      "",
      "The catalog must model categories, per-category attributes and product variants (one shirt, many sizes and colours); ingest items through APIs and bulk feeds; keep versions; detect duplicates of the same product from different sellers; and moderate what is published. Search and browse are served from an index, not from the source of truth.",
      "",
      "Cover: the data model; read and write APIs; ingestion, validation, versioning, deduplication and moderation; how the search and browse index is built and kept up to date, including partial updates; localization; caching; consistency between the source of truth and the index; schema evolution; multi-tenant isolation; and backfill and reprocessing.",
      "",
      "*Reported as: a large marketplace catalog system, one of two systems in a single onsite round (PracHub, Apple Software Engineer onsite, Sep 2025).*",
    ].join("\n"),
    hints: [
      "Separate the canonical product (what the thing is) from the offer (who sells it, at what price, with what stock). Deduplication merges products; offers stay per seller. Variants hang off a parent product along declared axes.",
      "Attributes are data, not columns: each category owns a versioned schema of typed attributes, items are validated against it on write, and facets in search come straight from it.",
      "The index is a derived view. Feed it from an outbox or change stream with per-document versions so stale updates are rejected, and make a full rebuild a routine operation — new index, backfill, alias swap.",
    ],
    rubric: [
      "- **Data model** — category taxonomy, versioned per-category attribute schemas with types and constraints, parent product with variant axes and SKUs, and canonical products separated from seller offers.",
      "- **Write path** — API and bulk ingestion through the same validation, item-level errors, draft/review/published lifecycle, immutable versions with optimistic concurrency, and idempotent writes.",
      "- **Deduplication and moderation** — exact identifiers first, then blocking plus similarity or learned matching with a human-review band; merge and un-merge are reversible; moderation combines automated rules with a review queue and takes effect quickly in search.",
      "- **Index pipeline and consistency** — change stream or outbox from the source of truth, denormalised documents, external versioning, partial updates for price and stock, reconciliation between store and index, and read-your-writes for sellers.",
      "- **Localization and caching** — per-locale translatable fields with fallback, units and currency handling, and cache keys that include version and locale with explicit invalidation.",
      "- **Evolution, isolation and reprocessing** — additive schema changes and backfills for new requirements, tenant quotas and fair scheduling for ingestion, and replayable backfills with a blue/green index swap.",
    ].join("\n"),
    solution: [
      "## Model",
      "",
      "```",
      "category          id, parent_id, path, schema_version                      -- a tree, small, cached everywhere",
      "attribute_def     (category_id, name) -> type, unit, enum, required, facetable, localizable, version",
      "product           product_id, category_id, brand, identifiers (GTIN, MPN), attributes{}, variant_axes[], state, version",
      "sku               sku_id, product_id, axis_values{colour, size}, attributes{}",
      "offer             (sku_id, seller_id) -> price, currency, stock, condition, shipping, state, version",
      "product_l10n      (product_id, locale) -> title, description, translated attribute values",
      "```",
      "",
      "Two separations carry the design. **Product versus offer:** the product is the canonical description shared by everyone selling it; the offer is one seller's price and stock. Price and stock change constantly, descriptions rarely, and duplicates are a product-level problem. **Schema versus data:** a category declares its attributes — type, unit, allowed values, required or not, whether it is a facet — and inherits from its ancestors. Attributes are validated on write and stored as a document column, so adding a category never needs a table change.",
      "",
      "Store the source of truth in a sharded relational or distributed SQL database keyed by `product_id` (offers co-located by `sku_id`), because lifecycle transitions, merges and versioning want transactions.",
      "",
      "## APIs",
      "",
      "```",
      "POST /products            Idempotency-Key            -> 201 { product_id, version, state: draft }",
      "PUT  /products/{id}       If-Match: <version>        -> 200 | 412 stale | 422 { item-level errors }",
      "PUT  /offers/{sku}/{seller}   { price, stock }       -> 200        high-rate partial update",
      "POST /feeds               bulk file                  -> 202 { feed_id };  GET /feeds/{id} -> per-row results",
      "GET  /products/{id}?locale=   |   GET /search?q=&category=&facets=&locale=",
      "```",
      "",
      "## Ingestion, validation, versioning",
      "",
      "API calls and bulk feeds go through the same validator: category exists, required attributes present, types and units valid, variant axes consistent. Feeds are split into chunks on a queue; errors are per row, never per file. Every accepted change creates an immutable version; writes carry `If-Match` so concurrent editors cannot clobber each other, and an idempotency key makes retries safe. Lifecycle: `draft → in_review → published → suppressed`.",
      "",
      "## Deduplication",
      "",
      "Match in stages: exact global identifiers (GTIN, brand plus part number) first; then candidate generation by blocking keys (brand, category, normalised model tokens) and a similarity or learned model over titles, attributes and images. High-confidence matches merge automatically, a middle band goes to human review, the rest stay separate. A merge re-points offers to the surviving product and records a redirect, so it is **reversible** — wrong merges happen and must be undoable.",
      "",
      "## Moderation",
      "",
      "Automated checks (prohibited categories, restricted words, image classifiers, price sanity) run in the pipeline; uncertain cases enter a review queue with service-level targets. A suppression is a state change that propagates to the index on a **priority lane**, so blocked content disappears in seconds even while a bulk reindex is running.",
      "",
      "## Index pipeline and consistency",
      "",
      "Each committed change writes an outbox row in the same transaction; a relay publishes it to a log partitioned by `product_id`. Indexers build a **denormalised document** per product (or per SKU where variants differ in searchable ways): category path, facet attributes, localized text, best offer price, availability. Writes to the index use the source version as an **external version**, so a delayed older event can never overwrite a newer document. Price and stock take a partial-update lane that touches only those fields.",
      "",
      "The index is eventually consistent — typically a few seconds behind. Sellers get read-your-writes by reading their own items from the source of truth. A reconciler samples and sweeps `(id, version)` pairs between store and index and repairs drift, and lag is an alerting metric.",
      "",
      "## Localization",
      "",
      "Translatable fields live per locale with a fallback chain (`fr-CA → fr → en`). Numeric attributes are stored in canonical units and rendered per locale; currency conversion belongs to offers. The index carries per-locale text fields with locale-appropriate analysers.",
      "",
      "## Caching",
      "",
      "Product pages cache by `(product_id, version, locale)`, so a new version is a new key and nothing needs purging; offers cache briefly with explicit invalidation on change. The taxonomy and schemas are tiny and cached in every service with a version check.",
      "",
      "## Schema evolution",
      "",
      "Schema changes are versioned and additive by default. Making an attribute required applies to new writes first; existing items are flagged and backfilled (by rule, by model, or by asking sellers) before enforcement. Moving a category subtree triggers re-validation and reindexing of just the affected items.",
      "",
      "## Multi-tenant isolation",
      "",
      "Every row carries the tenant or seller id and authorisation is enforced in the service layer. Ingestion uses per-tenant queues with fair scheduling and quotas, so a 50M-row feed cannot starve a small seller; large tenants can be pinned to their own partitions.",
      "",
      "## Backfill and reprocessing",
      "",
      "Because the index is derived, a mapping change or an analyser fix is a rebuild: create a new index, replay from the source of truth (rate limited, idempotent by version) while live updates dual-write, verify counts and sampled documents, then **swap the alias**. The same replay machinery serves re-running dedup or moderation with new rules.",
      "",
      "## Probes to expect",
      "",
      "- *Why not search the database?* Faceted full-text ranking across hundreds of millions of items is what an inverted index is for; the database stays the transactional truth.",
      "- *A seller updates stock 100 times a second?* Coalesce per key in the partial-update lane; only the latest value matters.",
    ].join("\n"),
  },
  {
    slug: "design-local-business-reviews",
    title: "Design and Scale a Yelp-like Reviews Platform",
    category: "system-design",
    difficulty: "hard",
    companies: ["apple"],
    summary:
      "Geo plus text search over a read-heavy model, with review writes fanned out through queues to aggregates and the index.",
    prompt: [
      "Design a local-business reviews platform in the shape of Yelp: people search for businesses near a location, open a business page, read and write reviews, rate, upload photos and check in.",
      "",
      "Define the core data model — users, businesses with coordinates and categories, reviews, ratings, photos, check-ins, and the indexes. Then explain how you scale **reads** (replication, caches, CDN, search indexes) and **writes** (sharding, queues, consistency, backfills), how search and geospatial queries work, how caches are invalidated, and what you do for performance.",
      "",
      "The same reported round also asked for a URL shortener; practise that separately at [Design a URL Shortener](/problems/design-url-shortener).",
      "",
      "*Reported as: a Yelp-like local-business reviews platform plus a URL shortener in one onsite round (PracHub, Apple Software Engineer onsite, Sep 2025).*",
    ].join("\n"),
    hints: [
      "The defining query is 'category or keyword near a point'. Pick a spatial index you can explain — geohash prefixes, S2 cells or a quadtree — and describe covering the search radius with cells, fetching candidates, then filtering by true distance and ranking.",
      "Reads outnumber writes by orders of magnitude, so precompute: rating aggregates per business, denormalised search documents, cached business pages, photos on a CDN.",
      "Shard reviews by business so a business page is one shard, and push everything else a review triggers — aggregate update, search reindex, spam scoring, the author's profile — through a queue with idempotent consumers.",
    ],
    rubric: [
      "- **Data model** — users, businesses (coordinates, spatial cell, categories, hours), reviews, rating aggregates, photos in object storage, check-ins as append-only events, and the secondary indexes each access path needs.",
      "- **Geospatial and text search** — a concrete spatial index, cell covering of the query radius, exact-distance filtering, ranking that blends relevance, rating, distance and open-now, and handling of dense versus sparse areas.",
      "- **Read scaling** — replicas, a cache for business pages and aggregates, CDN for photos, a separate search cluster, and protection against cache stampedes.",
      "- **Write scaling and consistency** — shard key choices for reviews and check-ins, queue-driven fan-out with idempotent consumers, read-your-writes for authors, eventual consistency elsewhere, and recomputable aggregates.",
      "- **Cache invalidation** — explicit invalidation or versioned keys on writes, time-to-live for aggregates, and stale-while-revalidate or request coalescing for hot keys.",
      "- **Operations** — backfills and reindexing without downtime, spam and abuse handling for reviews, and latency targets with the metrics to check them.",
    ].join("\n"),
    solution: [
      "## Requirements and numbers",
      "",
      "Assume 100M monthly users, 10M businesses, 200M reviews and a read-to-write ratio above 100:1. Search peaks at perhaps 20k queries/s; review writes at a few hundred per second. The system is a read-optimised view over a modest write stream, and nearly every choice follows from that.",
      "",
      "## Data model",
      "",
      "```",
      "business      id, name, lat, lng, cell_id, categories[], hours, attributes, photo_count",
      "rating_agg    business_id -> count, sum, histogram[1..5]                    -- maintained, recomputable",
      "review        (business_id, review_id) -> user_id, rating, text, created_at, status",
      "review_by_user (user_id, created_at) -> business_id, review_id              -- secondary view, async",
      "photo         (business_id, photo_id) -> object key, user_id, caption       -- bytes in object storage",
      "checkin       (business_id, ts) -> user_id                                  -- append-only events",
      "```",
      "",
      "Businesses and aggregates are small and hot; reviews are large and mostly cold; photos are bytes that belong on a CDN; check-ins are an event stream that mainly feeds counters and ranking signals.",
      "",
      "## Search: text plus geography",
      "",
      "Each business is a document in a search cluster: name and category text, attributes as filters, a geo-point, plus ranking features (rating, review count, check-in velocity). For the spatial part, map coordinates to hierarchical cells — geohash, S2 or a quadtree. A query for 'pizza within 2 km' computes the set of cells covering the circle, retrieves documents in those cells matching the text and filters, filters by exact distance, and ranks by a blend of text relevance, rating with a confidence adjustment (a 5.0 from two reviews must not beat a 4.6 from two thousand), distance and open-now.",
      "",
      "Density varies enormously, so use adaptive cell levels: small cells downtown, large cells in the countryside, and widen the radius automatically when too few results come back. Shard the index by region so a local query touches few shards. Popular (cell, category) combinations can be precomputed and cached, since millions of people ask the same question about the same neighbourhood.",
      "",
      "## Scaling reads",
      "",
      "- **Business page:** served from a cache keyed by business id — profile, aggregate, first page of reviews — with a read replica behind it.",
      "- **Photos:** object storage behind a CDN with immutable, size-specific URLs.",
      "- **Search:** its own cluster with replicas per shard; it is never queried for data the page can get by key.",
      "- **Stampedes:** hot keys use request coalescing and stale-while-revalidate, so an expiring entry for a famous restaurant triggers one recompute, not ten thousand.",
      "",
      "## Scaling writes",
      "",
      "Reviews shard by `business_id`, so rendering a business page reads one shard and the review insert and the aggregate update can share a local transaction. The author's list of reviews is a secondary view built asynchronously. Check-ins go straight to a log and are aggregated by a stream job.",
      "",
      "A new review emits an event, and queue consumers do the rest: spam and fraud scoring (which may hold the review), search document refresh, the by-user view, notifications to the owner. Consumers are idempotent — keyed by review id and version — because the queue delivers at least once.",
      "",
      "## Consistency",
      "",
      "The author must see their review immediately: read it from the primary, or overlay it client-side until replicas catch up. Everyone else can be seconds behind. The aggregate is updated with the review, but it is **recomputable**: a periodic batch job rebuilds counts and histograms from the review table and repairs drift — the same job that backfills when moderation removes a ring of fake reviews.",
      "",
      "## Cache invalidation",
      "",
      "Writes that change a business page delete or version its cache entry explicitly; aggregates also carry a short time-to-live as a safety net. Search result caches are keyed by (cell, query, filters) with a time-to-live of minutes, because freshness there is a ranking nicety, not a correctness issue.",
      "",
      "## Backfills and reindexing",
      "",
      "Changing the ranking features or the analyser means rebuilding the index: build a new index from the source of truth while live updates dual-write, verify, and swap an alias. Aggregate backfills run per business in batches, throttled, idempotent.",
      "",
      "## Performance targets",
      "",
      "Search p99 under 200 ms, business page under 100 ms from cache. Watch cache hit ratio, index lag from write to searchable, replica lag, queue depth, and the share of queries that had to widen their radius.",
      "",
      "## Probes to expect",
      "",
      "- *Why not a geospatial query in the primary database?* It works for small scale; at this read volume the combination with full-text ranking belongs in a search engine with its own replicas.",
      "- *Hot business during a news event?* It is one cache key; coalescing and a slightly longer time-to-live absorb it, and its review writes still land on one shard that can be split by review id range if needed.",
      "- *Fake reviews?* Score asynchronously, hold suspicious ones out of the aggregate, and make the aggregate recomputable so removals are clean.",
    ].join("\n"),
  },
];
